// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package networkrouter

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-validators/dynamicvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/HPE/terraform-provider-hpe/utils/validators"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func NetworkRouterResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cloud_id": schema.Int64Attribute{
				Optional:            true,
				Description:         "Required when router type does not support a network integration",
				MarkdownDescription: "Required when router type does not support a network integration",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
				Validators: []validator.Int64{
					int64validator.ConflictsWith(path.Expressions{
						path.MatchRoot("network_integration_id"),
					}...),
				},
			},
			"code": schema.StringAttribute{
				Computed: true,
			},
			"config": schema.DynamicAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Generic configuration object for network routers.",
				MarkdownDescription: "Generic configuration object for network routers.",
				Validators: []validator.Dynamic{
					validators.ValidObjectMap(),
					dynamicvalidator.ConflictsWith(path.Expressions{
						path.MatchRoot("config_nsxt_gateway_tier0"),
						path.MatchRoot("config_nsxt_gateway_tier1"),
					}...),
					dynamicvalidator.ExactlyOneOf(path.Expressions{
						path.MatchRoot("config"),
						path.MatchRoot("config_nsxt_gateway_tier0"),
						path.MatchRoot("config_nsxt_gateway_tier1"),
					}...),
				},
			},
			"config_nsxt_gateway_tier0": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"ecmp": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"edge_cluster": schema.StringAttribute{
						Optional:            true,
						Description:         "If set, also requires fail_over to be set.",
						MarkdownDescription: "If set, also requires fail_over to be set.",
						Validators: []validator.String{
							stringvalidator.AlsoRequires(path.Expressions{
								path.MatchRelative().AtParent().AtName("fail_over"),
							}...),
						},
					},
					"fail_over": schema.StringAttribute{
						Optional:            true,
						Description:         "Required with edge_cluster.",
						MarkdownDescription: "Required with edge_cluster.",
						Validators: []validator.String{
							stringvalidator.OneOf(
								"NON_PREEMPTIVE",
								"PREEMPTIVE",
							),
						},
					},
					"ha_mode": schema.StringAttribute{
						Required: true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"ACTIVE_ACTIVE",
								"ACTIVE_STANDBY",
							),
						},
					},
					"inter_sr_ibgp": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"ip_management_type": schema.StringAttribute{
						Optional: true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"dhcpLocal",
							),
						},
					},
					"ip_server_id": schema.StringAttribute{
						Optional: true,
					},
					"local_as_num": schema.StringAttribute{
						Optional: true,
						Computed: true,
						Default:  stringdefault.StaticString("65000"),
					},
					"multipath_relax": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"restart_mode": schema.StringAttribute{
						Required: true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"HELPER_ONLY",
								"GR_AND_HELPER",
								"DISABLE",
							),
						},
					},
					"restart_time": schema.Int64Attribute{
						Optional: true,
					},
					"stale_route_time": schema.Int64Attribute{
						Optional: true,
					},
					"tier0_dns_forwarder_ip": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier0_external_interface": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier0_ipsec_local_ip": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier0_loopback_interface": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier0_nat": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier0_segment": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier0_service_interface": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier0_static": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier1_dns_forwarder_ip": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier1_ipsec_local_endpoint": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier1_lb_snat": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier1_lb_vip": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier1_nat": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier1_segment": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier1_service_interface": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier1_static": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
				},
				CustomType: ConfigNsxtGatewayTier0Type{
					ObjectType: types.ObjectType{
						AttrTypes: ConfigNsxtGatewayTier0Value{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Description:         "Configuration object for NSX-T Tier-0 gateway network routers.",
				MarkdownDescription: "Configuration object for NSX-T Tier-0 gateway network routers.",
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplace(),
				},
			},
			"config_nsxt_gateway_tier1": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"edge_cluster": schema.StringAttribute{
						Optional:            true,
						Description:         "If set, also requires fail_over to be set.",
						MarkdownDescription: "If set, also requires fail_over to be set.",
						Validators: []validator.String{
							stringvalidator.AlsoRequires(path.Expressions{
								path.MatchRelative().AtParent().AtName("fail_over"),
							}...),
						},
					},
					"fail_over": schema.StringAttribute{
						Optional:            true,
						Description:         "Required with edge_cluster.",
						MarkdownDescription: "Required with edge_cluster.",
						Validators: []validator.String{
							stringvalidator.OneOf(
								"NON_PREEMPTIVE",
								"PREEMPTIVE",
							),
						},
					},
					"ip_management_type": schema.StringAttribute{
						Optional: true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"dhcpLocal",
							),
						},
					},
					"ip_server_id": schema.StringAttribute{
						Optional: true,
					},
					"tier0_gateway": schema.StringAttribute{
						Optional: true,
					},
					"tier1_connected": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier1_dns_forwarder_ip": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier1_ipsec_local_endpoint": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier1_lb_snat": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier1_lb_vip": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier1_nat": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
					"tier1_static_routes": schema.BoolAttribute{
						Optional: true,
						Computed: true,
						Default:  booldefault.StaticBool(false),
					},
				},
				CustomType: ConfigNsxtGatewayTier1Type{
					ObjectType: types.ObjectType{
						AttrTypes: ConfigNsxtGatewayTier1Value{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Description:         "Configuration object for NSX-T Tier-1 gateway network routers.",
				MarkdownDescription: "Configuration object for NSX-T Tier-1 gateway network routers.",
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplace(),
				},
			},
			"enable_bgp": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.RequiresReplace(),
				},
				Default: booldefault.StaticBool(false),
			},
			"enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Can be used to enable / disable the network router (true, false). Default is on",
				MarkdownDescription: "Can be used to enable / disable the network router (true, false). Default is on",
				Default:             booldefault.StaticBool(true),
			},
			"group_id": schema.Int64Attribute{
				Required:            true,
				Description:         "Group ID",
				MarkdownDescription: "Group ID",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
				Validators: []validator.Int64{
					int64validator.ConflictsWith(path.Expressions{
						path.MatchRoot("group_id"),
					}...),
				},
			},
			"id": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name",
				MarkdownDescription: "Name",
			},
			"network_integration_id": schema.Int64Attribute{
				Optional:            true,
				Description:         "Required when router type supports a network integration",
				MarkdownDescription: "Required when router type supports a network integration",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
				Validators: []validator.Int64{
					int64validator.ConflictsWith(path.Expressions{
						path.MatchRoot("cloud_id"),
					}...),
				},
			},
			"shared_group_access": schema.BoolAttribute{
				Optional:            true,
				Description:         "Used to enable shared group access. Conflicts with group_id.",
				MarkdownDescription: "Used to enable shared group access. Conflicts with group_id.",
			},
			"type_id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The network router type ID. Must be set if using generic config block. The provider will attempt to set this automatically if using a static config block.",
				MarkdownDescription: "The network router type ID. Must be set if using generic config block. The provider will attempt to set this automatically if using a static config block.",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
				Validators: []validator.Int64{
					int64validator.AlsoRequires(path.Expressions{path.MatchRoot("config")}...),
				},
			},
		},
	}
}

type NetworkRouterModel struct {
	CloudId                types.Int64                 `tfsdk:"cloud_id"`
	Code                   types.String                `tfsdk:"code"`
	Config                 types.Dynamic               `tfsdk:"config"`
	ConfigNsxtGatewayTier0 ConfigNsxtGatewayTier0Value `tfsdk:"config_nsxt_gateway_tier0"`
	ConfigNsxtGatewayTier1 ConfigNsxtGatewayTier1Value `tfsdk:"config_nsxt_gateway_tier1"`
	EnableBgp              types.Bool                  `tfsdk:"enable_bgp"`
	Enabled                types.Bool                  `tfsdk:"enabled"`
	GroupId                types.Int64                 `tfsdk:"group_id"`
	Id                     types.Int64                 `tfsdk:"id"`
	Name                   types.String                `tfsdk:"name"`
	NetworkIntegrationId   types.Int64                 `tfsdk:"network_integration_id"`
	SharedGroupAccess      types.Bool                  `tfsdk:"shared_group_access"`
	TypeId                 types.Int64                 `tfsdk:"type_id"`
}

var _ basetypes.ObjectTypable = ConfigNsxtGatewayTier0Type{}

type ConfigNsxtGatewayTier0Type struct {
	basetypes.ObjectType
}

func (t ConfigNsxtGatewayTier0Type) Equal(o attr.Type) bool {
	other, ok := o.(ConfigNsxtGatewayTier0Type)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConfigNsxtGatewayTier0Type) String() string {
	return "ConfigNsxtGatewayTier0Type"
}

func (t ConfigNsxtGatewayTier0Type) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewConfigNsxtGatewayTier0ValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigNsxtGatewayTier0ValueNull(), nil
	}

	attributes := in.Attributes()

	ecmpAttribute, ok := attributes["ecmp"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ecmp is missing from object`,
		)

		return nil, diags
	}

	ecmpVal, ok := ecmpAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ecmp expected to be basetypes.BoolValue, was: %T`, ecmpAttribute),
		)
	}

	edgeClusterAttribute, ok := attributes["edge_cluster"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`edge_cluster is missing from object`,
		)

		return nil, diags
	}

	edgeClusterVal, ok := edgeClusterAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`edge_cluster expected to be basetypes.StringValue, was: %T`, edgeClusterAttribute),
		)
	}

	failOverAttribute, ok := attributes["fail_over"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fail_over is missing from object`,
		)

		return nil, diags
	}

	failOverVal, ok := failOverAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fail_over expected to be basetypes.StringValue, was: %T`, failOverAttribute),
		)
	}

	haModeAttribute, ok := attributes["ha_mode"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ha_mode is missing from object`,
		)

		return nil, diags
	}

	haModeVal, ok := haModeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ha_mode expected to be basetypes.StringValue, was: %T`, haModeAttribute),
		)
	}

	interSrIbgpAttribute, ok := attributes["inter_sr_ibgp"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`inter_sr_ibgp is missing from object`,
		)

		return nil, diags
	}

	interSrIbgpVal, ok := interSrIbgpAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`inter_sr_ibgp expected to be basetypes.BoolValue, was: %T`, interSrIbgpAttribute),
		)
	}

	ipManagementTypeAttribute, ok := attributes["ip_management_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_management_type is missing from object`,
		)

		return nil, diags
	}

	ipManagementTypeVal, ok := ipManagementTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_management_type expected to be basetypes.StringValue, was: %T`, ipManagementTypeAttribute),
		)
	}

	ipServerIdAttribute, ok := attributes["ip_server_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_server_id is missing from object`,
		)

		return nil, diags
	}

	ipServerIdVal, ok := ipServerIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_server_id expected to be basetypes.StringValue, was: %T`, ipServerIdAttribute),
		)
	}

	localAsNumAttribute, ok := attributes["local_as_num"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`local_as_num is missing from object`,
		)

		return nil, diags
	}

	localAsNumVal, ok := localAsNumAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`local_as_num expected to be basetypes.StringValue, was: %T`, localAsNumAttribute),
		)
	}

	multipathRelaxAttribute, ok := attributes["multipath_relax"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`multipath_relax is missing from object`,
		)

		return nil, diags
	}

	multipathRelaxVal, ok := multipathRelaxAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`multipath_relax expected to be basetypes.BoolValue, was: %T`, multipathRelaxAttribute),
		)
	}

	restartModeAttribute, ok := attributes["restart_mode"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`restart_mode is missing from object`,
		)

		return nil, diags
	}

	restartModeVal, ok := restartModeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`restart_mode expected to be basetypes.StringValue, was: %T`, restartModeAttribute),
		)
	}

	restartTimeAttribute, ok := attributes["restart_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`restart_time is missing from object`,
		)

		return nil, diags
	}

	restartTimeVal, ok := restartTimeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`restart_time expected to be basetypes.Int64Value, was: %T`, restartTimeAttribute),
		)
	}

	staleRouteTimeAttribute, ok := attributes["stale_route_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`stale_route_time is missing from object`,
		)

		return nil, diags
	}

	staleRouteTimeVal, ok := staleRouteTimeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`stale_route_time expected to be basetypes.Int64Value, was: %T`, staleRouteTimeAttribute),
		)
	}

	tier0DnsForwarderIpAttribute, ok := attributes["tier0_dns_forwarder_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier0_dns_forwarder_ip is missing from object`,
		)

		return nil, diags
	}

	tier0DnsForwarderIpVal, ok := tier0DnsForwarderIpAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier0_dns_forwarder_ip expected to be basetypes.BoolValue, was: %T`, tier0DnsForwarderIpAttribute),
		)
	}

	tier0ExternalInterfaceAttribute, ok := attributes["tier0_external_interface"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier0_external_interface is missing from object`,
		)

		return nil, diags
	}

	tier0ExternalInterfaceVal, ok := tier0ExternalInterfaceAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier0_external_interface expected to be basetypes.BoolValue, was: %T`, tier0ExternalInterfaceAttribute),
		)
	}

	tier0IpsecLocalIpAttribute, ok := attributes["tier0_ipsec_local_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier0_ipsec_local_ip is missing from object`,
		)

		return nil, diags
	}

	tier0IpsecLocalIpVal, ok := tier0IpsecLocalIpAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier0_ipsec_local_ip expected to be basetypes.BoolValue, was: %T`, tier0IpsecLocalIpAttribute),
		)
	}

	tier0LoopbackInterfaceAttribute, ok := attributes["tier0_loopback_interface"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier0_loopback_interface is missing from object`,
		)

		return nil, diags
	}

	tier0LoopbackInterfaceVal, ok := tier0LoopbackInterfaceAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier0_loopback_interface expected to be basetypes.BoolValue, was: %T`, tier0LoopbackInterfaceAttribute),
		)
	}

	tier0NatAttribute, ok := attributes["tier0_nat"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier0_nat is missing from object`,
		)

		return nil, diags
	}

	tier0NatVal, ok := tier0NatAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier0_nat expected to be basetypes.BoolValue, was: %T`, tier0NatAttribute),
		)
	}

	tier0SegmentAttribute, ok := attributes["tier0_segment"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier0_segment is missing from object`,
		)

		return nil, diags
	}

	tier0SegmentVal, ok := tier0SegmentAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier0_segment expected to be basetypes.BoolValue, was: %T`, tier0SegmentAttribute),
		)
	}

	tier0ServiceInterfaceAttribute, ok := attributes["tier0_service_interface"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier0_service_interface is missing from object`,
		)

		return nil, diags
	}

	tier0ServiceInterfaceVal, ok := tier0ServiceInterfaceAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier0_service_interface expected to be basetypes.BoolValue, was: %T`, tier0ServiceInterfaceAttribute),
		)
	}

	tier0StaticAttribute, ok := attributes["tier0_static"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier0_static is missing from object`,
		)

		return nil, diags
	}

	tier0StaticVal, ok := tier0StaticAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier0_static expected to be basetypes.BoolValue, was: %T`, tier0StaticAttribute),
		)
	}

	tier1DnsForwarderIpAttribute, ok := attributes["tier1_dns_forwarder_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_dns_forwarder_ip is missing from object`,
		)

		return nil, diags
	}

	tier1DnsForwarderIpVal, ok := tier1DnsForwarderIpAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_dns_forwarder_ip expected to be basetypes.BoolValue, was: %T`, tier1DnsForwarderIpAttribute),
		)
	}

	tier1IpsecLocalEndpointAttribute, ok := attributes["tier1_ipsec_local_endpoint"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_ipsec_local_endpoint is missing from object`,
		)

		return nil, diags
	}

	tier1IpsecLocalEndpointVal, ok := tier1IpsecLocalEndpointAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_ipsec_local_endpoint expected to be basetypes.BoolValue, was: %T`, tier1IpsecLocalEndpointAttribute),
		)
	}

	tier1LbSnatAttribute, ok := attributes["tier1_lb_snat"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_lb_snat is missing from object`,
		)

		return nil, diags
	}

	tier1LbSnatVal, ok := tier1LbSnatAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_lb_snat expected to be basetypes.BoolValue, was: %T`, tier1LbSnatAttribute),
		)
	}

	tier1LbVipAttribute, ok := attributes["tier1_lb_vip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_lb_vip is missing from object`,
		)

		return nil, diags
	}

	tier1LbVipVal, ok := tier1LbVipAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_lb_vip expected to be basetypes.BoolValue, was: %T`, tier1LbVipAttribute),
		)
	}

	tier1NatAttribute, ok := attributes["tier1_nat"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_nat is missing from object`,
		)

		return nil, diags
	}

	tier1NatVal, ok := tier1NatAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_nat expected to be basetypes.BoolValue, was: %T`, tier1NatAttribute),
		)
	}

	tier1SegmentAttribute, ok := attributes["tier1_segment"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_segment is missing from object`,
		)

		return nil, diags
	}

	tier1SegmentVal, ok := tier1SegmentAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_segment expected to be basetypes.BoolValue, was: %T`, tier1SegmentAttribute),
		)
	}

	tier1ServiceInterfaceAttribute, ok := attributes["tier1_service_interface"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_service_interface is missing from object`,
		)

		return nil, diags
	}

	tier1ServiceInterfaceVal, ok := tier1ServiceInterfaceAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_service_interface expected to be basetypes.BoolValue, was: %T`, tier1ServiceInterfaceAttribute),
		)
	}

	tier1StaticAttribute, ok := attributes["tier1_static"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_static is missing from object`,
		)

		return nil, diags
	}

	tier1StaticVal, ok := tier1StaticAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_static expected to be basetypes.BoolValue, was: %T`, tier1StaticAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConfigNsxtGatewayTier0Value{
		Ecmp:                    ecmpVal,
		EdgeCluster:             edgeClusterVal,
		FailOver:                failOverVal,
		HaMode:                  haModeVal,
		InterSrIbgp:             interSrIbgpVal,
		IpManagementType:        ipManagementTypeVal,
		IpServerId:              ipServerIdVal,
		LocalAsNum:              localAsNumVal,
		MultipathRelax:          multipathRelaxVal,
		RestartMode:             restartModeVal,
		RestartTime:             restartTimeVal,
		StaleRouteTime:          staleRouteTimeVal,
		Tier0DnsForwarderIp:     tier0DnsForwarderIpVal,
		Tier0ExternalInterface:  tier0ExternalInterfaceVal,
		Tier0IpsecLocalIp:       tier0IpsecLocalIpVal,
		Tier0LoopbackInterface:  tier0LoopbackInterfaceVal,
		Tier0Nat:                tier0NatVal,
		Tier0Segment:            tier0SegmentVal,
		Tier0ServiceInterface:   tier0ServiceInterfaceVal,
		Tier0Static:             tier0StaticVal,
		Tier1DnsForwarderIp:     tier1DnsForwarderIpVal,
		Tier1IpsecLocalEndpoint: tier1IpsecLocalEndpointVal,
		Tier1LbSnat:             tier1LbSnatVal,
		Tier1LbVip:              tier1LbVipVal,
		Tier1Nat:                tier1NatVal,
		Tier1Segment:            tier1SegmentVal,
		Tier1ServiceInterface:   tier1ServiceInterfaceVal,
		Tier1Static:             tier1StaticVal,
		state:                   attr.ValueStateKnown,
	}, diags
}

func NewConfigNsxtGatewayTier0ValueNull() ConfigNsxtGatewayTier0Value {
	return ConfigNsxtGatewayTier0Value{
		state: attr.ValueStateNull,
	}
}

func NewConfigNsxtGatewayTier0ValueUnknown() ConfigNsxtGatewayTier0Value {
	return ConfigNsxtGatewayTier0Value{
		state: attr.ValueStateUnknown,
	}
}

func NewConfigNsxtGatewayTier0Value(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConfigNsxtGatewayTier0Value, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConfigNsxtGatewayTier0Value Attribute Value",
				"While creating a ConfigNsxtGatewayTier0Value value, a missing attribute value was detected. "+
					"A ConfigNsxtGatewayTier0Value must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigNsxtGatewayTier0Value Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConfigNsxtGatewayTier0Value Attribute Type",
				"While creating a ConfigNsxtGatewayTier0Value value, an invalid attribute value was detected. "+
					"A ConfigNsxtGatewayTier0Value must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigNsxtGatewayTier0Value Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConfigNsxtGatewayTier0Value Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConfigNsxtGatewayTier0Value Attribute Value",
				"While creating a ConfigNsxtGatewayTier0Value value, an extra attribute value was detected. "+
					"A ConfigNsxtGatewayTier0Value must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConfigNsxtGatewayTier0Value Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	ecmpAttribute, ok := attributes["ecmp"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ecmp is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	ecmpVal, ok := ecmpAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ecmp expected to be basetypes.BoolValue, was: %T`, ecmpAttribute),
		)
	}

	edgeClusterAttribute, ok := attributes["edge_cluster"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`edge_cluster is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	edgeClusterVal, ok := edgeClusterAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`edge_cluster expected to be basetypes.StringValue, was: %T`, edgeClusterAttribute),
		)
	}

	failOverAttribute, ok := attributes["fail_over"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fail_over is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	failOverVal, ok := failOverAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fail_over expected to be basetypes.StringValue, was: %T`, failOverAttribute),
		)
	}

	haModeAttribute, ok := attributes["ha_mode"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ha_mode is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	haModeVal, ok := haModeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ha_mode expected to be basetypes.StringValue, was: %T`, haModeAttribute),
		)
	}

	interSrIbgpAttribute, ok := attributes["inter_sr_ibgp"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`inter_sr_ibgp is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	interSrIbgpVal, ok := interSrIbgpAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`inter_sr_ibgp expected to be basetypes.BoolValue, was: %T`, interSrIbgpAttribute),
		)
	}

	ipManagementTypeAttribute, ok := attributes["ip_management_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_management_type is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	ipManagementTypeVal, ok := ipManagementTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_management_type expected to be basetypes.StringValue, was: %T`, ipManagementTypeAttribute),
		)
	}

	ipServerIdAttribute, ok := attributes["ip_server_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_server_id is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	ipServerIdVal, ok := ipServerIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_server_id expected to be basetypes.StringValue, was: %T`, ipServerIdAttribute),
		)
	}

	localAsNumAttribute, ok := attributes["local_as_num"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`local_as_num is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	localAsNumVal, ok := localAsNumAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`local_as_num expected to be basetypes.StringValue, was: %T`, localAsNumAttribute),
		)
	}

	multipathRelaxAttribute, ok := attributes["multipath_relax"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`multipath_relax is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	multipathRelaxVal, ok := multipathRelaxAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`multipath_relax expected to be basetypes.BoolValue, was: %T`, multipathRelaxAttribute),
		)
	}

	restartModeAttribute, ok := attributes["restart_mode"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`restart_mode is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	restartModeVal, ok := restartModeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`restart_mode expected to be basetypes.StringValue, was: %T`, restartModeAttribute),
		)
	}

	restartTimeAttribute, ok := attributes["restart_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`restart_time is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	restartTimeVal, ok := restartTimeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`restart_time expected to be basetypes.Int64Value, was: %T`, restartTimeAttribute),
		)
	}

	staleRouteTimeAttribute, ok := attributes["stale_route_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`stale_route_time is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	staleRouteTimeVal, ok := staleRouteTimeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`stale_route_time expected to be basetypes.Int64Value, was: %T`, staleRouteTimeAttribute),
		)
	}

	tier0DnsForwarderIpAttribute, ok := attributes["tier0_dns_forwarder_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier0_dns_forwarder_ip is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	tier0DnsForwarderIpVal, ok := tier0DnsForwarderIpAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier0_dns_forwarder_ip expected to be basetypes.BoolValue, was: %T`, tier0DnsForwarderIpAttribute),
		)
	}

	tier0ExternalInterfaceAttribute, ok := attributes["tier0_external_interface"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier0_external_interface is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	tier0ExternalInterfaceVal, ok := tier0ExternalInterfaceAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier0_external_interface expected to be basetypes.BoolValue, was: %T`, tier0ExternalInterfaceAttribute),
		)
	}

	tier0IpsecLocalIpAttribute, ok := attributes["tier0_ipsec_local_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier0_ipsec_local_ip is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	tier0IpsecLocalIpVal, ok := tier0IpsecLocalIpAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier0_ipsec_local_ip expected to be basetypes.BoolValue, was: %T`, tier0IpsecLocalIpAttribute),
		)
	}

	tier0LoopbackInterfaceAttribute, ok := attributes["tier0_loopback_interface"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier0_loopback_interface is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	tier0LoopbackInterfaceVal, ok := tier0LoopbackInterfaceAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier0_loopback_interface expected to be basetypes.BoolValue, was: %T`, tier0LoopbackInterfaceAttribute),
		)
	}

	tier0NatAttribute, ok := attributes["tier0_nat"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier0_nat is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	tier0NatVal, ok := tier0NatAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier0_nat expected to be basetypes.BoolValue, was: %T`, tier0NatAttribute),
		)
	}

	tier0SegmentAttribute, ok := attributes["tier0_segment"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier0_segment is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	tier0SegmentVal, ok := tier0SegmentAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier0_segment expected to be basetypes.BoolValue, was: %T`, tier0SegmentAttribute),
		)
	}

	tier0ServiceInterfaceAttribute, ok := attributes["tier0_service_interface"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier0_service_interface is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	tier0ServiceInterfaceVal, ok := tier0ServiceInterfaceAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier0_service_interface expected to be basetypes.BoolValue, was: %T`, tier0ServiceInterfaceAttribute),
		)
	}

	tier0StaticAttribute, ok := attributes["tier0_static"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier0_static is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	tier0StaticVal, ok := tier0StaticAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier0_static expected to be basetypes.BoolValue, was: %T`, tier0StaticAttribute),
		)
	}

	tier1DnsForwarderIpAttribute, ok := attributes["tier1_dns_forwarder_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_dns_forwarder_ip is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	tier1DnsForwarderIpVal, ok := tier1DnsForwarderIpAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_dns_forwarder_ip expected to be basetypes.BoolValue, was: %T`, tier1DnsForwarderIpAttribute),
		)
	}

	tier1IpsecLocalEndpointAttribute, ok := attributes["tier1_ipsec_local_endpoint"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_ipsec_local_endpoint is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	tier1IpsecLocalEndpointVal, ok := tier1IpsecLocalEndpointAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_ipsec_local_endpoint expected to be basetypes.BoolValue, was: %T`, tier1IpsecLocalEndpointAttribute),
		)
	}

	tier1LbSnatAttribute, ok := attributes["tier1_lb_snat"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_lb_snat is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	tier1LbSnatVal, ok := tier1LbSnatAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_lb_snat expected to be basetypes.BoolValue, was: %T`, tier1LbSnatAttribute),
		)
	}

	tier1LbVipAttribute, ok := attributes["tier1_lb_vip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_lb_vip is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	tier1LbVipVal, ok := tier1LbVipAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_lb_vip expected to be basetypes.BoolValue, was: %T`, tier1LbVipAttribute),
		)
	}

	tier1NatAttribute, ok := attributes["tier1_nat"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_nat is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	tier1NatVal, ok := tier1NatAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_nat expected to be basetypes.BoolValue, was: %T`, tier1NatAttribute),
		)
	}

	tier1SegmentAttribute, ok := attributes["tier1_segment"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_segment is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	tier1SegmentVal, ok := tier1SegmentAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_segment expected to be basetypes.BoolValue, was: %T`, tier1SegmentAttribute),
		)
	}

	tier1ServiceInterfaceAttribute, ok := attributes["tier1_service_interface"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_service_interface is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	tier1ServiceInterfaceVal, ok := tier1ServiceInterfaceAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_service_interface expected to be basetypes.BoolValue, was: %T`, tier1ServiceInterfaceAttribute),
		)
	}

	tier1StaticAttribute, ok := attributes["tier1_static"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_static is missing from object`,
		)

		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	tier1StaticVal, ok := tier1StaticAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_static expected to be basetypes.BoolValue, was: %T`, tier1StaticAttribute),
		)
	}

	if diags.HasError() {
		return NewConfigNsxtGatewayTier0ValueUnknown(), diags
	}

	return ConfigNsxtGatewayTier0Value{
		Ecmp:                    ecmpVal,
		EdgeCluster:             edgeClusterVal,
		FailOver:                failOverVal,
		HaMode:                  haModeVal,
		InterSrIbgp:             interSrIbgpVal,
		IpManagementType:        ipManagementTypeVal,
		IpServerId:              ipServerIdVal,
		LocalAsNum:              localAsNumVal,
		MultipathRelax:          multipathRelaxVal,
		RestartMode:             restartModeVal,
		RestartTime:             restartTimeVal,
		StaleRouteTime:          staleRouteTimeVal,
		Tier0DnsForwarderIp:     tier0DnsForwarderIpVal,
		Tier0ExternalInterface:  tier0ExternalInterfaceVal,
		Tier0IpsecLocalIp:       tier0IpsecLocalIpVal,
		Tier0LoopbackInterface:  tier0LoopbackInterfaceVal,
		Tier0Nat:                tier0NatVal,
		Tier0Segment:            tier0SegmentVal,
		Tier0ServiceInterface:   tier0ServiceInterfaceVal,
		Tier0Static:             tier0StaticVal,
		Tier1DnsForwarderIp:     tier1DnsForwarderIpVal,
		Tier1IpsecLocalEndpoint: tier1IpsecLocalEndpointVal,
		Tier1LbSnat:             tier1LbSnatVal,
		Tier1LbVip:              tier1LbVipVal,
		Tier1Nat:                tier1NatVal,
		Tier1Segment:            tier1SegmentVal,
		Tier1ServiceInterface:   tier1ServiceInterfaceVal,
		Tier1Static:             tier1StaticVal,
		state:                   attr.ValueStateKnown,
	}, diags
}

func NewConfigNsxtGatewayTier0ValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConfigNsxtGatewayTier0Value {
	object, diags := NewConfigNsxtGatewayTier0Value(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewConfigNsxtGatewayTier0ValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConfigNsxtGatewayTier0Type) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConfigNsxtGatewayTier0ValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConfigNsxtGatewayTier0ValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigNsxtGatewayTier0ValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConfigNsxtGatewayTier0ValueMust(ConfigNsxtGatewayTier0Value{}.AttributeTypes(ctx), attributes), nil
}

func (t ConfigNsxtGatewayTier0Type) ValueType(ctx context.Context) attr.Value {
	return ConfigNsxtGatewayTier0Value{}
}

var _ basetypes.ObjectValuable = ConfigNsxtGatewayTier0Value{}

type ConfigNsxtGatewayTier0Value struct {
	Ecmp                    basetypes.BoolValue   `tfsdk:"ecmp"`
	EdgeCluster             basetypes.StringValue `tfsdk:"edge_cluster"`
	FailOver                basetypes.StringValue `tfsdk:"fail_over"`
	HaMode                  basetypes.StringValue `tfsdk:"ha_mode"`
	InterSrIbgp             basetypes.BoolValue   `tfsdk:"inter_sr_ibgp"`
	IpManagementType        basetypes.StringValue `tfsdk:"ip_management_type"`
	IpServerId              basetypes.StringValue `tfsdk:"ip_server_id"`
	LocalAsNum              basetypes.StringValue `tfsdk:"local_as_num"`
	MultipathRelax          basetypes.BoolValue   `tfsdk:"multipath_relax"`
	RestartMode             basetypes.StringValue `tfsdk:"restart_mode"`
	RestartTime             basetypes.Int64Value  `tfsdk:"restart_time"`
	StaleRouteTime          basetypes.Int64Value  `tfsdk:"stale_route_time"`
	Tier0DnsForwarderIp     basetypes.BoolValue   `tfsdk:"tier0_dns_forwarder_ip"`
	Tier0ExternalInterface  basetypes.BoolValue   `tfsdk:"tier0_external_interface"`
	Tier0IpsecLocalIp       basetypes.BoolValue   `tfsdk:"tier0_ipsec_local_ip"`
	Tier0LoopbackInterface  basetypes.BoolValue   `tfsdk:"tier0_loopback_interface"`
	Tier0Nat                basetypes.BoolValue   `tfsdk:"tier0_nat"`
	Tier0Segment            basetypes.BoolValue   `tfsdk:"tier0_segment"`
	Tier0ServiceInterface   basetypes.BoolValue   `tfsdk:"tier0_service_interface"`
	Tier0Static             basetypes.BoolValue   `tfsdk:"tier0_static"`
	Tier1DnsForwarderIp     basetypes.BoolValue   `tfsdk:"tier1_dns_forwarder_ip"`
	Tier1IpsecLocalEndpoint basetypes.BoolValue   `tfsdk:"tier1_ipsec_local_endpoint"`
	Tier1LbSnat             basetypes.BoolValue   `tfsdk:"tier1_lb_snat"`
	Tier1LbVip              basetypes.BoolValue   `tfsdk:"tier1_lb_vip"`
	Tier1Nat                basetypes.BoolValue   `tfsdk:"tier1_nat"`
	Tier1Segment            basetypes.BoolValue   `tfsdk:"tier1_segment"`
	Tier1ServiceInterface   basetypes.BoolValue   `tfsdk:"tier1_service_interface"`
	Tier1Static             basetypes.BoolValue   `tfsdk:"tier1_static"`
	state                   attr.ValueState
}

func (v ConfigNsxtGatewayTier0Value) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 28)

	var val tftypes.Value
	var err error

	attrTypes["ecmp"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["edge_cluster"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["fail_over"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["ha_mode"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["inter_sr_ibgp"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["ip_management_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["ip_server_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["local_as_num"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["multipath_relax"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["restart_mode"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["restart_time"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["stale_route_time"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["tier0_dns_forwarder_ip"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier0_external_interface"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier0_ipsec_local_ip"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier0_loopback_interface"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier0_nat"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier0_segment"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier0_service_interface"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier0_static"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier1_dns_forwarder_ip"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier1_ipsec_local_endpoint"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier1_lb_snat"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier1_lb_vip"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier1_nat"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier1_segment"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier1_service_interface"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier1_static"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 28)

		val, err = v.Ecmp.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ecmp"] = val

		val, err = v.EdgeCluster.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["edge_cluster"] = val

		val, err = v.FailOver.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["fail_over"] = val

		val, err = v.HaMode.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ha_mode"] = val

		val, err = v.InterSrIbgp.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["inter_sr_ibgp"] = val

		val, err = v.IpManagementType.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip_management_type"] = val

		val, err = v.IpServerId.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip_server_id"] = val

		val, err = v.LocalAsNum.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["local_as_num"] = val

		val, err = v.MultipathRelax.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["multipath_relax"] = val

		val, err = v.RestartMode.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["restart_mode"] = val

		val, err = v.RestartTime.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["restart_time"] = val

		val, err = v.StaleRouteTime.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["stale_route_time"] = val

		val, err = v.Tier0DnsForwarderIp.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier0_dns_forwarder_ip"] = val

		val, err = v.Tier0ExternalInterface.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier0_external_interface"] = val

		val, err = v.Tier0IpsecLocalIp.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier0_ipsec_local_ip"] = val

		val, err = v.Tier0LoopbackInterface.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier0_loopback_interface"] = val

		val, err = v.Tier0Nat.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier0_nat"] = val

		val, err = v.Tier0Segment.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier0_segment"] = val

		val, err = v.Tier0ServiceInterface.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier0_service_interface"] = val

		val, err = v.Tier0Static.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier0_static"] = val

		val, err = v.Tier1DnsForwarderIp.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier1_dns_forwarder_ip"] = val

		val, err = v.Tier1IpsecLocalEndpoint.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier1_ipsec_local_endpoint"] = val

		val, err = v.Tier1LbSnat.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier1_lb_snat"] = val

		val, err = v.Tier1LbVip.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier1_lb_vip"] = val

		val, err = v.Tier1Nat.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier1_nat"] = val

		val, err = v.Tier1Segment.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier1_segment"] = val

		val, err = v.Tier1ServiceInterface.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier1_service_interface"] = val

		val, err = v.Tier1Static.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier1_static"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConfigNsxtGatewayTier0Value) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConfigNsxtGatewayTier0Value) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConfigNsxtGatewayTier0Value) String() string {
	return "ConfigNsxtGatewayTier0Value"
}

func (v ConfigNsxtGatewayTier0Value) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"ecmp":                       basetypes.BoolType{},
		"edge_cluster":               basetypes.StringType{},
		"fail_over":                  basetypes.StringType{},
		"ha_mode":                    basetypes.StringType{},
		"inter_sr_ibgp":              basetypes.BoolType{},
		"ip_management_type":         basetypes.StringType{},
		"ip_server_id":               basetypes.StringType{},
		"local_as_num":               basetypes.StringType{},
		"multipath_relax":            basetypes.BoolType{},
		"restart_mode":               basetypes.StringType{},
		"restart_time":               basetypes.Int64Type{},
		"stale_route_time":           basetypes.Int64Type{},
		"tier0_dns_forwarder_ip":     basetypes.BoolType{},
		"tier0_external_interface":   basetypes.BoolType{},
		"tier0_ipsec_local_ip":       basetypes.BoolType{},
		"tier0_loopback_interface":   basetypes.BoolType{},
		"tier0_nat":                  basetypes.BoolType{},
		"tier0_segment":              basetypes.BoolType{},
		"tier0_service_interface":    basetypes.BoolType{},
		"tier0_static":               basetypes.BoolType{},
		"tier1_dns_forwarder_ip":     basetypes.BoolType{},
		"tier1_ipsec_local_endpoint": basetypes.BoolType{},
		"tier1_lb_snat":              basetypes.BoolType{},
		"tier1_lb_vip":               basetypes.BoolType{},
		"tier1_nat":                  basetypes.BoolType{},
		"tier1_segment":              basetypes.BoolType{},
		"tier1_service_interface":    basetypes.BoolType{},
		"tier1_static":               basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"ecmp":                       v.Ecmp,
			"edge_cluster":               v.EdgeCluster,
			"fail_over":                  v.FailOver,
			"ha_mode":                    v.HaMode,
			"inter_sr_ibgp":              v.InterSrIbgp,
			"ip_management_type":         v.IpManagementType,
			"ip_server_id":               v.IpServerId,
			"local_as_num":               v.LocalAsNum,
			"multipath_relax":            v.MultipathRelax,
			"restart_mode":               v.RestartMode,
			"restart_time":               v.RestartTime,
			"stale_route_time":           v.StaleRouteTime,
			"tier0_dns_forwarder_ip":     v.Tier0DnsForwarderIp,
			"tier0_external_interface":   v.Tier0ExternalInterface,
			"tier0_ipsec_local_ip":       v.Tier0IpsecLocalIp,
			"tier0_loopback_interface":   v.Tier0LoopbackInterface,
			"tier0_nat":                  v.Tier0Nat,
			"tier0_segment":              v.Tier0Segment,
			"tier0_service_interface":    v.Tier0ServiceInterface,
			"tier0_static":               v.Tier0Static,
			"tier1_dns_forwarder_ip":     v.Tier1DnsForwarderIp,
			"tier1_ipsec_local_endpoint": v.Tier1IpsecLocalEndpoint,
			"tier1_lb_snat":              v.Tier1LbSnat,
			"tier1_lb_vip":               v.Tier1LbVip,
			"tier1_nat":                  v.Tier1Nat,
			"tier1_segment":              v.Tier1Segment,
			"tier1_service_interface":    v.Tier1ServiceInterface,
			"tier1_static":               v.Tier1Static,
		},
	)

	return objVal, diags
}

func (v ConfigNsxtGatewayTier0Value) Equal(o attr.Value) bool {
	other, ok := o.(ConfigNsxtGatewayTier0Value)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Ecmp.Equal(other.Ecmp) {
		return false
	}

	if !v.EdgeCluster.Equal(other.EdgeCluster) {
		return false
	}

	if !v.FailOver.Equal(other.FailOver) {
		return false
	}

	if !v.HaMode.Equal(other.HaMode) {
		return false
	}

	if !v.InterSrIbgp.Equal(other.InterSrIbgp) {
		return false
	}

	if !v.IpManagementType.Equal(other.IpManagementType) {
		return false
	}

	if !v.IpServerId.Equal(other.IpServerId) {
		return false
	}

	if !v.LocalAsNum.Equal(other.LocalAsNum) {
		return false
	}

	if !v.MultipathRelax.Equal(other.MultipathRelax) {
		return false
	}

	if !v.RestartMode.Equal(other.RestartMode) {
		return false
	}

	if !v.RestartTime.Equal(other.RestartTime) {
		return false
	}

	if !v.StaleRouteTime.Equal(other.StaleRouteTime) {
		return false
	}

	if !v.Tier0DnsForwarderIp.Equal(other.Tier0DnsForwarderIp) {
		return false
	}

	if !v.Tier0ExternalInterface.Equal(other.Tier0ExternalInterface) {
		return false
	}

	if !v.Tier0IpsecLocalIp.Equal(other.Tier0IpsecLocalIp) {
		return false
	}

	if !v.Tier0LoopbackInterface.Equal(other.Tier0LoopbackInterface) {
		return false
	}

	if !v.Tier0Nat.Equal(other.Tier0Nat) {
		return false
	}

	if !v.Tier0Segment.Equal(other.Tier0Segment) {
		return false
	}

	if !v.Tier0ServiceInterface.Equal(other.Tier0ServiceInterface) {
		return false
	}

	if !v.Tier0Static.Equal(other.Tier0Static) {
		return false
	}

	if !v.Tier1DnsForwarderIp.Equal(other.Tier1DnsForwarderIp) {
		return false
	}

	if !v.Tier1IpsecLocalEndpoint.Equal(other.Tier1IpsecLocalEndpoint) {
		return false
	}

	if !v.Tier1LbSnat.Equal(other.Tier1LbSnat) {
		return false
	}

	if !v.Tier1LbVip.Equal(other.Tier1LbVip) {
		return false
	}

	if !v.Tier1Nat.Equal(other.Tier1Nat) {
		return false
	}

	if !v.Tier1Segment.Equal(other.Tier1Segment) {
		return false
	}

	if !v.Tier1ServiceInterface.Equal(other.Tier1ServiceInterface) {
		return false
	}

	if !v.Tier1Static.Equal(other.Tier1Static) {
		return false
	}

	return true
}

func (v ConfigNsxtGatewayTier0Value) Type(ctx context.Context) attr.Type {
	return ConfigNsxtGatewayTier0Type{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConfigNsxtGatewayTier0Value) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"ecmp":                       basetypes.BoolType{},
		"edge_cluster":               basetypes.StringType{},
		"fail_over":                  basetypes.StringType{},
		"ha_mode":                    basetypes.StringType{},
		"inter_sr_ibgp":              basetypes.BoolType{},
		"ip_management_type":         basetypes.StringType{},
		"ip_server_id":               basetypes.StringType{},
		"local_as_num":               basetypes.StringType{},
		"multipath_relax":            basetypes.BoolType{},
		"restart_mode":               basetypes.StringType{},
		"restart_time":               basetypes.Int64Type{},
		"stale_route_time":           basetypes.Int64Type{},
		"tier0_dns_forwarder_ip":     basetypes.BoolType{},
		"tier0_external_interface":   basetypes.BoolType{},
		"tier0_ipsec_local_ip":       basetypes.BoolType{},
		"tier0_loopback_interface":   basetypes.BoolType{},
		"tier0_nat":                  basetypes.BoolType{},
		"tier0_segment":              basetypes.BoolType{},
		"tier0_service_interface":    basetypes.BoolType{},
		"tier0_static":               basetypes.BoolType{},
		"tier1_dns_forwarder_ip":     basetypes.BoolType{},
		"tier1_ipsec_local_endpoint": basetypes.BoolType{},
		"tier1_lb_snat":              basetypes.BoolType{},
		"tier1_lb_vip":               basetypes.BoolType{},
		"tier1_nat":                  basetypes.BoolType{},
		"tier1_segment":              basetypes.BoolType{},
		"tier1_service_interface":    basetypes.BoolType{},
		"tier1_static":               basetypes.BoolType{},
	}
}

var _ basetypes.ObjectTypable = ConfigNsxtGatewayTier1Type{}

type ConfigNsxtGatewayTier1Type struct {
	basetypes.ObjectType
}

func (t ConfigNsxtGatewayTier1Type) Equal(o attr.Type) bool {
	other, ok := o.(ConfigNsxtGatewayTier1Type)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConfigNsxtGatewayTier1Type) String() string {
	return "ConfigNsxtGatewayTier1Type"
}

func (t ConfigNsxtGatewayTier1Type) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewConfigNsxtGatewayTier1ValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigNsxtGatewayTier1ValueNull(), nil
	}

	attributes := in.Attributes()

	edgeClusterAttribute, ok := attributes["edge_cluster"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`edge_cluster is missing from object`,
		)

		return nil, diags
	}

	edgeClusterVal, ok := edgeClusterAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`edge_cluster expected to be basetypes.StringValue, was: %T`, edgeClusterAttribute),
		)
	}

	failOverAttribute, ok := attributes["fail_over"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fail_over is missing from object`,
		)

		return nil, diags
	}

	failOverVal, ok := failOverAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fail_over expected to be basetypes.StringValue, was: %T`, failOverAttribute),
		)
	}

	ipManagementTypeAttribute, ok := attributes["ip_management_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_management_type is missing from object`,
		)

		return nil, diags
	}

	ipManagementTypeVal, ok := ipManagementTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_management_type expected to be basetypes.StringValue, was: %T`, ipManagementTypeAttribute),
		)
	}

	ipServerIdAttribute, ok := attributes["ip_server_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_server_id is missing from object`,
		)

		return nil, diags
	}

	ipServerIdVal, ok := ipServerIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_server_id expected to be basetypes.StringValue, was: %T`, ipServerIdAttribute),
		)
	}

	tier0GatewayAttribute, ok := attributes["tier0_gateway"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier0_gateway is missing from object`,
		)

		return nil, diags
	}

	tier0GatewayVal, ok := tier0GatewayAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier0_gateway expected to be basetypes.StringValue, was: %T`, tier0GatewayAttribute),
		)
	}

	tier1ConnectedAttribute, ok := attributes["tier1_connected"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_connected is missing from object`,
		)

		return nil, diags
	}

	tier1ConnectedVal, ok := tier1ConnectedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_connected expected to be basetypes.BoolValue, was: %T`, tier1ConnectedAttribute),
		)
	}

	tier1DnsForwarderIpAttribute, ok := attributes["tier1_dns_forwarder_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_dns_forwarder_ip is missing from object`,
		)

		return nil, diags
	}

	tier1DnsForwarderIpVal, ok := tier1DnsForwarderIpAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_dns_forwarder_ip expected to be basetypes.BoolValue, was: %T`, tier1DnsForwarderIpAttribute),
		)
	}

	tier1IpsecLocalEndpointAttribute, ok := attributes["tier1_ipsec_local_endpoint"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_ipsec_local_endpoint is missing from object`,
		)

		return nil, diags
	}

	tier1IpsecLocalEndpointVal, ok := tier1IpsecLocalEndpointAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_ipsec_local_endpoint expected to be basetypes.BoolValue, was: %T`, tier1IpsecLocalEndpointAttribute),
		)
	}

	tier1LbSnatAttribute, ok := attributes["tier1_lb_snat"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_lb_snat is missing from object`,
		)

		return nil, diags
	}

	tier1LbSnatVal, ok := tier1LbSnatAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_lb_snat expected to be basetypes.BoolValue, was: %T`, tier1LbSnatAttribute),
		)
	}

	tier1LbVipAttribute, ok := attributes["tier1_lb_vip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_lb_vip is missing from object`,
		)

		return nil, diags
	}

	tier1LbVipVal, ok := tier1LbVipAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_lb_vip expected to be basetypes.BoolValue, was: %T`, tier1LbVipAttribute),
		)
	}

	tier1NatAttribute, ok := attributes["tier1_nat"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_nat is missing from object`,
		)

		return nil, diags
	}

	tier1NatVal, ok := tier1NatAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_nat expected to be basetypes.BoolValue, was: %T`, tier1NatAttribute),
		)
	}

	tier1StaticRoutesAttribute, ok := attributes["tier1_static_routes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_static_routes is missing from object`,
		)

		return nil, diags
	}

	tier1StaticRoutesVal, ok := tier1StaticRoutesAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_static_routes expected to be basetypes.BoolValue, was: %T`, tier1StaticRoutesAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConfigNsxtGatewayTier1Value{
		EdgeCluster:             edgeClusterVal,
		FailOver:                failOverVal,
		IpManagementType:        ipManagementTypeVal,
		IpServerId:              ipServerIdVal,
		Tier0Gateway:            tier0GatewayVal,
		Tier1Connected:          tier1ConnectedVal,
		Tier1DnsForwarderIp:     tier1DnsForwarderIpVal,
		Tier1IpsecLocalEndpoint: tier1IpsecLocalEndpointVal,
		Tier1LbSnat:             tier1LbSnatVal,
		Tier1LbVip:              tier1LbVipVal,
		Tier1Nat:                tier1NatVal,
		Tier1StaticRoutes:       tier1StaticRoutesVal,
		state:                   attr.ValueStateKnown,
	}, diags
}

func NewConfigNsxtGatewayTier1ValueNull() ConfigNsxtGatewayTier1Value {
	return ConfigNsxtGatewayTier1Value{
		state: attr.ValueStateNull,
	}
}

func NewConfigNsxtGatewayTier1ValueUnknown() ConfigNsxtGatewayTier1Value {
	return ConfigNsxtGatewayTier1Value{
		state: attr.ValueStateUnknown,
	}
}

func NewConfigNsxtGatewayTier1Value(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConfigNsxtGatewayTier1Value, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConfigNsxtGatewayTier1Value Attribute Value",
				"While creating a ConfigNsxtGatewayTier1Value value, a missing attribute value was detected. "+
					"A ConfigNsxtGatewayTier1Value must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigNsxtGatewayTier1Value Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConfigNsxtGatewayTier1Value Attribute Type",
				"While creating a ConfigNsxtGatewayTier1Value value, an invalid attribute value was detected. "+
					"A ConfigNsxtGatewayTier1Value must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigNsxtGatewayTier1Value Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConfigNsxtGatewayTier1Value Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConfigNsxtGatewayTier1Value Attribute Value",
				"While creating a ConfigNsxtGatewayTier1Value value, an extra attribute value was detected. "+
					"A ConfigNsxtGatewayTier1Value must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConfigNsxtGatewayTier1Value Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConfigNsxtGatewayTier1ValueUnknown(), diags
	}

	edgeClusterAttribute, ok := attributes["edge_cluster"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`edge_cluster is missing from object`,
		)

		return NewConfigNsxtGatewayTier1ValueUnknown(), diags
	}

	edgeClusterVal, ok := edgeClusterAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`edge_cluster expected to be basetypes.StringValue, was: %T`, edgeClusterAttribute),
		)
	}

	failOverAttribute, ok := attributes["fail_over"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fail_over is missing from object`,
		)

		return NewConfigNsxtGatewayTier1ValueUnknown(), diags
	}

	failOverVal, ok := failOverAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fail_over expected to be basetypes.StringValue, was: %T`, failOverAttribute),
		)
	}

	ipManagementTypeAttribute, ok := attributes["ip_management_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_management_type is missing from object`,
		)

		return NewConfigNsxtGatewayTier1ValueUnknown(), diags
	}

	ipManagementTypeVal, ok := ipManagementTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_management_type expected to be basetypes.StringValue, was: %T`, ipManagementTypeAttribute),
		)
	}

	ipServerIdAttribute, ok := attributes["ip_server_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_server_id is missing from object`,
		)

		return NewConfigNsxtGatewayTier1ValueUnknown(), diags
	}

	ipServerIdVal, ok := ipServerIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_server_id expected to be basetypes.StringValue, was: %T`, ipServerIdAttribute),
		)
	}

	tier0GatewayAttribute, ok := attributes["tier0_gateway"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier0_gateway is missing from object`,
		)

		return NewConfigNsxtGatewayTier1ValueUnknown(), diags
	}

	tier0GatewayVal, ok := tier0GatewayAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier0_gateway expected to be basetypes.StringValue, was: %T`, tier0GatewayAttribute),
		)
	}

	tier1ConnectedAttribute, ok := attributes["tier1_connected"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_connected is missing from object`,
		)

		return NewConfigNsxtGatewayTier1ValueUnknown(), diags
	}

	tier1ConnectedVal, ok := tier1ConnectedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_connected expected to be basetypes.BoolValue, was: %T`, tier1ConnectedAttribute),
		)
	}

	tier1DnsForwarderIpAttribute, ok := attributes["tier1_dns_forwarder_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_dns_forwarder_ip is missing from object`,
		)

		return NewConfigNsxtGatewayTier1ValueUnknown(), diags
	}

	tier1DnsForwarderIpVal, ok := tier1DnsForwarderIpAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_dns_forwarder_ip expected to be basetypes.BoolValue, was: %T`, tier1DnsForwarderIpAttribute),
		)
	}

	tier1IpsecLocalEndpointAttribute, ok := attributes["tier1_ipsec_local_endpoint"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_ipsec_local_endpoint is missing from object`,
		)

		return NewConfigNsxtGatewayTier1ValueUnknown(), diags
	}

	tier1IpsecLocalEndpointVal, ok := tier1IpsecLocalEndpointAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_ipsec_local_endpoint expected to be basetypes.BoolValue, was: %T`, tier1IpsecLocalEndpointAttribute),
		)
	}

	tier1LbSnatAttribute, ok := attributes["tier1_lb_snat"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_lb_snat is missing from object`,
		)

		return NewConfigNsxtGatewayTier1ValueUnknown(), diags
	}

	tier1LbSnatVal, ok := tier1LbSnatAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_lb_snat expected to be basetypes.BoolValue, was: %T`, tier1LbSnatAttribute),
		)
	}

	tier1LbVipAttribute, ok := attributes["tier1_lb_vip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_lb_vip is missing from object`,
		)

		return NewConfigNsxtGatewayTier1ValueUnknown(), diags
	}

	tier1LbVipVal, ok := tier1LbVipAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_lb_vip expected to be basetypes.BoolValue, was: %T`, tier1LbVipAttribute),
		)
	}

	tier1NatAttribute, ok := attributes["tier1_nat"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_nat is missing from object`,
		)

		return NewConfigNsxtGatewayTier1ValueUnknown(), diags
	}

	tier1NatVal, ok := tier1NatAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_nat expected to be basetypes.BoolValue, was: %T`, tier1NatAttribute),
		)
	}

	tier1StaticRoutesAttribute, ok := attributes["tier1_static_routes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_static_routes is missing from object`,
		)

		return NewConfigNsxtGatewayTier1ValueUnknown(), diags
	}

	tier1StaticRoutesVal, ok := tier1StaticRoutesAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_static_routes expected to be basetypes.BoolValue, was: %T`, tier1StaticRoutesAttribute),
		)
	}

	if diags.HasError() {
		return NewConfigNsxtGatewayTier1ValueUnknown(), diags
	}

	return ConfigNsxtGatewayTier1Value{
		EdgeCluster:             edgeClusterVal,
		FailOver:                failOverVal,
		IpManagementType:        ipManagementTypeVal,
		IpServerId:              ipServerIdVal,
		Tier0Gateway:            tier0GatewayVal,
		Tier1Connected:          tier1ConnectedVal,
		Tier1DnsForwarderIp:     tier1DnsForwarderIpVal,
		Tier1IpsecLocalEndpoint: tier1IpsecLocalEndpointVal,
		Tier1LbSnat:             tier1LbSnatVal,
		Tier1LbVip:              tier1LbVipVal,
		Tier1Nat:                tier1NatVal,
		Tier1StaticRoutes:       tier1StaticRoutesVal,
		state:                   attr.ValueStateKnown,
	}, diags
}

func NewConfigNsxtGatewayTier1ValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConfigNsxtGatewayTier1Value {
	object, diags := NewConfigNsxtGatewayTier1Value(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewConfigNsxtGatewayTier1ValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConfigNsxtGatewayTier1Type) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConfigNsxtGatewayTier1ValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConfigNsxtGatewayTier1ValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigNsxtGatewayTier1ValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConfigNsxtGatewayTier1ValueMust(ConfigNsxtGatewayTier1Value{}.AttributeTypes(ctx), attributes), nil
}

func (t ConfigNsxtGatewayTier1Type) ValueType(ctx context.Context) attr.Value {
	return ConfigNsxtGatewayTier1Value{}
}

var _ basetypes.ObjectValuable = ConfigNsxtGatewayTier1Value{}

type ConfigNsxtGatewayTier1Value struct {
	EdgeCluster             basetypes.StringValue `tfsdk:"edge_cluster"`
	FailOver                basetypes.StringValue `tfsdk:"fail_over"`
	IpManagementType        basetypes.StringValue `tfsdk:"ip_management_type"`
	IpServerId              basetypes.StringValue `tfsdk:"ip_server_id"`
	Tier0Gateway            basetypes.StringValue `tfsdk:"tier0_gateway"`
	Tier1Connected          basetypes.BoolValue   `tfsdk:"tier1_connected"`
	Tier1DnsForwarderIp     basetypes.BoolValue   `tfsdk:"tier1_dns_forwarder_ip"`
	Tier1IpsecLocalEndpoint basetypes.BoolValue   `tfsdk:"tier1_ipsec_local_endpoint"`
	Tier1LbSnat             basetypes.BoolValue   `tfsdk:"tier1_lb_snat"`
	Tier1LbVip              basetypes.BoolValue   `tfsdk:"tier1_lb_vip"`
	Tier1Nat                basetypes.BoolValue   `tfsdk:"tier1_nat"`
	Tier1StaticRoutes       basetypes.BoolValue   `tfsdk:"tier1_static_routes"`
	state                   attr.ValueState
}

func (v ConfigNsxtGatewayTier1Value) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 12)

	var val tftypes.Value
	var err error

	attrTypes["edge_cluster"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["fail_over"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["ip_management_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["ip_server_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["tier0_gateway"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["tier1_connected"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier1_dns_forwarder_ip"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier1_ipsec_local_endpoint"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier1_lb_snat"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier1_lb_vip"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier1_nat"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tier1_static_routes"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 12)

		val, err = v.EdgeCluster.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["edge_cluster"] = val

		val, err = v.FailOver.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["fail_over"] = val

		val, err = v.IpManagementType.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip_management_type"] = val

		val, err = v.IpServerId.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip_server_id"] = val

		val, err = v.Tier0Gateway.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier0_gateway"] = val

		val, err = v.Tier1Connected.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier1_connected"] = val

		val, err = v.Tier1DnsForwarderIp.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier1_dns_forwarder_ip"] = val

		val, err = v.Tier1IpsecLocalEndpoint.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier1_ipsec_local_endpoint"] = val

		val, err = v.Tier1LbSnat.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier1_lb_snat"] = val

		val, err = v.Tier1LbVip.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier1_lb_vip"] = val

		val, err = v.Tier1Nat.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier1_nat"] = val

		val, err = v.Tier1StaticRoutes.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier1_static_routes"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConfigNsxtGatewayTier1Value) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConfigNsxtGatewayTier1Value) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConfigNsxtGatewayTier1Value) String() string {
	return "ConfigNsxtGatewayTier1Value"
}

func (v ConfigNsxtGatewayTier1Value) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"edge_cluster":               basetypes.StringType{},
		"fail_over":                  basetypes.StringType{},
		"ip_management_type":         basetypes.StringType{},
		"ip_server_id":               basetypes.StringType{},
		"tier0_gateway":              basetypes.StringType{},
		"tier1_connected":            basetypes.BoolType{},
		"tier1_dns_forwarder_ip":     basetypes.BoolType{},
		"tier1_ipsec_local_endpoint": basetypes.BoolType{},
		"tier1_lb_snat":              basetypes.BoolType{},
		"tier1_lb_vip":               basetypes.BoolType{},
		"tier1_nat":                  basetypes.BoolType{},
		"tier1_static_routes":        basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"edge_cluster":               v.EdgeCluster,
			"fail_over":                  v.FailOver,
			"ip_management_type":         v.IpManagementType,
			"ip_server_id":               v.IpServerId,
			"tier0_gateway":              v.Tier0Gateway,
			"tier1_connected":            v.Tier1Connected,
			"tier1_dns_forwarder_ip":     v.Tier1DnsForwarderIp,
			"tier1_ipsec_local_endpoint": v.Tier1IpsecLocalEndpoint,
			"tier1_lb_snat":              v.Tier1LbSnat,
			"tier1_lb_vip":               v.Tier1LbVip,
			"tier1_nat":                  v.Tier1Nat,
			"tier1_static_routes":        v.Tier1StaticRoutes,
		},
	)

	return objVal, diags
}

func (v ConfigNsxtGatewayTier1Value) Equal(o attr.Value) bool {
	other, ok := o.(ConfigNsxtGatewayTier1Value)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.EdgeCluster.Equal(other.EdgeCluster) {
		return false
	}

	if !v.FailOver.Equal(other.FailOver) {
		return false
	}

	if !v.IpManagementType.Equal(other.IpManagementType) {
		return false
	}

	if !v.IpServerId.Equal(other.IpServerId) {
		return false
	}

	if !v.Tier0Gateway.Equal(other.Tier0Gateway) {
		return false
	}

	if !v.Tier1Connected.Equal(other.Tier1Connected) {
		return false
	}

	if !v.Tier1DnsForwarderIp.Equal(other.Tier1DnsForwarderIp) {
		return false
	}

	if !v.Tier1IpsecLocalEndpoint.Equal(other.Tier1IpsecLocalEndpoint) {
		return false
	}

	if !v.Tier1LbSnat.Equal(other.Tier1LbSnat) {
		return false
	}

	if !v.Tier1LbVip.Equal(other.Tier1LbVip) {
		return false
	}

	if !v.Tier1Nat.Equal(other.Tier1Nat) {
		return false
	}

	if !v.Tier1StaticRoutes.Equal(other.Tier1StaticRoutes) {
		return false
	}

	return true
}

func (v ConfigNsxtGatewayTier1Value) Type(ctx context.Context) attr.Type {
	return ConfigNsxtGatewayTier1Type{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConfigNsxtGatewayTier1Value) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"edge_cluster":               basetypes.StringType{},
		"fail_over":                  basetypes.StringType{},
		"ip_management_type":         basetypes.StringType{},
		"ip_server_id":               basetypes.StringType{},
		"tier0_gateway":              basetypes.StringType{},
		"tier1_connected":            basetypes.BoolType{},
		"tier1_dns_forwarder_ip":     basetypes.BoolType{},
		"tier1_ipsec_local_endpoint": basetypes.BoolType{},
		"tier1_lb_snat":              basetypes.BoolType{},
		"tier1_lb_vip":               basetypes.BoolType{},
		"tier1_nat":                  basetypes.BoolType{},
		"tier1_static_routes":        basetypes.BoolType{},
	}
}
