// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package networkdhcpserver

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-validators/dynamicvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func NetworkDhcpServerResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"config": schema.DynamicAttribute{
				Optional:            true,
				Description:         "Generic DHCP Server Configuration",
				MarkdownDescription: "Generic DHCP Server Configuration",
				Validators: []validator.Dynamic{
					dynamicvalidator.ConflictsWith(path.Expressions{path.MatchRoot("config_nsxt")}...),
				},
			},
			"config_nsxt": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"active_edge_node": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Active Edge Node",
						MarkdownDescription: "Active Edge Node",
					},
					"edge_cluster": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Edge Cluster",
						MarkdownDescription: "Edge Cluster",
					},
					"standby_edge_node": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Standby Edge Node",
						MarkdownDescription: "Standby Edge Node",
					},
				},
				CustomType: ConfigNsxtType{
					ObjectType: types.ObjectType{
						AttrTypes: ConfigNsxtValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Description:         "Configuration object with parameters that vary by type",
				MarkdownDescription: "Configuration object with parameters that vary by type",
			},
			"id": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"lease_time": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Lease time in seconds for the DHCP server",
				MarkdownDescription: "Lease time in seconds for the DHCP server",
				Default:             int64default.StaticInt64(86400),
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name",
				MarkdownDescription: "Name",
			},
			"network_integration_id": schema.Int64Attribute{
				Required:            true,
				Description:         "The ID of the network integration this DHCP server belongs to",
				MarkdownDescription: "The ID of the network integration this DHCP server belongs to",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"server_ip_address": schema.StringAttribute{
				Required:            true,
				Description:         "Server address for the DHCP server",
				MarkdownDescription: "Server address for the DHCP server",
			},
		},
	}
}

type NetworkDhcpServerModel struct {
	Config               types.Dynamic   `tfsdk:"config"`
	ConfigNsxt           ConfigNsxtValue `tfsdk:"config_nsxt"`
	Id                   types.Int64     `tfsdk:"id"`
	LeaseTime            types.Int64     `tfsdk:"lease_time"`
	Name                 types.String    `tfsdk:"name"`
	NetworkIntegrationId types.Int64     `tfsdk:"network_integration_id"`
	ServerIpAddress      types.String    `tfsdk:"server_ip_address"`
}

var _ basetypes.ObjectTypable = ConfigNsxtType{}

type ConfigNsxtType struct {
	basetypes.ObjectType
}

func (t ConfigNsxtType) Equal(o attr.Type) bool {
	other, ok := o.(ConfigNsxtType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConfigNsxtType) String() string {
	return "ConfigNsxtType"
}

func (t ConfigNsxtType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewConfigNsxtValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigNsxtValueNull(), nil
	}

	attributes := in.Attributes()

	activeEdgeNodeAttribute, ok := attributes["active_edge_node"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`active_edge_node is missing from object`,
		)

		return nil, diags
	}

	activeEdgeNodeVal, ok := activeEdgeNodeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`active_edge_node expected to be basetypes.StringValue, was: %T`, activeEdgeNodeAttribute),
		)
	}

	edgeClusterAttribute, ok := attributes["edge_cluster"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`edge_cluster is missing from object`,
		)

		return nil, diags
	}

	edgeClusterVal, ok := edgeClusterAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`edge_cluster expected to be basetypes.StringValue, was: %T`, edgeClusterAttribute),
		)
	}

	standbyEdgeNodeAttribute, ok := attributes["standby_edge_node"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`standby_edge_node is missing from object`,
		)

		return nil, diags
	}

	standbyEdgeNodeVal, ok := standbyEdgeNodeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`standby_edge_node expected to be basetypes.StringValue, was: %T`, standbyEdgeNodeAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConfigNsxtValue{
		ActiveEdgeNode:  activeEdgeNodeVal,
		EdgeCluster:     edgeClusterVal,
		StandbyEdgeNode: standbyEdgeNodeVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewConfigNsxtValueNull() ConfigNsxtValue {
	return ConfigNsxtValue{
		state: attr.ValueStateNull,
	}
}

func NewConfigNsxtValueUnknown() ConfigNsxtValue {
	return ConfigNsxtValue{
		state: attr.ValueStateUnknown,
	}
}

func NewConfigNsxtValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConfigNsxtValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConfigNsxtValue Attribute Value",
				"While creating a ConfigNsxtValue value, a missing attribute value was detected. "+
					"A ConfigNsxtValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigNsxtValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConfigNsxtValue Attribute Type",
				"While creating a ConfigNsxtValue value, an invalid attribute value was detected. "+
					"A ConfigNsxtValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigNsxtValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConfigNsxtValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConfigNsxtValue Attribute Value",
				"While creating a ConfigNsxtValue value, an extra attribute value was detected. "+
					"A ConfigNsxtValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConfigNsxtValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConfigNsxtValueUnknown(), diags
	}

	activeEdgeNodeAttribute, ok := attributes["active_edge_node"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`active_edge_node is missing from object`,
		)

		return NewConfigNsxtValueUnknown(), diags
	}

	activeEdgeNodeVal, ok := activeEdgeNodeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`active_edge_node expected to be basetypes.StringValue, was: %T`, activeEdgeNodeAttribute),
		)
	}

	edgeClusterAttribute, ok := attributes["edge_cluster"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`edge_cluster is missing from object`,
		)

		return NewConfigNsxtValueUnknown(), diags
	}

	edgeClusterVal, ok := edgeClusterAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`edge_cluster expected to be basetypes.StringValue, was: %T`, edgeClusterAttribute),
		)
	}

	standbyEdgeNodeAttribute, ok := attributes["standby_edge_node"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`standby_edge_node is missing from object`,
		)

		return NewConfigNsxtValueUnknown(), diags
	}

	standbyEdgeNodeVal, ok := standbyEdgeNodeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`standby_edge_node expected to be basetypes.StringValue, was: %T`, standbyEdgeNodeAttribute),
		)
	}

	if diags.HasError() {
		return NewConfigNsxtValueUnknown(), diags
	}

	return ConfigNsxtValue{
		ActiveEdgeNode:  activeEdgeNodeVal,
		EdgeCluster:     edgeClusterVal,
		StandbyEdgeNode: standbyEdgeNodeVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewConfigNsxtValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConfigNsxtValue {
	object, diags := NewConfigNsxtValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewConfigNsxtValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConfigNsxtType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConfigNsxtValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConfigNsxtValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigNsxtValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConfigNsxtValueMust(ConfigNsxtValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ConfigNsxtType) ValueType(ctx context.Context) attr.Value {
	return ConfigNsxtValue{}
}

var _ basetypes.ObjectValuable = ConfigNsxtValue{}

type ConfigNsxtValue struct {
	ActiveEdgeNode  basetypes.StringValue `tfsdk:"active_edge_node"`
	EdgeCluster     basetypes.StringValue `tfsdk:"edge_cluster"`
	StandbyEdgeNode basetypes.StringValue `tfsdk:"standby_edge_node"`
	state           attr.ValueState
}

func (v ConfigNsxtValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["active_edge_node"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["edge_cluster"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["standby_edge_node"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.ActiveEdgeNode.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["active_edge_node"] = val

		val, err = v.EdgeCluster.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["edge_cluster"] = val

		val, err = v.StandbyEdgeNode.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["standby_edge_node"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConfigNsxtValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConfigNsxtValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConfigNsxtValue) String() string {
	return "ConfigNsxtValue"
}

func (v ConfigNsxtValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"active_edge_node":  basetypes.StringType{},
		"edge_cluster":      basetypes.StringType{},
		"standby_edge_node": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"active_edge_node":  v.ActiveEdgeNode,
			"edge_cluster":      v.EdgeCluster,
			"standby_edge_node": v.StandbyEdgeNode,
		},
	)

	return objVal, diags
}

func (v ConfigNsxtValue) Equal(o attr.Value) bool {
	other, ok := o.(ConfigNsxtValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ActiveEdgeNode.Equal(other.ActiveEdgeNode) {
		return false
	}

	if !v.EdgeCluster.Equal(other.EdgeCluster) {
		return false
	}

	if !v.StandbyEdgeNode.Equal(other.StandbyEdgeNode) {
		return false
	}

	return true
}

func (v ConfigNsxtValue) Type(ctx context.Context) attr.Type {
	return ConfigNsxtType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConfigNsxtValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"active_edge_node":  basetypes.StringType{},
		"edge_cluster":      basetypes.StringType{},
		"standby_edge_node": basetypes.StringType{},
	}
}
