// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package image

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/HPE/terraform-provider-hpe/utils/modifiers"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ImageResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"auto_join_domain": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Auto Join Domain?",
				MarkdownDescription: "Auto Join Domain?",
				Default:             booldefault.StaticBool(false),
			},
			"cloud_init": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Cloud Init Enabled?",
				MarkdownDescription: "Cloud Init Enabled?",
				Default:             booldefault.StaticBool(false),
			},
			"config_azure": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"offer": schema.StringAttribute{
						Required:            true,
						Description:         "The name of the offer in the Azure Marketplace",
						MarkdownDescription: "The name of the offer in the Azure Marketplace",
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					"publisher": schema.StringAttribute{
						Required:            true,
						Description:         "The name of the publisher in the Azure Marketplace",
						MarkdownDescription: "The name of the publisher in the Azure Marketplace",
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					"sku": schema.StringAttribute{
						Required:            true,
						Description:         "The name of the sku in the Azure Marketplace",
						MarkdownDescription: "The name of the sku in the Azure Marketplace",
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					"version": schema.StringAttribute{
						Required:            true,
						Description:         "The name of the version in the Azure Marketplace",
						MarkdownDescription: "The name of the version in the Azure Marketplace",
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
				},
				CustomType: ConfigAzureType{
					ObjectType: types.ObjectType{
						AttrTypes: ConfigAzureValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Azure Reference Virtual Image Parameters",
				MarkdownDescription: "Azure Reference Virtual Image Parameters",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A description for the virtual image",
				MarkdownDescription: "A description for the virtual image",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"external_id": schema.StringAttribute{
				Computed: true,
			},
			"fips_enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "FIPS enabled?",
				MarkdownDescription: "FIPS enabled?",
			},
			"force_customization": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Force Guest Customization?",
				MarkdownDescription: "Force Guest Customization?",
				Default:             booldefault.StaticBool(false),
			},
			"id": schema.Int64Attribute{
				Computed: true,
			},
			"image_type": schema.StringAttribute{
				Required:            true,
				Description:         "Code of image type. eg. vmware, ami, etc.",
				MarkdownDescription: "Code of image type. eg. vmware, ami, etc.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"install_agent": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Install Agent?",
				MarkdownDescription: "Install Agent?",
				Default:             booldefault.StaticBool(false),
			},
			"labels": schema.SetAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Array of label strings, can be used for filtering.",
				MarkdownDescription: "Array of label strings, can be used for filtering.",
			},
			"min_disk": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Minimal required amount of disk space for provisioning in GB",
				MarkdownDescription: "Minimal required amount of disk space for provisioning in GB",
			},
			"min_ram": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Minimal required amount of RAM for provisioning in GB",
				MarkdownDescription: "Minimal required amount of RAM for provisioning in GB",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "A name for the virtual image",
				MarkdownDescription: "A name for the virtual image",
			},
			"os_type_id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "ID of the OS Type",
				MarkdownDescription: "ID of the OS Type",
			},
			"owner_id": schema.Int64Attribute{
				Computed:            true,
				Description:         "ID of the user which created this image",
				MarkdownDescription: "ID of the user which created this image",
			},
			"raw_size": schema.Int64Attribute{
				Computed:            true,
				Description:         "Size of image in bytes",
				MarkdownDescription: "Size of image in bytes",
			},
			"ssh_password_wo": schema.StringAttribute{
				Optional:            true,
				WriteOnly:           true,
				Description:         "SSH password (Write Only)",
				MarkdownDescription: "SSH password (Write Only)",
				PlanModifiers: []planmodifier.String{
					modifiers.NullableStringUpdateModifier{},
				},
			},
			"ssh_password_wo_version": schema.Int64Attribute{
				Optional:            true,
				Description:         "SSH password version. Used to determine if ssh_password_wo has been updated.",
				MarkdownDescription: "SSH password version. Used to determine if ssh_password_wo has been updated.",
			},
			"ssh_username": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "SSH Username",
				MarkdownDescription: "SSH Username",
			},
			"storage_provider_id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "ID of the storage provider where the image will be uploaded",
				MarkdownDescription: "ID of the storage provider where the image will be uploaded",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"sysprep": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Sysprep Enabled?",
				MarkdownDescription: "Sysprep Enabled?",
				Default:             booldefault.StaticBool(false),
			},
			"system_image": schema.BoolAttribute{
				Computed: true,
			},
			"tags": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							Required: true,
						},
						"value": schema.StringAttribute{
							Required: true,
						},
					},
					CustomType: TagsType{
						ObjectType: types.ObjectType{
							AttrTypes: TagsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Metadata tags, Array of objects having a name and value",
				MarkdownDescription: "Metadata tags, Array of objects having a name and value",
			},
			"tenant_ids": schema.SetAttribute{
				ElementType:         types.Int64Type,
				Optional:            true,
				Computed:            true,
				Description:         "List of tenant IDs",
				MarkdownDescription: "List of tenant IDs",
			},
			"trial_version": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Trial Version",
				MarkdownDescription: "Trial Version",
				Default:             booldefault.StaticBool(false),
			},
			"uefi": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "UEFI enabled?",
				MarkdownDescription: "UEFI enabled?",
			},
			"url": schema.StringAttribute{
				Optional:            true,
				Description:         "Image File URL, a virtual image file will be created by fetching the specified URL",
				MarkdownDescription: "Image File URL, a virtual image file will be created by fetching the specified URL",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"user_data": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Cloud-Init User Data, a bash script",
				MarkdownDescription: "Cloud-Init User Data, a bash script",
			},
			"virtio_supported": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "VirtIO Drivers Loaded?",
				MarkdownDescription: "VirtIO Drivers Loaded?",
				Default:             booldefault.StaticBool(true),
			},
			"visibility": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "private or public",
				MarkdownDescription: "private or public",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"private",
						"public",
					),
				},
				Default: stringdefault.StaticString("private"),
			},
			"vm_tools_installed": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "VM Tools Installed?",
				MarkdownDescription: "VM Tools Installed?",
				Default:             booldefault.StaticBool(true),
			},
		},
	}
}

type ImageModel struct {
	AutoJoinDomain       types.Bool       `tfsdk:"auto_join_domain"`
	CloudInit            types.Bool       `tfsdk:"cloud_init"`
	ConfigAzure          ConfigAzureValue `tfsdk:"config_azure"`
	Description          types.String     `tfsdk:"description"`
	ExternalId           types.String     `tfsdk:"external_id"`
	FipsEnabled          types.Bool       `tfsdk:"fips_enabled"`
	ForceCustomization   types.Bool       `tfsdk:"force_customization"`
	Id                   types.Int64      `tfsdk:"id"`
	ImageType            types.String     `tfsdk:"image_type"`
	InstallAgent         types.Bool       `tfsdk:"install_agent"`
	Labels               types.Set        `tfsdk:"labels"`
	MinDisk              types.Int64      `tfsdk:"min_disk"`
	MinRam               types.Int64      `tfsdk:"min_ram"`
	Name                 types.String     `tfsdk:"name"`
	OsTypeId             types.Int64      `tfsdk:"os_type_id"`
	OwnerId              types.Int64      `tfsdk:"owner_id"`
	RawSize              types.Int64      `tfsdk:"raw_size"`
	SshPasswordWo        types.String     `tfsdk:"ssh_password_wo"`
	SshPasswordWoVersion types.Int64      `tfsdk:"ssh_password_wo_version"`
	SshUsername          types.String     `tfsdk:"ssh_username"`
	StorageProviderId    types.Int64      `tfsdk:"storage_provider_id"`
	Sysprep              types.Bool       `tfsdk:"sysprep"`
	SystemImage          types.Bool       `tfsdk:"system_image"`
	Tags                 types.Set        `tfsdk:"tags"`
	TenantIds            types.Set        `tfsdk:"tenant_ids"`
	TrialVersion         types.Bool       `tfsdk:"trial_version"`
	Uefi                 types.Bool       `tfsdk:"uefi"`
	Url                  types.String     `tfsdk:"url"`
	UserData             types.String     `tfsdk:"user_data"`
	VirtioSupported      types.Bool       `tfsdk:"virtio_supported"`
	Visibility           types.String     `tfsdk:"visibility"`
	VmToolsInstalled     types.Bool       `tfsdk:"vm_tools_installed"`
}

var _ basetypes.ObjectTypable = ConfigAzureType{}

type ConfigAzureType struct {
	basetypes.ObjectType
}

func (t ConfigAzureType) Equal(o attr.Type) bool {
	other, ok := o.(ConfigAzureType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConfigAzureType) String() string {
	return "ConfigAzureType"
}

func (t ConfigAzureType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewConfigAzureValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigAzureValueNull(), nil
	}

	attributes := in.Attributes()

	offerAttribute, ok := attributes["offer"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`offer is missing from object`,
		)

		return nil, diags
	}

	offerVal, ok := offerAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`offer expected to be basetypes.StringValue, was: %T`, offerAttribute),
		)
	}

	publisherAttribute, ok := attributes["publisher"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`publisher is missing from object`,
		)

		return nil, diags
	}

	publisherVal, ok := publisherAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`publisher expected to be basetypes.StringValue, was: %T`, publisherAttribute),
		)
	}

	skuAttribute, ok := attributes["sku"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`sku is missing from object`,
		)

		return nil, diags
	}

	skuVal, ok := skuAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`sku expected to be basetypes.StringValue, was: %T`, skuAttribute),
		)
	}

	versionAttribute, ok := attributes["version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`version is missing from object`,
		)

		return nil, diags
	}

	versionVal, ok := versionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`version expected to be basetypes.StringValue, was: %T`, versionAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConfigAzureValue{
		Offer:     offerVal,
		Publisher: publisherVal,
		Sku:       skuVal,
		Version:   versionVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewConfigAzureValueNull() ConfigAzureValue {
	return ConfigAzureValue{
		state: attr.ValueStateNull,
	}
}

func NewConfigAzureValueUnknown() ConfigAzureValue {
	return ConfigAzureValue{
		state: attr.ValueStateUnknown,
	}
}

func NewConfigAzureValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConfigAzureValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConfigAzureValue Attribute Value",
				"While creating a ConfigAzureValue value, a missing attribute value was detected. "+
					"A ConfigAzureValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigAzureValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConfigAzureValue Attribute Type",
				"While creating a ConfigAzureValue value, an invalid attribute value was detected. "+
					"A ConfigAzureValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigAzureValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConfigAzureValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConfigAzureValue Attribute Value",
				"While creating a ConfigAzureValue value, an extra attribute value was detected. "+
					"A ConfigAzureValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConfigAzureValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConfigAzureValueUnknown(), diags
	}

	offerAttribute, ok := attributes["offer"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`offer is missing from object`,
		)

		return NewConfigAzureValueUnknown(), diags
	}

	offerVal, ok := offerAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`offer expected to be basetypes.StringValue, was: %T`, offerAttribute),
		)
	}

	publisherAttribute, ok := attributes["publisher"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`publisher is missing from object`,
		)

		return NewConfigAzureValueUnknown(), diags
	}

	publisherVal, ok := publisherAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`publisher expected to be basetypes.StringValue, was: %T`, publisherAttribute),
		)
	}

	skuAttribute, ok := attributes["sku"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`sku is missing from object`,
		)

		return NewConfigAzureValueUnknown(), diags
	}

	skuVal, ok := skuAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`sku expected to be basetypes.StringValue, was: %T`, skuAttribute),
		)
	}

	versionAttribute, ok := attributes["version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`version is missing from object`,
		)

		return NewConfigAzureValueUnknown(), diags
	}

	versionVal, ok := versionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`version expected to be basetypes.StringValue, was: %T`, versionAttribute),
		)
	}

	if diags.HasError() {
		return NewConfigAzureValueUnknown(), diags
	}

	return ConfigAzureValue{
		Offer:     offerVal,
		Publisher: publisherVal,
		Sku:       skuVal,
		Version:   versionVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewConfigAzureValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConfigAzureValue {
	object, diags := NewConfigAzureValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewConfigAzureValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConfigAzureType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConfigAzureValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConfigAzureValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigAzureValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConfigAzureValueMust(ConfigAzureValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ConfigAzureType) ValueType(ctx context.Context) attr.Value {
	return ConfigAzureValue{}
}

var _ basetypes.ObjectValuable = ConfigAzureValue{}

type ConfigAzureValue struct {
	Offer     basetypes.StringValue `tfsdk:"offer"`
	Publisher basetypes.StringValue `tfsdk:"publisher"`
	Sku       basetypes.StringValue `tfsdk:"sku"`
	Version   basetypes.StringValue `tfsdk:"version"`
	state     attr.ValueState
}

func (v ConfigAzureValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["offer"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["publisher"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["sku"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["version"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.Offer.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["offer"] = val

		val, err = v.Publisher.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["publisher"] = val

		val, err = v.Sku.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["sku"] = val

		val, err = v.Version.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["version"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConfigAzureValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConfigAzureValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConfigAzureValue) String() string {
	return "ConfigAzureValue"
}

func (v ConfigAzureValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"offer":     basetypes.StringType{},
		"publisher": basetypes.StringType{},
		"sku":       basetypes.StringType{},
		"version":   basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"offer":     v.Offer,
			"publisher": v.Publisher,
			"sku":       v.Sku,
			"version":   v.Version,
		},
	)

	return objVal, diags
}

func (v ConfigAzureValue) Equal(o attr.Value) bool {
	other, ok := o.(ConfigAzureValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Offer.Equal(other.Offer) {
		return false
	}

	if !v.Publisher.Equal(other.Publisher) {
		return false
	}

	if !v.Sku.Equal(other.Sku) {
		return false
	}

	if !v.Version.Equal(other.Version) {
		return false
	}

	return true
}

func (v ConfigAzureValue) Type(ctx context.Context) attr.Type {
	return ConfigAzureType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConfigAzureValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"offer":     basetypes.StringType{},
		"publisher": basetypes.StringType{},
		"sku":       basetypes.StringType{},
		"version":   basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = TagsType{}

type TagsType struct {
	basetypes.ObjectType
}

func (t TagsType) Equal(o attr.Type) bool {
	other, ok := o.(TagsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TagsType) String() string {
	return "TagsType"
}

func (t TagsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewTagsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTagsValueNull(), nil
	}

	attributes := in.Attributes()

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`,
		)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute),
		)
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`,
		)

		return nil, diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return TagsValue{
		Name:  nameVal,
		Value: valueVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTagsValueNull() TagsValue {
	return TagsValue{
		state: attr.ValueStateNull,
	}
}

func NewTagsValueUnknown() TagsValue {
	return TagsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTagsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TagsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TagsValue Attribute Value",
				"While creating a TagsValue value, a missing attribute value was detected. "+
					"A TagsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TagsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TagsValue Attribute Type",
				"While creating a TagsValue value, an invalid attribute value was detected. "+
					"A TagsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TagsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TagsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TagsValue Attribute Value",
				"While creating a TagsValue value, an extra attribute value was detected. "+
					"A TagsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TagsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTagsValueUnknown(), diags
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`,
		)

		return NewTagsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute),
		)
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`,
		)

		return NewTagsValueUnknown(), diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute),
		)
	}

	if diags.HasError() {
		return NewTagsValueUnknown(), diags
	}

	return TagsValue{
		Name:  nameVal,
		Value: valueVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTagsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TagsValue {
	object, diags := NewTagsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewTagsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TagsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTagsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTagsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTagsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTagsValueMust(TagsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TagsType) ValueType(ctx context.Context) attr.Value {
	return TagsValue{}
}

var _ basetypes.ObjectValuable = TagsValue{}

type TagsValue struct {
	Name  basetypes.StringValue `tfsdk:"name"`
	Value basetypes.StringValue `tfsdk:"value"`
	state attr.ValueState
}

func (v TagsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["value"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Name.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Value.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["value"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TagsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TagsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TagsValue) String() string {
	return "TagsValue"
}

func (v TagsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"name":  basetypes.StringType{},
		"value": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"name":  v.Name,
			"value": v.Value,
		},
	)

	return objVal, diags
}

func (v TagsValue) Equal(o attr.Value) bool {
	other, ok := o.(TagsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Value.Equal(other.Value) {
		return false
	}

	return true
}

func (v TagsValue) Type(ctx context.Context) attr.Type {
	return TagsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TagsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"name":  basetypes.StringType{},
		"value": basetypes.StringType{},
	}
}
