// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package networkfirewallrule

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func NetworkFirewallRuleResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"application": schema.SetAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Application identifiers for the firewall rule.",
				MarkdownDescription: "Application identifiers for the firewall rule.",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The description of the network firewall rule.",
				MarkdownDescription: "The description of the network firewall rule.",
			},
			"destinations": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.SetAttribute{
						ElementType: types.StringType,
						Optional:    true,
						Computed:    true,
					},
				},
				CustomType: DestinationsType{
					ObjectType: types.ObjectType{
						AttrTypes: DestinationsValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Destination addresses or groups for the firewall rule.",
				MarkdownDescription: "Destination addresses or groups for the firewall rule.",
			},
			"direction": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The traffic direction for the firewall rule (e.g. ingress, egress).",
				MarkdownDescription: "The traffic direction for the firewall rule (e.g. ingress, egress).",
			},
			"enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether the firewall rule is enabled.",
				MarkdownDescription: "Whether the firewall rule is enabled.",
			},
			"id": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the network firewall rule.",
				MarkdownDescription: "The name of the network firewall rule.",
			},
			"network_integration_id": schema.Int64Attribute{
				Required:            true,
				Description:         "The ID of the network integration",
				MarkdownDescription: "The ID of the network integration",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"policy": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The policy action for the firewall rule (e.g. accept, deny, drop).",
				MarkdownDescription: "The policy action for the firewall rule (e.g. accept, deny, drop).",
			},
			"priority": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The priority of the network firewall rule.",
				MarkdownDescription: "The priority of the network firewall rule.",
			},
			"profile": schema.SetAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Profile identifiers for the firewall rule.",
				MarkdownDescription: "Profile identifiers for the firewall rule.",
			},
			"rule_group_id": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.Int64Attribute{
						Optional:            true,
						Computed:            true,
						Description:         "Firewall rule group for rule (*applicable to select network servers).",
						MarkdownDescription: "Firewall rule group for rule (*applicable to select network servers).",
					},
					"name": schema.StringAttribute{
						Computed: true,
					},
				},
				CustomType: RuleGroupIdType{
					ObjectType: types.ObjectType{
						AttrTypes: RuleGroupIdValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "The ID of the firewall rule group this rule belongs to.",
				MarkdownDescription: "The ID of the firewall rule group this rule belongs to.",
			},
			"scopes": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.SetAttribute{
						ElementType: types.StringType,
						Optional:    true,
						Computed:    true,
					},
				},
				CustomType: ScopesType{
					ObjectType: types.ObjectType{
						AttrTypes: ScopesValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "The scopes applied to the firewall rule.",
				MarkdownDescription: "The scopes applied to the firewall rule.",
			},
			"sources": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.SetAttribute{
						ElementType: types.StringType,
						Optional:    true,
						Computed:    true,
					},
				},
				CustomType: SourcesType{
					ObjectType: types.ObjectType{
						AttrTypes: SourcesValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Source addresses or groups for the firewall rule.",
				MarkdownDescription: "Source addresses or groups for the firewall rule.",
			},
		},
	}
}

type NetworkFirewallRuleModel struct {
	Application          types.Set         `tfsdk:"application"`
	Description          types.String      `tfsdk:"description"`
	Destinations         DestinationsValue `tfsdk:"destinations"`
	Direction            types.String      `tfsdk:"direction"`
	Enabled              types.Bool        `tfsdk:"enabled"`
	Id                   types.Int64       `tfsdk:"id"`
	Name                 types.String      `tfsdk:"name"`
	NetworkIntegrationId types.Int64       `tfsdk:"network_integration_id"`
	Policy               types.String      `tfsdk:"policy"`
	Priority             types.Int64       `tfsdk:"priority"`
	Profile              types.Set         `tfsdk:"profile"`
	RuleGroupId          RuleGroupIdValue  `tfsdk:"rule_group_id"`
	Scopes               ScopesValue       `tfsdk:"scopes"`
	Sources              SourcesValue      `tfsdk:"sources"`
}

var _ basetypes.ObjectTypable = DestinationsType{}

type DestinationsType struct {
	basetypes.ObjectType
}

func (t DestinationsType) Equal(o attr.Type) bool {
	other, ok := o.(DestinationsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DestinationsType) String() string {
	return "DestinationsType"
}

func (t DestinationsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewDestinationsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDestinationsValueNull(), nil
	}

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`,
		)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.SetValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.SetValue, was: %T`, idAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return DestinationsValue{
		Id:    idVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewDestinationsValueNull() DestinationsValue {
	return DestinationsValue{
		state: attr.ValueStateNull,
	}
}

func NewDestinationsValueUnknown() DestinationsValue {
	return DestinationsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDestinationsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DestinationsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DestinationsValue Attribute Value",
				"While creating a DestinationsValue value, a missing attribute value was detected. "+
					"A DestinationsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DestinationsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DestinationsValue Attribute Type",
				"While creating a DestinationsValue value, an invalid attribute value was detected. "+
					"A DestinationsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DestinationsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DestinationsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DestinationsValue Attribute Value",
				"While creating a DestinationsValue value, an extra attribute value was detected. "+
					"A DestinationsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DestinationsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDestinationsValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`,
		)

		return NewDestinationsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.SetValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.SetValue, was: %T`, idAttribute),
		)
	}

	if diags.HasError() {
		return NewDestinationsValueUnknown(), diags
	}

	return DestinationsValue{
		Id:    idVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewDestinationsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DestinationsValue {
	object, diags := NewDestinationsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewDestinationsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DestinationsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDestinationsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDestinationsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDestinationsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDestinationsValueMust(DestinationsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DestinationsType) ValueType(ctx context.Context) attr.Value {
	return DestinationsValue{}
}

var _ basetypes.ObjectValuable = DestinationsValue{}

type DestinationsValue struct {
	Id    basetypes.SetValue `tfsdk:"id"`
	state attr.ValueState
}

func (v DestinationsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.SetType{
		ElemType: types.StringType,
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Id.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DestinationsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DestinationsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DestinationsValue) String() string {
	return "DestinationsValue"
}

func (v DestinationsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var idVal basetypes.SetValue
	switch {
	case v.Id.IsUnknown():
		idVal = types.SetUnknown(types.StringType)
	case v.Id.IsNull():
		idVal = types.SetNull(types.StringType)
	default:
		var d diag.Diagnostics
		idVal, d = types.SetValue(types.StringType, v.Id.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"id": basetypes.SetType{
				ElemType: types.StringType,
			},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"id": basetypes.SetType{
			ElemType: types.StringType,
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id": idVal,
		},
	)

	return objVal, diags
}

func (v DestinationsValue) Equal(o attr.Value) bool {
	other, ok := o.(DestinationsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	return true
}

func (v DestinationsValue) Type(ctx context.Context) attr.Type {
	return DestinationsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DestinationsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id": basetypes.SetType{
			ElemType: types.StringType,
		},
	}
}

var _ basetypes.ObjectTypable = RuleGroupIdType{}

type RuleGroupIdType struct {
	basetypes.ObjectType
}

func (t RuleGroupIdType) Equal(o attr.Type) bool {
	other, ok := o.(RuleGroupIdType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t RuleGroupIdType) String() string {
	return "RuleGroupIdType"
}

func (t RuleGroupIdType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewRuleGroupIdValueUnknown(), nil
	}

	if in.IsNull() {
		return NewRuleGroupIdValueNull(), nil
	}

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`,
		)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute),
		)
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`,
		)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return RuleGroupIdValue{
		Id:    idVal,
		Name:  nameVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewRuleGroupIdValueNull() RuleGroupIdValue {
	return RuleGroupIdValue{
		state: attr.ValueStateNull,
	}
}

func NewRuleGroupIdValueUnknown() RuleGroupIdValue {
	return RuleGroupIdValue{
		state: attr.ValueStateUnknown,
	}
}

func NewRuleGroupIdValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (RuleGroupIdValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing RuleGroupIdValue Attribute Value",
				"While creating a RuleGroupIdValue value, a missing attribute value was detected. "+
					"A RuleGroupIdValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RuleGroupIdValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid RuleGroupIdValue Attribute Type",
				"While creating a RuleGroupIdValue value, an invalid attribute value was detected. "+
					"A RuleGroupIdValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RuleGroupIdValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("RuleGroupIdValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra RuleGroupIdValue Attribute Value",
				"While creating a RuleGroupIdValue value, an extra attribute value was detected. "+
					"A RuleGroupIdValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra RuleGroupIdValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewRuleGroupIdValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`,
		)

		return NewRuleGroupIdValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute),
		)
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`,
		)

		return NewRuleGroupIdValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute),
		)
	}

	if diags.HasError() {
		return NewRuleGroupIdValueUnknown(), diags
	}

	return RuleGroupIdValue{
		Id:    idVal,
		Name:  nameVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewRuleGroupIdValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) RuleGroupIdValue {
	object, diags := NewRuleGroupIdValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewRuleGroupIdValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t RuleGroupIdType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewRuleGroupIdValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewRuleGroupIdValueUnknown(), nil
	}

	if in.IsNull() {
		return NewRuleGroupIdValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewRuleGroupIdValueMust(RuleGroupIdValue{}.AttributeTypes(ctx), attributes), nil
}

func (t RuleGroupIdType) ValueType(ctx context.Context) attr.Value {
	return RuleGroupIdValue{}
}

var _ basetypes.ObjectValuable = RuleGroupIdValue{}

type RuleGroupIdValue struct {
	Id    basetypes.Int64Value  `tfsdk:"id"`
	Name  basetypes.StringValue `tfsdk:"name"`
	state attr.ValueState
}

func (v RuleGroupIdValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Id.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v RuleGroupIdValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v RuleGroupIdValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v RuleGroupIdValue) String() string {
	return "RuleGroupIdValue"
}

func (v RuleGroupIdValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.Int64Type{},
		"name": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"name": v.Name,
		},
	)

	return objVal, diags
}

func (v RuleGroupIdValue) Equal(o attr.Value) bool {
	other, ok := o.(RuleGroupIdValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	return true
}

func (v RuleGroupIdValue) Type(ctx context.Context) attr.Type {
	return RuleGroupIdType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v RuleGroupIdValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.Int64Type{},
		"name": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ScopesType{}

type ScopesType struct {
	basetypes.ObjectType
}

func (t ScopesType) Equal(o attr.Type) bool {
	other, ok := o.(ScopesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ScopesType) String() string {
	return "ScopesType"
}

func (t ScopesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewScopesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewScopesValueNull(), nil
	}

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`,
		)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.SetValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.SetValue, was: %T`, idAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return ScopesValue{
		Id:    idVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewScopesValueNull() ScopesValue {
	return ScopesValue{
		state: attr.ValueStateNull,
	}
}

func NewScopesValueUnknown() ScopesValue {
	return ScopesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewScopesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ScopesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ScopesValue Attribute Value",
				"While creating a ScopesValue value, a missing attribute value was detected. "+
					"A ScopesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScopesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ScopesValue Attribute Type",
				"While creating a ScopesValue value, an invalid attribute value was detected. "+
					"A ScopesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScopesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ScopesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ScopesValue Attribute Value",
				"While creating a ScopesValue value, an extra attribute value was detected. "+
					"A ScopesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ScopesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewScopesValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`,
		)

		return NewScopesValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.SetValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.SetValue, was: %T`, idAttribute),
		)
	}

	if diags.HasError() {
		return NewScopesValueUnknown(), diags
	}

	return ScopesValue{
		Id:    idVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewScopesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ScopesValue {
	object, diags := NewScopesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewScopesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ScopesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewScopesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewScopesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewScopesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewScopesValueMust(ScopesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ScopesType) ValueType(ctx context.Context) attr.Value {
	return ScopesValue{}
}

var _ basetypes.ObjectValuable = ScopesValue{}

type ScopesValue struct {
	Id    basetypes.SetValue `tfsdk:"id"`
	state attr.ValueState
}

func (v ScopesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.SetType{
		ElemType: types.StringType,
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Id.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ScopesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ScopesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ScopesValue) String() string {
	return "ScopesValue"
}

func (v ScopesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var idVal basetypes.SetValue
	switch {
	case v.Id.IsUnknown():
		idVal = types.SetUnknown(types.StringType)
	case v.Id.IsNull():
		idVal = types.SetNull(types.StringType)
	default:
		var d diag.Diagnostics
		idVal, d = types.SetValue(types.StringType, v.Id.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"id": basetypes.SetType{
				ElemType: types.StringType,
			},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"id": basetypes.SetType{
			ElemType: types.StringType,
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id": idVal,
		},
	)

	return objVal, diags
}

func (v ScopesValue) Equal(o attr.Value) bool {
	other, ok := o.(ScopesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	return true
}

func (v ScopesValue) Type(ctx context.Context) attr.Type {
	return ScopesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ScopesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id": basetypes.SetType{
			ElemType: types.StringType,
		},
	}
}

var _ basetypes.ObjectTypable = SourcesType{}

type SourcesType struct {
	basetypes.ObjectType
}

func (t SourcesType) Equal(o attr.Type) bool {
	other, ok := o.(SourcesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SourcesType) String() string {
	return "SourcesType"
}

func (t SourcesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewSourcesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSourcesValueNull(), nil
	}

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`,
		)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.SetValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.SetValue, was: %T`, idAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return SourcesValue{
		Id:    idVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewSourcesValueNull() SourcesValue {
	return SourcesValue{
		state: attr.ValueStateNull,
	}
}

func NewSourcesValueUnknown() SourcesValue {
	return SourcesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSourcesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SourcesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SourcesValue Attribute Value",
				"While creating a SourcesValue value, a missing attribute value was detected. "+
					"A SourcesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SourcesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SourcesValue Attribute Type",
				"While creating a SourcesValue value, an invalid attribute value was detected. "+
					"A SourcesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SourcesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SourcesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SourcesValue Attribute Value",
				"While creating a SourcesValue value, an extra attribute value was detected. "+
					"A SourcesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SourcesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSourcesValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`,
		)

		return NewSourcesValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.SetValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.SetValue, was: %T`, idAttribute),
		)
	}

	if diags.HasError() {
		return NewSourcesValueUnknown(), diags
	}

	return SourcesValue{
		Id:    idVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewSourcesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SourcesValue {
	object, diags := NewSourcesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewSourcesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SourcesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSourcesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSourcesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSourcesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSourcesValueMust(SourcesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SourcesType) ValueType(ctx context.Context) attr.Value {
	return SourcesValue{}
}

var _ basetypes.ObjectValuable = SourcesValue{}

type SourcesValue struct {
	Id    basetypes.SetValue `tfsdk:"id"`
	state attr.ValueState
}

func (v SourcesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.SetType{
		ElemType: types.StringType,
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Id.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SourcesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SourcesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SourcesValue) String() string {
	return "SourcesValue"
}

func (v SourcesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var idVal basetypes.SetValue
	switch {
	case v.Id.IsUnknown():
		idVal = types.SetUnknown(types.StringType)
	case v.Id.IsNull():
		idVal = types.SetNull(types.StringType)
	default:
		var d diag.Diagnostics
		idVal, d = types.SetValue(types.StringType, v.Id.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"id": basetypes.SetType{
				ElemType: types.StringType,
			},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"id": basetypes.SetType{
			ElemType: types.StringType,
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id": idVal,
		},
	)

	return objVal, diags
}

func (v SourcesValue) Equal(o attr.Value) bool {
	other, ok := o.(SourcesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	return true
}

func (v SourcesValue) Type(ctx context.Context) attr.Type {
	return SourcesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SourcesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id": basetypes.SetType{
			ElemType: types.StringType,
		},
	}
}
