// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package networkrouterbgpneighbor

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-validators/dynamicvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/objectvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/HPE/terraform-provider-hpe/utils/modifiers"
	"github.com/HPE/terraform-provider-hpe/utils/validators"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func NetworkRouterBgpNeighborResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"allow_as_in": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Allow AS-in",
				MarkdownDescription: "Allow AS-in",
				Default:             booldefault.StaticBool(false),
			},
			"bfd_enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable BFD (Bidirectional Forwarding Detection)",
				MarkdownDescription: "Enable BFD (Bidirectional Forwarding Detection)",
				Default:             booldefault.StaticBool(false),
			},
			"bfd_interval": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "BFD interval in milliseconds",
				MarkdownDescription: "BFD interval in milliseconds",
			},
			"bfd_multiple": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "BFD multiplier",
				MarkdownDescription: "BFD multiplier",
			},
			"config": schema.DynamicAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Dynamic configuration",
				MarkdownDescription: "Dynamic configuration",
				Validators: []validator.Dynamic{
					validators.ValidObjectMap(),
					dynamicvalidator.ConflictsWith(path.Expressions{path.MatchRoot("config_nsxt"), path.MatchRoot("config_nsxv")}...),
				},
			},
			"config_nsxt": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"source_addresses": schema.SetAttribute{
						ElementType:         types.StringType,
						Optional:            true,
						Computed:            true,
						Description:         "Source IP addresses for the BGP session",
						MarkdownDescription: "Source IP addresses for the BGP session",
					},
				},
				CustomType: ConfigNsxtType{
					ObjectType: types.ObjectType{
						AttrTypes: ConfigNsxtValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Configuration for NSX-T Tier-0/Tier-1 router BGP neighbors",
				MarkdownDescription: "Configuration for NSX-T Tier-0/Tier-1 router BGP neighbors",
				Validators: []validator.Object{
					objectvalidator.ConflictsWith(path.Expressions{path.MatchRoot("config_nsxv")}...),
				},
			},
			"config_nsxv": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"interface": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The interface name for the BGP session (distributed routers only)",
						MarkdownDescription: "The interface name for the BGP session (distributed routers only)",
					},
					"router_id": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The router identifier (auto-populated for edge routers)",
						MarkdownDescription: "The router identifier (auto-populated for edge routers)",
					},
				},
				CustomType: ConfigNsxvType{
					ObjectType: types.ObjectType{
						AttrTypes: ConfigNsxvValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Configuration for NSX-V Edge/Distributed router BGP neighbors",
				MarkdownDescription: "Configuration for NSX-V Edge/Distributed router BGP neighbors",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Description of the BGP neighbor",
				MarkdownDescription: "Description of the BGP neighbor",
			},
			"forwarding_address": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Forwarding address (NSX-V distributed router)",
				MarkdownDescription: "Forwarding address (NSX-V distributed router)",
			},
			"hold_down": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Hold-down timer in seconds",
				MarkdownDescription: "Hold-down timer in seconds",
				Default:             int64default.StaticInt64(180),
			},
			"hop_limit": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Maximum hop limit",
				MarkdownDescription: "Maximum hop limit",
				Default:             int64default.StaticInt64(1),
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the BGP neighbor",
				MarkdownDescription: "The ID of the BGP neighbor",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"ip_address": schema.StringAttribute{
				Required:            true,
				Description:         "IP address of the BGP neighbor",
				MarkdownDescription: "IP address of the BGP neighbor",
			},
			"keep_alive": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Keep-alive interval in seconds",
				MarkdownDescription: "Keep-alive interval in seconds",
				Default:             int64default.StaticInt64(60),
			},
			"password_wo": schema.StringAttribute{
				Optional:            true,
				WriteOnly:           true,
				Description:         "Password (Write Only)",
				MarkdownDescription: "Password (Write Only)",
				PlanModifiers: []planmodifier.String{
					modifiers.NullableStringUpdateModifier{},
				},
			},
			"password_wo_version": schema.Int64Attribute{
				Optional:            true,
				Description:         "Password version. Used to determine if password_wo has been updated.",
				MarkdownDescription: "Password version. Used to determine if password_wo has been updated.",
			},
			"protocol_address": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Protocol address (NSX-V distributed router)",
				MarkdownDescription: "Protocol address (NSX-V distributed router)",
			},
			"remote_as": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Remote AS number",
				MarkdownDescription: "Remote AS number",
			},
			"restart_mode": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Graceful restart mode (e.g. HELPER_ONLY, GRACEFUL_RESTART, DISABLE)",
				MarkdownDescription: "Graceful restart mode (e.g. HELPER_ONLY, GRACEFUL_RESTART, DISABLE)",
				Validators: []validator.String{
					stringvalidator.OneOf("HELPER_ONLY", "GRACEFUL_RESTART", "DISABLE"),
				},
			},
			"route_filtering_in": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Inbound route filter name",
				MarkdownDescription: "Inbound route filter name",
			},
			"route_filtering_out": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Outbound route filter name",
				MarkdownDescription: "Outbound route filter name",
			},
			"route_filtering_type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Address family for route filtering (e.g. IPV4, IPV6)",
				MarkdownDescription: "Address family for route filtering (e.g. IPV4, IPV6)",
				Validators: []validator.String{
					stringvalidator.OneOf("IPV4", "IPV6"),
				},
			},
			"router_id": schema.Int64Attribute{
				Required:            true,
				Description:         "The ID of the network router",
				MarkdownDescription: "The ID of the network router",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"weight": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Route weight",
				MarkdownDescription: "Route weight",
				Default:             int64default.StaticInt64(60),
			},
		},
	}
}

type NetworkRouterBgpNeighborModel struct {
	AllowAsIn          types.Bool      `tfsdk:"allow_as_in"`
	BfdEnabled         types.Bool      `tfsdk:"bfd_enabled"`
	BfdInterval        types.Int64     `tfsdk:"bfd_interval"`
	BfdMultiple        types.Int64     `tfsdk:"bfd_multiple"`
	Config             types.Dynamic   `tfsdk:"config"`
	ConfigNsxt         ConfigNsxtValue `tfsdk:"config_nsxt"`
	ConfigNsxv         ConfigNsxvValue `tfsdk:"config_nsxv"`
	Description        types.String    `tfsdk:"description"`
	ForwardingAddress  types.String    `tfsdk:"forwarding_address"`
	HoldDown           types.Int64     `tfsdk:"hold_down"`
	HopLimit           types.Int64     `tfsdk:"hop_limit"`
	Id                 types.Int64     `tfsdk:"id"`
	IpAddress          types.String    `tfsdk:"ip_address"`
	KeepAlive          types.Int64     `tfsdk:"keep_alive"`
	PasswordWo         types.String    `tfsdk:"password_wo"`
	PasswordWoVersion  types.Int64     `tfsdk:"password_wo_version"`
	ProtocolAddress    types.String    `tfsdk:"protocol_address"`
	RemoteAs           types.String    `tfsdk:"remote_as"`
	RestartMode        types.String    `tfsdk:"restart_mode"`
	RouteFilteringIn   types.String    `tfsdk:"route_filtering_in"`
	RouteFilteringOut  types.String    `tfsdk:"route_filtering_out"`
	RouteFilteringType types.String    `tfsdk:"route_filtering_type"`
	RouterId           types.Int64     `tfsdk:"router_id"`
	Weight             types.Int64     `tfsdk:"weight"`
}

var _ basetypes.ObjectTypable = ConfigNsxtType{}

type ConfigNsxtType struct {
	basetypes.ObjectType
}

func (t ConfigNsxtType) Equal(o attr.Type) bool {
	other, ok := o.(ConfigNsxtType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConfigNsxtType) String() string {
	return "ConfigNsxtType"
}

func (t ConfigNsxtType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewConfigNsxtValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigNsxtValueNull(), nil
	}

	attributes := in.Attributes()

	sourceAddressesAttribute, ok := attributes["source_addresses"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`source_addresses is missing from object`,
		)

		return nil, diags
	}

	sourceAddressesVal, ok := sourceAddressesAttribute.(basetypes.SetValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`source_addresses expected to be basetypes.SetValue, was: %T`, sourceAddressesAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConfigNsxtValue{
		SourceAddresses: sourceAddressesVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewConfigNsxtValueNull() ConfigNsxtValue {
	return ConfigNsxtValue{
		state: attr.ValueStateNull,
	}
}

func NewConfigNsxtValueUnknown() ConfigNsxtValue {
	return ConfigNsxtValue{
		state: attr.ValueStateUnknown,
	}
}

func NewConfigNsxtValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConfigNsxtValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConfigNsxtValue Attribute Value",
				"While creating a ConfigNsxtValue value, a missing attribute value was detected. "+
					"A ConfigNsxtValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigNsxtValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConfigNsxtValue Attribute Type",
				"While creating a ConfigNsxtValue value, an invalid attribute value was detected. "+
					"A ConfigNsxtValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigNsxtValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConfigNsxtValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConfigNsxtValue Attribute Value",
				"While creating a ConfigNsxtValue value, an extra attribute value was detected. "+
					"A ConfigNsxtValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConfigNsxtValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConfigNsxtValueUnknown(), diags
	}

	sourceAddressesAttribute, ok := attributes["source_addresses"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`source_addresses is missing from object`,
		)

		return NewConfigNsxtValueUnknown(), diags
	}

	sourceAddressesVal, ok := sourceAddressesAttribute.(basetypes.SetValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`source_addresses expected to be basetypes.SetValue, was: %T`, sourceAddressesAttribute),
		)
	}

	if diags.HasError() {
		return NewConfigNsxtValueUnknown(), diags
	}

	return ConfigNsxtValue{
		SourceAddresses: sourceAddressesVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewConfigNsxtValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConfigNsxtValue {
	object, diags := NewConfigNsxtValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewConfigNsxtValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConfigNsxtType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConfigNsxtValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConfigNsxtValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigNsxtValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConfigNsxtValueMust(ConfigNsxtValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ConfigNsxtType) ValueType(ctx context.Context) attr.Value {
	return ConfigNsxtValue{}
}

var _ basetypes.ObjectValuable = ConfigNsxtValue{}

type ConfigNsxtValue struct {
	SourceAddresses basetypes.SetValue `tfsdk:"source_addresses"`
	state           attr.ValueState
}

func (v ConfigNsxtValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["source_addresses"] = basetypes.SetType{
		ElemType: types.StringType,
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.SourceAddresses.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["source_addresses"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConfigNsxtValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConfigNsxtValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConfigNsxtValue) String() string {
	return "ConfigNsxtValue"
}

func (v ConfigNsxtValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var sourceAddressesVal basetypes.SetValue
	switch {
	case v.SourceAddresses.IsUnknown():
		sourceAddressesVal = types.SetUnknown(types.StringType)
	case v.SourceAddresses.IsNull():
		sourceAddressesVal = types.SetNull(types.StringType)
	default:
		var d diag.Diagnostics
		sourceAddressesVal, d = types.SetValue(types.StringType, v.SourceAddresses.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"source_addresses": basetypes.SetType{
				ElemType: types.StringType,
			},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"source_addresses": basetypes.SetType{
			ElemType: types.StringType,
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"source_addresses": sourceAddressesVal,
		},
	)

	return objVal, diags
}

func (v ConfigNsxtValue) Equal(o attr.Value) bool {
	other, ok := o.(ConfigNsxtValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.SourceAddresses.Equal(other.SourceAddresses) {
		return false
	}

	return true
}

func (v ConfigNsxtValue) Type(ctx context.Context) attr.Type {
	return ConfigNsxtType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConfigNsxtValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"source_addresses": basetypes.SetType{
			ElemType: types.StringType,
		},
	}
}

var _ basetypes.ObjectTypable = ConfigNsxvType{}

type ConfigNsxvType struct {
	basetypes.ObjectType
}

func (t ConfigNsxvType) Equal(o attr.Type) bool {
	other, ok := o.(ConfigNsxvType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConfigNsxvType) String() string {
	return "ConfigNsxvType"
}

func (t ConfigNsxvType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewConfigNsxvValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigNsxvValueNull(), nil
	}

	attributes := in.Attributes()

	interfaceAttribute, ok := attributes["interface"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`interface is missing from object`,
		)

		return nil, diags
	}

	interfaceVal, ok := interfaceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`interface expected to be basetypes.StringValue, was: %T`, interfaceAttribute),
		)
	}

	routerIdAttribute, ok := attributes["router_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`router_id is missing from object`,
		)

		return nil, diags
	}

	routerIdVal, ok := routerIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`router_id expected to be basetypes.StringValue, was: %T`, routerIdAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConfigNsxvValue{
		Interface: interfaceVal,
		RouterId:  routerIdVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewConfigNsxvValueNull() ConfigNsxvValue {
	return ConfigNsxvValue{
		state: attr.ValueStateNull,
	}
}

func NewConfigNsxvValueUnknown() ConfigNsxvValue {
	return ConfigNsxvValue{
		state: attr.ValueStateUnknown,
	}
}

func NewConfigNsxvValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConfigNsxvValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConfigNsxvValue Attribute Value",
				"While creating a ConfigNsxvValue value, a missing attribute value was detected. "+
					"A ConfigNsxvValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigNsxvValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConfigNsxvValue Attribute Type",
				"While creating a ConfigNsxvValue value, an invalid attribute value was detected. "+
					"A ConfigNsxvValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigNsxvValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConfigNsxvValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConfigNsxvValue Attribute Value",
				"While creating a ConfigNsxvValue value, an extra attribute value was detected. "+
					"A ConfigNsxvValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConfigNsxvValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConfigNsxvValueUnknown(), diags
	}

	interfaceAttribute, ok := attributes["interface"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`interface is missing from object`,
		)

		return NewConfigNsxvValueUnknown(), diags
	}

	interfaceVal, ok := interfaceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`interface expected to be basetypes.StringValue, was: %T`, interfaceAttribute),
		)
	}

	routerIdAttribute, ok := attributes["router_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`router_id is missing from object`,
		)

		return NewConfigNsxvValueUnknown(), diags
	}

	routerIdVal, ok := routerIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`router_id expected to be basetypes.StringValue, was: %T`, routerIdAttribute),
		)
	}

	if diags.HasError() {
		return NewConfigNsxvValueUnknown(), diags
	}

	return ConfigNsxvValue{
		Interface: interfaceVal,
		RouterId:  routerIdVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewConfigNsxvValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConfigNsxvValue {
	object, diags := NewConfigNsxvValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewConfigNsxvValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConfigNsxvType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConfigNsxvValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConfigNsxvValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigNsxvValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConfigNsxvValueMust(ConfigNsxvValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ConfigNsxvType) ValueType(ctx context.Context) attr.Value {
	return ConfigNsxvValue{}
}

var _ basetypes.ObjectValuable = ConfigNsxvValue{}

type ConfigNsxvValue struct {
	Interface basetypes.StringValue `tfsdk:"interface"`
	RouterId  basetypes.StringValue `tfsdk:"router_id"`
	state     attr.ValueState
}

func (v ConfigNsxvValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["interface"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["router_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Interface.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["interface"] = val

		val, err = v.RouterId.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["router_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConfigNsxvValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConfigNsxvValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConfigNsxvValue) String() string {
	return "ConfigNsxvValue"
}

func (v ConfigNsxvValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"interface": basetypes.StringType{},
		"router_id": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"interface": v.Interface,
			"router_id": v.RouterId,
		},
	)

	return objVal, diags
}

func (v ConfigNsxvValue) Equal(o attr.Value) bool {
	other, ok := o.(ConfigNsxvValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Interface.Equal(other.Interface) {
		return false
	}

	if !v.RouterId.Equal(other.RouterId) {
		return false
	}

	return true
}

func (v ConfigNsxvValue) Type(ctx context.Context) attr.Type {
	return ConfigNsxvType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConfigNsxvValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"interface": basetypes.StringType{},
		"router_id": basetypes.StringType{},
	}
}
