// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package loadbalancermonitor

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func LoadBalancerMonitorResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"alias_port": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "An alternative port to use for health checks if different from the target port",
				MarkdownDescription: "An alternative port to use for health checks if different from the target port",
			},
			"config": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"monitor": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"id": schema.Int64Attribute{
								Optional:            true,
								Computed:            true,
								Description:         "The ID of the parent monitor. If set, the monitorType of the new monitor will be inherited from the parent monitor.",
								MarkdownDescription: "The ID of the parent monitor. If set, the monitorType of the new monitor will be inherited from the parent monitor.",
							},
						},
						CustomType: MonitorType{
							ObjectType: types.ObjectType{
								AttrTypes: MonitorValue{}.AttributeTypes(ctx),
							},
						},
						Optional:            true,
						Computed:            true,
						Description:         "Parent monitor reference. Allows this monitor to inherit from an existing monitor.",
						MarkdownDescription: "Parent monitor reference. Allows this monitor to inherit from an existing monitor.",
					},
					"monitor_config": schema.DynamicAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Free-form monitor configuration content.",
						MarkdownDescription: "Free-form monitor configuration content.",
					},
				},
				CustomType: ConfigType{
					ObjectType: types.ObjectType{
						AttrTypes: ConfigValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Configuration object with parameters that vary by monitor type",
				MarkdownDescription: "Configuration object with parameters that vary by monitor type",
			},
			"data_length": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The length in bytes of the data payload for ICMP echo requests",
				MarkdownDescription: "The length in bytes of the data payload for ICMP echo requests",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A description of the load balancer monitor",
				MarkdownDescription: "A description of the load balancer monitor",
			},
			"extra_config": schema.StringAttribute{
				Optional:            true,
				Description:         "Additional monitor extension configuration. Used with NSX-V load balancer monitors to provide extension parameters for specific monitor types (e.g. http, https, tcp, udp, dns, mssql, ldap). This field is write-only and not returned by the API.",
				MarkdownDescription: "Additional monitor extension configuration. Used with NSX-V load balancer monitors to provide extension parameters for specific monitor types (e.g. http, https, tcp, udp, dns, mssql, ldap). This field is write-only and not returned by the API.",
			},
			"fall_count": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The number of consecutive failed health checks before marking the target as down",
				MarkdownDescription: "The number of consecutive failed health checks before marking the target as down",
			},
			"id": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"load_balancer_id": schema.Int64Attribute{
				Required:            true,
				Description:         "The ID of the load balancer associated with the monitor",
				MarkdownDescription: "The ID of the load balancer associated with the monitor",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"max_retry": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The number of retries before the health check is considered failed",
				MarkdownDescription: "The number of retries before the health check is considered failed",
			},
			"monitor_destination": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The target path or URL for the health check (e.g. /health)",
				MarkdownDescription: "The target path or URL for the health check (e.g. /health)",
			},
			"monitor_interval": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The interval in seconds at which the monitor checks target health",
				MarkdownDescription: "The interval in seconds at which the monitor checks target health",
			},
			"monitor_password_wo": schema.StringAttribute{
				Optional:            true,
				WriteOnly:           true,
				Description:         "The password for authenticated health checks (Write Only)",
				MarkdownDescription: "The password for authenticated health checks (Write Only)",
			},
			"monitor_password_wo_version": schema.Int64Attribute{
				Optional:            true,
				Description:         "Monitor password version. Used to determine if monitor_password_wo has been updated.",
				MarkdownDescription: "Monitor password version. Used to determine if monitor_password_wo has been updated.",
			},
			"monitor_timeout": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The maximum time in seconds to wait for a health check response before marking as failed",
				MarkdownDescription: "The maximum time in seconds to wait for a health check response before marking as failed",
			},
			"monitor_type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The monitor protocol type. Valid values are: dns, http, https, icmp, ldap, mssql, passive, tcp, udp. The provider maps these to the appropriate load-balancer-specific value based on the load balancer type (e.g. http becomes LBHttpMonitorProfile for NSX-T).",
				MarkdownDescription: "The monitor protocol type. Valid values are: dns, http, https, icmp, ldap, mssql, passive, tcp, udp. The provider maps these to the appropriate load-balancer-specific value based on the load balancer type (e.g. http becomes LBHttpMonitorProfile for NSX-T).",
			},
			"monitor_username": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The username for authenticated health checks",
				MarkdownDescription: "The username for authenticated health checks",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the load balancer monitor",
				MarkdownDescription: "The name of the load balancer monitor",
			},
			"receive_code": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A comma-separated list of HTTP status codes expected for a successful health check (e.g. \"200\" or \"200,201\")",
				MarkdownDescription: "A comma-separated list of HTTP status codes expected for a successful health check (e.g. \"200\" or \"200,201\")",
			},
			"receive_data": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The expected response body string to validate in the health check response",
				MarkdownDescription: "The expected response body string to validate in the health check response",
			},
			"rise_count": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The number of consecutive successful health checks before marking the target as up",
				MarkdownDescription: "The number of consecutive successful health checks before marking the target as up",
			},
			"send_data": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The request body to send to the target during health checks",
				MarkdownDescription: "The request body to send to the target during health checks",
			},
			"send_type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The HTTP method for the health check request (e.g. GET, POST, HEAD)",
				MarkdownDescription: "The HTTP method for the health check request (e.g. GET, POST, HEAD)",
			},
			"send_version": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The HTTP protocol version to use in health check requests (e.g. HTTP/1.0, HTTP/1.1)",
				MarkdownDescription: "The HTTP protocol version to use in health check requests (e.g. HTTP/1.0, HTTP/1.1)",
			},
		},
	}
}

type LoadBalancerMonitorModel struct {
	AliasPort                types.Int64  `tfsdk:"alias_port"`
	Config                   ConfigValue  `tfsdk:"config"`
	DataLength               types.Int64  `tfsdk:"data_length"`
	Description              types.String `tfsdk:"description"`
	ExtraConfig              types.String `tfsdk:"extra_config"`
	FallCount                types.Int64  `tfsdk:"fall_count"`
	Id                       types.Int64  `tfsdk:"id"`
	LoadBalancerId           types.Int64  `tfsdk:"load_balancer_id"`
	MaxRetry                 types.Int64  `tfsdk:"max_retry"`
	MonitorDestination       types.String `tfsdk:"monitor_destination"`
	MonitorInterval          types.Int64  `tfsdk:"monitor_interval"`
	MonitorPasswordWo        types.String `tfsdk:"monitor_password_wo"`
	MonitorPasswordWoVersion types.Int64  `tfsdk:"monitor_password_wo_version"`
	MonitorTimeout           types.Int64  `tfsdk:"monitor_timeout"`
	MonitorType              types.String `tfsdk:"monitor_type"`
	MonitorUsername          types.String `tfsdk:"monitor_username"`
	Name                     types.String `tfsdk:"name"`
	ReceiveCode              types.String `tfsdk:"receive_code"`
	ReceiveData              types.String `tfsdk:"receive_data"`
	RiseCount                types.Int64  `tfsdk:"rise_count"`
	SendData                 types.String `tfsdk:"send_data"`
	SendType                 types.String `tfsdk:"send_type"`
	SendVersion              types.String `tfsdk:"send_version"`
}

var _ basetypes.ObjectTypable = ConfigType{}

type ConfigType struct {
	basetypes.ObjectType
}

func (t ConfigType) Equal(o attr.Type) bool {
	other, ok := o.(ConfigType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConfigType) String() string {
	return "ConfigType"
}

func (t ConfigType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewConfigValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigValueNull(), nil
	}

	attributes := in.Attributes()

	monitorAttribute, ok := attributes["monitor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`monitor is missing from object`,
		)

		return nil, diags
	}

	monitorVal, ok := monitorAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`monitor expected to be basetypes.ObjectValue, was: %T`, monitorAttribute),
		)
	}

	monitorConfigAttribute, ok := attributes["monitor_config"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`monitor_config is missing from object`,
		)

		return nil, diags
	}

	monitorConfigVal, ok := monitorConfigAttribute.(basetypes.DynamicValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`monitor_config expected to be basetypes.DynamicValue, was: %T`, monitorConfigAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConfigValue{
		Monitor:       monitorVal,
		MonitorConfig: monitorConfigVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewConfigValueNull() ConfigValue {
	return ConfigValue{
		state: attr.ValueStateNull,
	}
}

func NewConfigValueUnknown() ConfigValue {
	return ConfigValue{
		state: attr.ValueStateUnknown,
	}
}

func NewConfigValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConfigValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConfigValue Attribute Value",
				"While creating a ConfigValue value, a missing attribute value was detected. "+
					"A ConfigValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConfigValue Attribute Type",
				"While creating a ConfigValue value, an invalid attribute value was detected. "+
					"A ConfigValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConfigValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConfigValue Attribute Value",
				"While creating a ConfigValue value, an extra attribute value was detected. "+
					"A ConfigValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConfigValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConfigValueUnknown(), diags
	}

	monitorAttribute, ok := attributes["monitor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`monitor is missing from object`,
		)

		return NewConfigValueUnknown(), diags
	}

	monitorVal, ok := monitorAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`monitor expected to be basetypes.ObjectValue, was: %T`, monitorAttribute),
		)
	}

	monitorConfigAttribute, ok := attributes["monitor_config"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`monitor_config is missing from object`,
		)

		return NewConfigValueUnknown(), diags
	}

	monitorConfigVal, ok := monitorConfigAttribute.(basetypes.DynamicValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`monitor_config expected to be basetypes.DynamicValue, was: %T`, monitorConfigAttribute),
		)
	}

	if diags.HasError() {
		return NewConfigValueUnknown(), diags
	}

	return ConfigValue{
		Monitor:       monitorVal,
		MonitorConfig: monitorConfigVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewConfigValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConfigValue {
	object, diags := NewConfigValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewConfigValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConfigType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConfigValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConfigValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConfigValueMust(ConfigValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ConfigType) ValueType(ctx context.Context) attr.Value {
	return ConfigValue{}
}

var _ basetypes.ObjectValuable = ConfigValue{}

type ConfigValue struct {
	Monitor       basetypes.ObjectValue  `tfsdk:"monitor"`
	MonitorConfig basetypes.DynamicValue `tfsdk:"monitor_config"`
	state         attr.ValueState
}

func (v ConfigValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["monitor"] = basetypes.ObjectType{
		AttrTypes: MonitorValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["monitor_config"] = basetypes.DynamicType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Monitor.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["monitor"] = val

		val, err = v.MonitorConfig.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["monitor_config"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConfigValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConfigValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConfigValue) String() string {
	return "ConfigValue"
}

func (v ConfigValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var monitorVal basetypes.ObjectValue

	if v.Monitor.IsNull() {
		monitorVal = types.ObjectNull(
			MonitorValue{}.AttributeTypes(ctx),
		)
	}

	if v.Monitor.IsUnknown() {
		monitorVal = types.ObjectUnknown(
			MonitorValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Monitor.IsNull() && !v.Monitor.IsUnknown() {
		monitorVal = types.ObjectValueMust(
			MonitorValue{}.AttributeTypes(ctx),
			v.Monitor.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"monitor": basetypes.ObjectType{
			AttrTypes: MonitorValue{}.AttributeTypes(ctx),
		},
		"monitor_config": basetypes.DynamicType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"monitor":        monitorVal,
			"monitor_config": v.MonitorConfig,
		},
	)

	return objVal, diags
}

func (v ConfigValue) Equal(o attr.Value) bool {
	other, ok := o.(ConfigValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Monitor.Equal(other.Monitor) {
		return false
	}

	if !v.MonitorConfig.Equal(other.MonitorConfig) {
		return false
	}

	return true
}

func (v ConfigValue) Type(ctx context.Context) attr.Type {
	return ConfigType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConfigValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"monitor": basetypes.ObjectType{
			AttrTypes: MonitorValue{}.AttributeTypes(ctx),
		},
		"monitor_config": basetypes.DynamicType{},
	}
}

var _ basetypes.ObjectTypable = MonitorType{}

type MonitorType struct {
	basetypes.ObjectType
}

func (t MonitorType) Equal(o attr.Type) bool {
	other, ok := o.(MonitorType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MonitorType) String() string {
	return "MonitorType"
}

func (t MonitorType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewMonitorValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMonitorValueNull(), nil
	}

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`,
		)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return MonitorValue{
		Id:    idVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewMonitorValueNull() MonitorValue {
	return MonitorValue{
		state: attr.ValueStateNull,
	}
}

func NewMonitorValueUnknown() MonitorValue {
	return MonitorValue{
		state: attr.ValueStateUnknown,
	}
}

func NewMonitorValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MonitorValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MonitorValue Attribute Value",
				"While creating a MonitorValue value, a missing attribute value was detected. "+
					"A MonitorValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MonitorValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MonitorValue Attribute Type",
				"While creating a MonitorValue value, an invalid attribute value was detected. "+
					"A MonitorValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MonitorValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MonitorValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MonitorValue Attribute Value",
				"While creating a MonitorValue value, an extra attribute value was detected. "+
					"A MonitorValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MonitorValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewMonitorValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`,
		)

		return NewMonitorValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute),
		)
	}

	if diags.HasError() {
		return NewMonitorValueUnknown(), diags
	}

	return MonitorValue{
		Id:    idVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewMonitorValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MonitorValue {
	object, diags := NewMonitorValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewMonitorValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MonitorType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewMonitorValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewMonitorValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMonitorValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewMonitorValueMust(MonitorValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MonitorType) ValueType(ctx context.Context) attr.Value {
	return MonitorValue{}
}

var _ basetypes.ObjectValuable = MonitorValue{}

type MonitorValue struct {
	Id    basetypes.Int64Value `tfsdk:"id"`
	state attr.ValueState
}

func (v MonitorValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Id.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MonitorValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MonitorValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MonitorValue) String() string {
	return "MonitorValue"
}

func (v MonitorValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id": basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id": v.Id,
		},
	)

	return objVal, diags
}

func (v MonitorValue) Equal(o attr.Value) bool {
	other, ok := o.(MonitorValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	return true
}

func (v MonitorValue) Type(ctx context.Context) attr.Type {
	return MonitorType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MonitorValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id": basetypes.Int64Type{},
	}
}
