// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package ostype

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func OsTypeResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"bit_count": schema.Int64Attribute{
				Required:            true,
				Description:         "The architecture bit count (e.g. 32 or 64)",
				MarkdownDescription: "The architecture bit count (e.g. 32 or 64)",
			},
			"category": schema.StringAttribute{
				Optional:            true,
				Description:         "The category of the osType.",
				MarkdownDescription: "The category of the osType.",
			},
			"cloud_init_version": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The version of CloudInit being used",
				MarkdownDescription: "The version of CloudInit being used",
			},
			"code": schema.StringAttribute{
				Required:            true,
				Description:         "The code Morpheus uses as an internal identifier.",
				MarkdownDescription: "The code Morpheus uses as an internal identifier.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The description of the osType.",
				MarkdownDescription: "The description of the osType.",
			},
			"id": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"install_agent": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether to install the Morpheus agent on provisioned instances",
				MarkdownDescription: "Whether to install the Morpheus agent on provisioned instances",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the osType.",
				MarkdownDescription: "The name of the osType.",
			},
			"os_codename": schema.StringAttribute{
				Optional:            true,
				Description:         "The osCodename of the osType.",
				MarkdownDescription: "The osCodename of the osType.",
			},
			"os_family": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The osFamily of the osType.",
				MarkdownDescription: "The osFamily of the osType.",
			},
			"os_name": schema.StringAttribute{
				Optional:            true,
				Description:         "The osName of the osType.",
				MarkdownDescription: "The osName of the osType.",
			},
			"os_version": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The osVersion of the osType.",
				MarkdownDescription: "The osVersion of the osType.",
			},
			"owner": schema.StringAttribute{
				Computed:            true,
				Description:         "The owner of the osType.",
				MarkdownDescription: "The owner of the osType.",
			},
			"platform": schema.StringAttribute{
				Required:            true,
				Description:         "The platform of the osType (e.g. linux, windows).",
				MarkdownDescription: "The platform of the osType (e.g. linux, windows).",
			},
			"vendor": schema.StringAttribute{
				Optional:            true,
				Description:         "The vendor of the osType.",
				MarkdownDescription: "The vendor of the osType.",
			},
		},
	}
}

type OsTypeModel struct {
	BitCount         types.Int64  `tfsdk:"bit_count"`
	Category         types.String `tfsdk:"category"`
	CloudInitVersion types.String `tfsdk:"cloud_init_version"`
	Code             types.String `tfsdk:"code"`
	Description      types.String `tfsdk:"description"`
	Id               types.Int64  `tfsdk:"id"`
	InstallAgent     types.Bool   `tfsdk:"install_agent"`
	Name             types.String `tfsdk:"name"`
	OsCodename       types.String `tfsdk:"os_codename"`
	OsFamily         types.String `tfsdk:"os_family"`
	OsName           types.String `tfsdk:"os_name"`
	OsVersion        types.String `tfsdk:"os_version"`
	Owner            types.String `tfsdk:"owner"`
	Platform         types.String `tfsdk:"platform"`
	Vendor           types.String `tfsdk:"vendor"`
}
