// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package loadbalancer

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-validators/boolvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/dynamicvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/objectvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/HPE/terraform-provider-hpe/utils/validators"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func LoadBalancerResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cloud_id": schema.Int64Attribute{
				Optional:            true,
				Description:         "The ID of the cloud associated with the load balancer",
				MarkdownDescription: "The ID of the cloud associated with the load balancer",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"config": schema.DynamicAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Configuration object with parameters that vary by load balancer type.",
				MarkdownDescription: "Configuration object with parameters that vary by load balancer type.",
				Validators: []validator.Dynamic{
					validators.ValidObjectMap(),
					dynamicvalidator.ConflictsWith(path.Expressions{
						path.MatchRoot("config_haproxy"),
						path.MatchRoot("config_nsxt"),
					}...),
					dynamicvalidator.ExactlyOneOf(path.Expressions{
						path.MatchRoot("config"),
						path.MatchRoot("config_haproxy"),
						path.MatchRoot("config_nsxt"),
					}...),
				},
			},
			"config_haproxy": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"plan_id": schema.Int64Attribute{
						Required:            true,
						Description:         "The ID of the service plan for the HAProxy load balancer",
						MarkdownDescription: "The ID of the service plan for the HAProxy load balancer",
					},
					"pool": schema.StringAttribute{
						Required:            true,
						Description:         "The ID of the network pool for the HAProxy load balancer",
						MarkdownDescription: "The ID of the network pool for the HAProxy load balancer",
					},
				},
				CustomType: ConfigHaproxyType{
					ObjectType: types.ObjectType{
						AttrTypes: ConfigHaproxyValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Description:         "Configuration for HAProxy container load balancer type",
				MarkdownDescription: "Configuration for HAProxy container load balancer type",
				Validators: []validator.Object{
					objectvalidator.ConflictsWith(path.Expressions{path.MatchRoot("type_code")}...),
				},
			},
			"config_nsxt": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"admin_state": schema.BoolAttribute{
						Optional:            true,
						Description:         "If true then Admin State will be active/enabled.",
						MarkdownDescription: "If true then Admin State will be active/enabled.",
						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.RequiresReplace(),
						},
					},
					"log_level": schema.StringAttribute{
						Optional:            true,
						Description:         "Supported Values are \"DEBUG\", \"INFO\", \"WARNING\", \"ERROR\", \"CRITICAL\", \"ALERT\", \"EMERGENCY\"",
						MarkdownDescription: "Supported Values are \"DEBUG\", \"INFO\", \"WARNING\", \"ERROR\", \"CRITICAL\", \"ALERT\", \"EMERGENCY\"",
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
						Validators: []validator.String{
							stringvalidator.OneOf("DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL", "ALERT", "EMERGENCY"),
						},
					},
					"size": schema.StringAttribute{
						Optional:            true,
						Description:         "Supported Values are \"SMALL\", \"MEDIUM\", \"LARGE\"",
						MarkdownDescription: "Supported Values are \"SMALL\", \"MEDIUM\", \"LARGE\"",
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
						Validators: []validator.String{
							stringvalidator.OneOf("SMALL", "MEDIUM", "LARGE"),
						},
					},
					"tier1_gateway": schema.StringAttribute{
						Required:            true,
						Description:         "Provider ID of the Tier-1 Gateway. provider_id can be found in the hpe_morpheus_network_router datasource.",
						MarkdownDescription: "Provider ID of the Tier-1 Gateway. provider_id can be found in the hpe_morpheus_network_router datasource.",
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
				},
				CustomType: ConfigNsxtType{
					ObjectType: types.ObjectType{
						AttrTypes: ConfigNsxtValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Description:         "Configuration for NSX-T load balancer type",
				MarkdownDescription: "Configuration for NSX-T load balancer type",
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplace(),
				},
				Validators: []validator.Object{
					objectvalidator.ConflictsWith(path.Expressions{path.MatchRoot("config"), path.MatchRoot("config_haproxy")}...),
				},
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Description",
				MarkdownDescription: "Description",
			},
			"group_id": schema.Int64Attribute{
				Optional:            true,
				Description:         "The ID of the group associated with the load balancer",
				MarkdownDescription: "The ID of the group associated with the load balancer",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"id": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name",
				MarkdownDescription: "Name",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(32),
				},
			},
			"network_server_id": schema.Int64Attribute{
				Optional:            true,
				Description:         "Network Server ID",
				MarkdownDescription: "Network Server ID",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"permissions": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"all": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Pass true to allow access to all groups",
						MarkdownDescription: "Pass true to allow access to all groups",
						Validators: []validator.Bool{
							boolvalidator.ConflictsWith(path.Expressions{
								path.MatchRelative().AtParent().AtName("groups"),
							}...),
						},
					},
					"groups": schema.ListAttribute{
						ElementType:         types.Int64Type,
						Optional:            true,
						Computed:            true,
						Description:         "Array of group IDs that are allowed access",
						MarkdownDescription: "Array of group IDs that are allowed access",
					},
				},
				CustomType: PermissionsType{
					ObjectType: types.ObjectType{
						AttrTypes: PermissionsValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Resource permissions for the load balancer",
				MarkdownDescription: "Resource permissions for the load balancer",
			},
			"tenants": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.Int64Attribute{
							Optional: true,
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: TenantsType{
						ObjectType: types.ObjectType{
							AttrTypes: TenantsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Array of tenant account ids that are allowed access",
				MarkdownDescription: "Array of tenant account ids that are allowed access",
			},
			"type_code": schema.StringAttribute{
				Optional:            true,
				Description:         "The type code of the load balancer (e.g. haproxyContainer)",
				MarkdownDescription: "The type code of the load balancer (e.g. haproxyContainer)",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"visibility": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "private or public",
				MarkdownDescription: "private or public",
				Validators: []validator.String{
					stringvalidator.OneOf("public", "private"),
				},
				Default: stringdefault.StaticString("public"),
			},
		},
	}
}

type LoadBalancerModel struct {
	CloudId         types.Int64        `tfsdk:"cloud_id"`
	Config          types.Dynamic      `tfsdk:"config"`
	ConfigHaproxy   ConfigHaproxyValue `tfsdk:"config_haproxy"`
	ConfigNsxt      ConfigNsxtValue    `tfsdk:"config_nsxt"`
	Description     types.String       `tfsdk:"description"`
	GroupId         types.Int64        `tfsdk:"group_id"`
	Id              types.Int64        `tfsdk:"id"`
	Name            types.String       `tfsdk:"name"`
	NetworkServerId types.Int64        `tfsdk:"network_server_id"`
	Permissions     PermissionsValue   `tfsdk:"permissions"`
	Tenants         types.Set          `tfsdk:"tenants"`
	TypeCode        types.String       `tfsdk:"type_code"`
	Visibility      types.String       `tfsdk:"visibility"`
}

var _ basetypes.ObjectTypable = ConfigHaproxyType{}

type ConfigHaproxyType struct {
	basetypes.ObjectType
}

func (t ConfigHaproxyType) Equal(o attr.Type) bool {
	other, ok := o.(ConfigHaproxyType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConfigHaproxyType) String() string {
	return "ConfigHaproxyType"
}

func (t ConfigHaproxyType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewConfigHaproxyValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigHaproxyValueNull(), nil
	}

	attributes := in.Attributes()

	planIdAttribute, ok := attributes["plan_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`plan_id is missing from object`,
		)

		return nil, diags
	}

	planIdVal, ok := planIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`plan_id expected to be basetypes.Int64Value, was: %T`, planIdAttribute),
		)
	}

	poolAttribute, ok := attributes["pool"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`pool is missing from object`,
		)

		return nil, diags
	}

	poolVal, ok := poolAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`pool expected to be basetypes.StringValue, was: %T`, poolAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConfigHaproxyValue{
		PlanId: planIdVal,
		Pool:   poolVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewConfigHaproxyValueNull() ConfigHaproxyValue {
	return ConfigHaproxyValue{
		state: attr.ValueStateNull,
	}
}

func NewConfigHaproxyValueUnknown() ConfigHaproxyValue {
	return ConfigHaproxyValue{
		state: attr.ValueStateUnknown,
	}
}

func NewConfigHaproxyValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConfigHaproxyValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConfigHaproxyValue Attribute Value",
				"While creating a ConfigHaproxyValue value, a missing attribute value was detected. "+
					"A ConfigHaproxyValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigHaproxyValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConfigHaproxyValue Attribute Type",
				"While creating a ConfigHaproxyValue value, an invalid attribute value was detected. "+
					"A ConfigHaproxyValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigHaproxyValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConfigHaproxyValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConfigHaproxyValue Attribute Value",
				"While creating a ConfigHaproxyValue value, an extra attribute value was detected. "+
					"A ConfigHaproxyValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConfigHaproxyValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConfigHaproxyValueUnknown(), diags
	}

	planIdAttribute, ok := attributes["plan_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`plan_id is missing from object`,
		)

		return NewConfigHaproxyValueUnknown(), diags
	}

	planIdVal, ok := planIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`plan_id expected to be basetypes.Int64Value, was: %T`, planIdAttribute),
		)
	}

	poolAttribute, ok := attributes["pool"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`pool is missing from object`,
		)

		return NewConfigHaproxyValueUnknown(), diags
	}

	poolVal, ok := poolAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`pool expected to be basetypes.StringValue, was: %T`, poolAttribute),
		)
	}

	if diags.HasError() {
		return NewConfigHaproxyValueUnknown(), diags
	}

	return ConfigHaproxyValue{
		PlanId: planIdVal,
		Pool:   poolVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewConfigHaproxyValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConfigHaproxyValue {
	object, diags := NewConfigHaproxyValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewConfigHaproxyValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConfigHaproxyType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConfigHaproxyValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConfigHaproxyValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigHaproxyValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConfigHaproxyValueMust(ConfigHaproxyValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ConfigHaproxyType) ValueType(ctx context.Context) attr.Value {
	return ConfigHaproxyValue{}
}

var _ basetypes.ObjectValuable = ConfigHaproxyValue{}

type ConfigHaproxyValue struct {
	PlanId basetypes.Int64Value  `tfsdk:"plan_id"`
	Pool   basetypes.StringValue `tfsdk:"pool"`
	state  attr.ValueState
}

func (v ConfigHaproxyValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["plan_id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["pool"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.PlanId.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["plan_id"] = val

		val, err = v.Pool.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["pool"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConfigHaproxyValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConfigHaproxyValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConfigHaproxyValue) String() string {
	return "ConfigHaproxyValue"
}

func (v ConfigHaproxyValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"plan_id": basetypes.Int64Type{},
		"pool":    basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"plan_id": v.PlanId,
			"pool":    v.Pool,
		},
	)

	return objVal, diags
}

func (v ConfigHaproxyValue) Equal(o attr.Value) bool {
	other, ok := o.(ConfigHaproxyValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.PlanId.Equal(other.PlanId) {
		return false
	}

	if !v.Pool.Equal(other.Pool) {
		return false
	}

	return true
}

func (v ConfigHaproxyValue) Type(ctx context.Context) attr.Type {
	return ConfigHaproxyType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConfigHaproxyValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"plan_id": basetypes.Int64Type{},
		"pool":    basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ConfigNsxtType{}

type ConfigNsxtType struct {
	basetypes.ObjectType
}

func (t ConfigNsxtType) Equal(o attr.Type) bool {
	other, ok := o.(ConfigNsxtType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConfigNsxtType) String() string {
	return "ConfigNsxtType"
}

func (t ConfigNsxtType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewConfigNsxtValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigNsxtValueNull(), nil
	}

	attributes := in.Attributes()

	adminStateAttribute, ok := attributes["admin_state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`admin_state is missing from object`,
		)

		return nil, diags
	}

	adminStateVal, ok := adminStateAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`admin_state expected to be basetypes.BoolValue, was: %T`, adminStateAttribute),
		)
	}

	logLevelAttribute, ok := attributes["log_level"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`log_level is missing from object`,
		)

		return nil, diags
	}

	logLevelVal, ok := logLevelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`log_level expected to be basetypes.StringValue, was: %T`, logLevelAttribute),
		)
	}

	sizeAttribute, ok := attributes["size"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size is missing from object`,
		)

		return nil, diags
	}

	sizeVal, ok := sizeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size expected to be basetypes.StringValue, was: %T`, sizeAttribute),
		)
	}

	tier1GatewayAttribute, ok := attributes["tier1_gateway"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_gateway is missing from object`,
		)

		return nil, diags
	}

	tier1GatewayVal, ok := tier1GatewayAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_gateway expected to be basetypes.StringValue, was: %T`, tier1GatewayAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConfigNsxtValue{
		AdminState:   adminStateVal,
		LogLevel:     logLevelVal,
		Size:         sizeVal,
		Tier1Gateway: tier1GatewayVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewConfigNsxtValueNull() ConfigNsxtValue {
	return ConfigNsxtValue{
		state: attr.ValueStateNull,
	}
}

func NewConfigNsxtValueUnknown() ConfigNsxtValue {
	return ConfigNsxtValue{
		state: attr.ValueStateUnknown,
	}
}

func NewConfigNsxtValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConfigNsxtValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConfigNsxtValue Attribute Value",
				"While creating a ConfigNsxtValue value, a missing attribute value was detected. "+
					"A ConfigNsxtValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigNsxtValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConfigNsxtValue Attribute Type",
				"While creating a ConfigNsxtValue value, an invalid attribute value was detected. "+
					"A ConfigNsxtValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigNsxtValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConfigNsxtValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConfigNsxtValue Attribute Value",
				"While creating a ConfigNsxtValue value, an extra attribute value was detected. "+
					"A ConfigNsxtValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConfigNsxtValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConfigNsxtValueUnknown(), diags
	}

	adminStateAttribute, ok := attributes["admin_state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`admin_state is missing from object`,
		)

		return NewConfigNsxtValueUnknown(), diags
	}

	adminStateVal, ok := adminStateAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`admin_state expected to be basetypes.BoolValue, was: %T`, adminStateAttribute),
		)
	}

	logLevelAttribute, ok := attributes["log_level"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`log_level is missing from object`,
		)

		return NewConfigNsxtValueUnknown(), diags
	}

	logLevelVal, ok := logLevelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`log_level expected to be basetypes.StringValue, was: %T`, logLevelAttribute),
		)
	}

	sizeAttribute, ok := attributes["size"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size is missing from object`,
		)

		return NewConfigNsxtValueUnknown(), diags
	}

	sizeVal, ok := sizeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size expected to be basetypes.StringValue, was: %T`, sizeAttribute),
		)
	}

	tier1GatewayAttribute, ok := attributes["tier1_gateway"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tier1_gateway is missing from object`,
		)

		return NewConfigNsxtValueUnknown(), diags
	}

	tier1GatewayVal, ok := tier1GatewayAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tier1_gateway expected to be basetypes.StringValue, was: %T`, tier1GatewayAttribute),
		)
	}

	if diags.HasError() {
		return NewConfigNsxtValueUnknown(), diags
	}

	return ConfigNsxtValue{
		AdminState:   adminStateVal,
		LogLevel:     logLevelVal,
		Size:         sizeVal,
		Tier1Gateway: tier1GatewayVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewConfigNsxtValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConfigNsxtValue {
	object, diags := NewConfigNsxtValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewConfigNsxtValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConfigNsxtType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConfigNsxtValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConfigNsxtValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigNsxtValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConfigNsxtValueMust(ConfigNsxtValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ConfigNsxtType) ValueType(ctx context.Context) attr.Value {
	return ConfigNsxtValue{}
}

var _ basetypes.ObjectValuable = ConfigNsxtValue{}

type ConfigNsxtValue struct {
	AdminState   basetypes.BoolValue   `tfsdk:"admin_state"`
	LogLevel     basetypes.StringValue `tfsdk:"log_level"`
	Size         basetypes.StringValue `tfsdk:"size"`
	Tier1Gateway basetypes.StringValue `tfsdk:"tier1_gateway"`
	state        attr.ValueState
}

func (v ConfigNsxtValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["admin_state"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["log_level"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["size"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["tier1_gateway"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.AdminState.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["admin_state"] = val

		val, err = v.LogLevel.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["log_level"] = val

		val, err = v.Size.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["size"] = val

		val, err = v.Tier1Gateway.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tier1_gateway"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConfigNsxtValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConfigNsxtValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConfigNsxtValue) String() string {
	return "ConfigNsxtValue"
}

func (v ConfigNsxtValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"admin_state":   basetypes.BoolType{},
		"log_level":     basetypes.StringType{},
		"size":          basetypes.StringType{},
		"tier1_gateway": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"admin_state":   v.AdminState,
			"log_level":     v.LogLevel,
			"size":          v.Size,
			"tier1_gateway": v.Tier1Gateway,
		},
	)

	return objVal, diags
}

func (v ConfigNsxtValue) Equal(o attr.Value) bool {
	other, ok := o.(ConfigNsxtValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AdminState.Equal(other.AdminState) {
		return false
	}

	if !v.LogLevel.Equal(other.LogLevel) {
		return false
	}

	if !v.Size.Equal(other.Size) {
		return false
	}

	if !v.Tier1Gateway.Equal(other.Tier1Gateway) {
		return false
	}

	return true
}

func (v ConfigNsxtValue) Type(ctx context.Context) attr.Type {
	return ConfigNsxtType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConfigNsxtValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"admin_state":   basetypes.BoolType{},
		"log_level":     basetypes.StringType{},
		"size":          basetypes.StringType{},
		"tier1_gateway": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = PermissionsType{}

type PermissionsType struct {
	basetypes.ObjectType
}

func (t PermissionsType) Equal(o attr.Type) bool {
	other, ok := o.(PermissionsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t PermissionsType) String() string {
	return "PermissionsType"
}

func (t PermissionsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewPermissionsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewPermissionsValueNull(), nil
	}

	attributes := in.Attributes()

	allAttribute, ok := attributes["all"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`all is missing from object`,
		)

		return nil, diags
	}

	allVal, ok := allAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`all expected to be basetypes.BoolValue, was: %T`, allAttribute),
		)
	}

	groupsAttribute, ok := attributes["groups"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`groups is missing from object`,
		)

		return nil, diags
	}

	groupsVal, ok := groupsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`groups expected to be basetypes.ListValue, was: %T`, groupsAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return PermissionsValue{
		All:    allVal,
		Groups: groupsVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewPermissionsValueNull() PermissionsValue {
	return PermissionsValue{
		state: attr.ValueStateNull,
	}
}

func NewPermissionsValueUnknown() PermissionsValue {
	return PermissionsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewPermissionsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (PermissionsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing PermissionsValue Attribute Value",
				"While creating a PermissionsValue value, a missing attribute value was detected. "+
					"A PermissionsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PermissionsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid PermissionsValue Attribute Type",
				"While creating a PermissionsValue value, an invalid attribute value was detected. "+
					"A PermissionsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PermissionsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("PermissionsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra PermissionsValue Attribute Value",
				"While creating a PermissionsValue value, an extra attribute value was detected. "+
					"A PermissionsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra PermissionsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewPermissionsValueUnknown(), diags
	}

	allAttribute, ok := attributes["all"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`all is missing from object`,
		)

		return NewPermissionsValueUnknown(), diags
	}

	allVal, ok := allAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`all expected to be basetypes.BoolValue, was: %T`, allAttribute),
		)
	}

	groupsAttribute, ok := attributes["groups"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`groups is missing from object`,
		)

		return NewPermissionsValueUnknown(), diags
	}

	groupsVal, ok := groupsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`groups expected to be basetypes.ListValue, was: %T`, groupsAttribute),
		)
	}

	if diags.HasError() {
		return NewPermissionsValueUnknown(), diags
	}

	return PermissionsValue{
		All:    allVal,
		Groups: groupsVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewPermissionsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) PermissionsValue {
	object, diags := NewPermissionsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewPermissionsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t PermissionsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewPermissionsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewPermissionsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewPermissionsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewPermissionsValueMust(PermissionsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t PermissionsType) ValueType(ctx context.Context) attr.Value {
	return PermissionsValue{}
}

var _ basetypes.ObjectValuable = PermissionsValue{}

type PermissionsValue struct {
	All    basetypes.BoolValue `tfsdk:"all"`
	Groups basetypes.ListValue `tfsdk:"groups"`
	state  attr.ValueState
}

func (v PermissionsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["all"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["groups"] = basetypes.ListType{
		ElemType: types.Int64Type,
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.All.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["all"] = val

		val, err = v.Groups.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["groups"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v PermissionsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v PermissionsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v PermissionsValue) String() string {
	return "PermissionsValue"
}

func (v PermissionsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var groupsVal basetypes.ListValue
	switch {
	case v.Groups.IsUnknown():
		groupsVal = types.ListUnknown(types.Int64Type)
	case v.Groups.IsNull():
		groupsVal = types.ListNull(types.Int64Type)
	default:
		var d diag.Diagnostics
		groupsVal, d = types.ListValue(types.Int64Type, v.Groups.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"all": basetypes.BoolType{},
			"groups": basetypes.ListType{
				ElemType: types.Int64Type,
			},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"all": basetypes.BoolType{},
		"groups": basetypes.ListType{
			ElemType: types.Int64Type,
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"all":    v.All,
			"groups": groupsVal,
		},
	)

	return objVal, diags
}

func (v PermissionsValue) Equal(o attr.Value) bool {
	other, ok := o.(PermissionsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.All.Equal(other.All) {
		return false
	}

	if !v.Groups.Equal(other.Groups) {
		return false
	}

	return true
}

func (v PermissionsValue) Type(ctx context.Context) attr.Type {
	return PermissionsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v PermissionsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"all": basetypes.BoolType{},
		"groups": basetypes.ListType{
			ElemType: types.Int64Type,
		},
	}
}

var _ basetypes.ObjectTypable = TenantsType{}

type TenantsType struct {
	basetypes.ObjectType
}

func (t TenantsType) Equal(o attr.Type) bool {
	other, ok := o.(TenantsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TenantsType) String() string {
	return "TenantsType"
}

func (t TenantsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewTenantsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTenantsValueNull(), nil
	}

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`,
		)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute),
		)
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`,
		)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return TenantsValue{
		Id:    idVal,
		Name:  nameVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTenantsValueNull() TenantsValue {
	return TenantsValue{
		state: attr.ValueStateNull,
	}
}

func NewTenantsValueUnknown() TenantsValue {
	return TenantsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTenantsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TenantsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TenantsValue Attribute Value",
				"While creating a TenantsValue value, a missing attribute value was detected. "+
					"A TenantsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TenantsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TenantsValue Attribute Type",
				"While creating a TenantsValue value, an invalid attribute value was detected. "+
					"A TenantsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TenantsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TenantsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TenantsValue Attribute Value",
				"While creating a TenantsValue value, an extra attribute value was detected. "+
					"A TenantsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TenantsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTenantsValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`,
		)

		return NewTenantsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute),
		)
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`,
		)

		return NewTenantsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute),
		)
	}

	if diags.HasError() {
		return NewTenantsValueUnknown(), diags
	}

	return TenantsValue{
		Id:    idVal,
		Name:  nameVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTenantsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TenantsValue {
	object, diags := NewTenantsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewTenantsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TenantsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTenantsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTenantsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTenantsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTenantsValueMust(TenantsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TenantsType) ValueType(ctx context.Context) attr.Value {
	return TenantsValue{}
}

var _ basetypes.ObjectValuable = TenantsValue{}

type TenantsValue struct {
	Id    basetypes.Int64Value  `tfsdk:"id"`
	Name  basetypes.StringValue `tfsdk:"name"`
	state attr.ValueState
}

func (v TenantsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Id.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TenantsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TenantsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TenantsValue) String() string {
	return "TenantsValue"
}

func (v TenantsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.Int64Type{},
		"name": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"name": v.Name,
		},
	)

	return objVal, diags
}

func (v TenantsValue) Equal(o attr.Value) bool {
	other, ok := o.(TenantsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	return true
}

func (v TenantsValue) Type(ctx context.Context) attr.Type {
	return TenantsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TenantsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.Int64Type{},
		"name": basetypes.StringType{},
	}
}
