// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package task

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/HPE/terraform-provider-hpe/utils/customtypes"
	"github.com/HPE/terraform-provider-hpe/utils/validators"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func TaskResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"allow_custom_config": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "When enabled, a text area is provided during manual Task execution to allow the user to pass extra variables or specify extra configuration",
				MarkdownDescription: "When enabled, a text area is provided during manual Task execution to allow the user to pass extra variables or specify extra configuration",
			},
			"code": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A unique code for the task",
				MarkdownDescription: "A unique code for the task",
			},
			"config": schema.DynamicAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Configuration object. Settings vary by type.",
				MarkdownDescription: "Configuration object. Settings vary by type.",
				Validators: []validator.Dynamic{
					validators.ValidObjectMap(),
				},
			},
			"config_conditional_workflow": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"conditional_script": schema.StringAttribute{
						CustomType:          customtypes.TrimmedStringType{},
						Optional:            true,
						Computed:            true,
						Description:         "Allows the user to set JavaScript logic. If it resolves to true, HPE Morpheus Enterprise will run the Operational Workflow set as the “IF OPERATIONAL WORKFLOW” and if it resolves to false, HPE Morpheus Enterprise will run the “ELSE OPERATIONAL WORKFLOW”",
						MarkdownDescription: "Allows the user to set JavaScript logic. If it resolves to true, HPE Morpheus Enterprise will run the Operational Workflow set as the “IF OPERATIONAL WORKFLOW” and if it resolves to false, HPE Morpheus Enterprise will run the “ELSE OPERATIONAL WORKFLOW”",
					},
					"else_operational_workflow_id": schema.Int64Attribute{
						Optional:            true,
						Computed:            true,
						Description:         "else Operational Workflow ID",
						MarkdownDescription: "else Operational Workflow ID",
					},
					"else_operational_workflow_name": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Else Operational Workflow Name",
						MarkdownDescription: "Else Operational Workflow Name",
					},
					"if_operational_workflow_id": schema.Int64Attribute{
						Optional:            true,
						Computed:            true,
						Description:         "If Operational Workflow ID",
						MarkdownDescription: "If Operational Workflow ID",
					},
					"if_operational_workflow_name": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "If Operational Workflow Name",
						MarkdownDescription: "If Operational Workflow Name",
					},
				},
				CustomType: ConfigConditionalWorkflowType{
					ObjectType: types.ObjectType{
						AttrTypes: ConfigConditionalWorkflowValue{}.AttributeTypes(ctx),
					},
				},
				Optional: true,
				Computed: true,
			},
			"execute_target": schema.StringAttribute{
				Required:            true,
				Description:         "The execution target. eg. local,remote,resource. The default value varies by task type.\n",
				MarkdownDescription: "The execution target. eg. local,remote,resource. The default value varies by task type.\n",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"local",
						"remote",
						"resource",
					),
				},
			},
			"id": schema.Int64Attribute{
				Computed: true,
			},
			"labels": schema.SetAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "An array of Category labels for filtering",
				MarkdownDescription: "An array of Category labels for filtering",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "A unique name for the task",
				MarkdownDescription: "A unique name for the task",
			},
			"result_type": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"exitCode",
						"keyValue",
						"json",
					),
				},
			},
			"retry_count": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The number of times to retry.",
				MarkdownDescription: "The number of times to retry.",
			},
			"retry_delay_seconds": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The delay, between retries.",
				MarkdownDescription: "The delay, between retries.",
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
			},
			"retryable": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If the task should be retried or not.",
				MarkdownDescription: "If the task should be retried or not.",
				Default:             booldefault.StaticBool(false),
			},
			"task_type_code": schema.StringAttribute{
				Required:            true,
				Description:         "The code for the type of task",
				MarkdownDescription: "The code for the type of task",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"visibility": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "private or public",
				MarkdownDescription: "private or public",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"private",
						"public",
					),
				},
				Default: stringdefault.StaticString("private"),
			},
		},
	}
}

type TaskModel struct {
	AllowCustomConfig         types.Bool                     `tfsdk:"allow_custom_config"`
	Code                      types.String                   `tfsdk:"code"`
	Config                    types.Dynamic                  `tfsdk:"config"`
	ConfigConditionalWorkflow ConfigConditionalWorkflowValue `tfsdk:"config_conditional_workflow"`
	ExecuteTarget             types.String                   `tfsdk:"execute_target"`
	Id                        types.Int64                    `tfsdk:"id"`
	Labels                    types.Set                      `tfsdk:"labels"`
	Name                      types.String                   `tfsdk:"name"`
	ResultType                types.String                   `tfsdk:"result_type"`
	RetryCount                types.Int64                    `tfsdk:"retry_count"`
	RetryDelaySeconds         types.Int64                    `tfsdk:"retry_delay_seconds"`
	Retryable                 types.Bool                     `tfsdk:"retryable"`
	TaskTypeCode              types.String                   `tfsdk:"task_type_code"`
	Visibility                types.String                   `tfsdk:"visibility"`
}

var _ basetypes.ObjectTypable = ConfigConditionalWorkflowType{}

type ConfigConditionalWorkflowType struct {
	basetypes.ObjectType
}

func (t ConfigConditionalWorkflowType) Equal(o attr.Type) bool {
	other, ok := o.(ConfigConditionalWorkflowType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConfigConditionalWorkflowType) String() string {
	return "ConfigConditionalWorkflowType"
}

func (t ConfigConditionalWorkflowType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewConfigConditionalWorkflowValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigConditionalWorkflowValueNull(), nil
	}

	attributes := in.Attributes()

	conditionalScriptAttribute, ok := attributes["conditional_script"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`conditional_script is missing from object`,
		)

		return nil, diags
	}

	conditionalScriptVal, ok := conditionalScriptAttribute.(customtypes.TrimmedString)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`conditional_script expected to be customtypes.TrimmedString, was: %T`, conditionalScriptAttribute),
		)
	}

	elseOperationalWorkflowIdAttribute, ok := attributes["else_operational_workflow_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`else_operational_workflow_id is missing from object`,
		)

		return nil, diags
	}

	elseOperationalWorkflowIdVal, ok := elseOperationalWorkflowIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`else_operational_workflow_id expected to be basetypes.Int64Value, was: %T`, elseOperationalWorkflowIdAttribute),
		)
	}

	elseOperationalWorkflowNameAttribute, ok := attributes["else_operational_workflow_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`else_operational_workflow_name is missing from object`,
		)

		return nil, diags
	}

	elseOperationalWorkflowNameVal, ok := elseOperationalWorkflowNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`else_operational_workflow_name expected to be basetypes.StringValue, was: %T`, elseOperationalWorkflowNameAttribute),
		)
	}

	ifOperationalWorkflowIdAttribute, ok := attributes["if_operational_workflow_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`if_operational_workflow_id is missing from object`,
		)

		return nil, diags
	}

	ifOperationalWorkflowIdVal, ok := ifOperationalWorkflowIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`if_operational_workflow_id expected to be basetypes.Int64Value, was: %T`, ifOperationalWorkflowIdAttribute),
		)
	}

	ifOperationalWorkflowNameAttribute, ok := attributes["if_operational_workflow_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`if_operational_workflow_name is missing from object`,
		)

		return nil, diags
	}

	ifOperationalWorkflowNameVal, ok := ifOperationalWorkflowNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`if_operational_workflow_name expected to be basetypes.StringValue, was: %T`, ifOperationalWorkflowNameAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConfigConditionalWorkflowValue{
		ConditionalScript:           conditionalScriptVal,
		ElseOperationalWorkflowId:   elseOperationalWorkflowIdVal,
		ElseOperationalWorkflowName: elseOperationalWorkflowNameVal,
		IfOperationalWorkflowId:     ifOperationalWorkflowIdVal,
		IfOperationalWorkflowName:   ifOperationalWorkflowNameVal,
		state:                       attr.ValueStateKnown,
	}, diags
}

func NewConfigConditionalWorkflowValueNull() ConfigConditionalWorkflowValue {
	return ConfigConditionalWorkflowValue{
		state: attr.ValueStateNull,
	}
}

func NewConfigConditionalWorkflowValueUnknown() ConfigConditionalWorkflowValue {
	return ConfigConditionalWorkflowValue{
		state: attr.ValueStateUnknown,
	}
}

func NewConfigConditionalWorkflowValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConfigConditionalWorkflowValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConfigConditionalWorkflowValue Attribute Value",
				"While creating a ConfigConditionalWorkflowValue value, a missing attribute value was detected. "+
					"A ConfigConditionalWorkflowValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigConditionalWorkflowValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConfigConditionalWorkflowValue Attribute Type",
				"While creating a ConfigConditionalWorkflowValue value, an invalid attribute value was detected. "+
					"A ConfigConditionalWorkflowValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigConditionalWorkflowValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConfigConditionalWorkflowValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConfigConditionalWorkflowValue Attribute Value",
				"While creating a ConfigConditionalWorkflowValue value, an extra attribute value was detected. "+
					"A ConfigConditionalWorkflowValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConfigConditionalWorkflowValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConfigConditionalWorkflowValueUnknown(), diags
	}

	conditionalScriptAttribute, ok := attributes["conditional_script"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`conditional_script is missing from object`,
		)

		return NewConfigConditionalWorkflowValueUnknown(), diags
	}

	conditionalScriptVal, ok := conditionalScriptAttribute.(customtypes.TrimmedString)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`conditional_script expected to be customtypes.TrimmedString, was: %T`, conditionalScriptAttribute),
		)
	}

	elseOperationalWorkflowIdAttribute, ok := attributes["else_operational_workflow_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`else_operational_workflow_id is missing from object`,
		)

		return NewConfigConditionalWorkflowValueUnknown(), diags
	}

	elseOperationalWorkflowIdVal, ok := elseOperationalWorkflowIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`else_operational_workflow_id expected to be basetypes.Int64Value, was: %T`, elseOperationalWorkflowIdAttribute),
		)
	}

	elseOperationalWorkflowNameAttribute, ok := attributes["else_operational_workflow_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`else_operational_workflow_name is missing from object`,
		)

		return NewConfigConditionalWorkflowValueUnknown(), diags
	}

	elseOperationalWorkflowNameVal, ok := elseOperationalWorkflowNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`else_operational_workflow_name expected to be basetypes.StringValue, was: %T`, elseOperationalWorkflowNameAttribute),
		)
	}

	ifOperationalWorkflowIdAttribute, ok := attributes["if_operational_workflow_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`if_operational_workflow_id is missing from object`,
		)

		return NewConfigConditionalWorkflowValueUnknown(), diags
	}

	ifOperationalWorkflowIdVal, ok := ifOperationalWorkflowIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`if_operational_workflow_id expected to be basetypes.Int64Value, was: %T`, ifOperationalWorkflowIdAttribute),
		)
	}

	ifOperationalWorkflowNameAttribute, ok := attributes["if_operational_workflow_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`if_operational_workflow_name is missing from object`,
		)

		return NewConfigConditionalWorkflowValueUnknown(), diags
	}

	ifOperationalWorkflowNameVal, ok := ifOperationalWorkflowNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`if_operational_workflow_name expected to be basetypes.StringValue, was: %T`, ifOperationalWorkflowNameAttribute),
		)
	}

	if diags.HasError() {
		return NewConfigConditionalWorkflowValueUnknown(), diags
	}

	return ConfigConditionalWorkflowValue{
		ConditionalScript:           conditionalScriptVal,
		ElseOperationalWorkflowId:   elseOperationalWorkflowIdVal,
		ElseOperationalWorkflowName: elseOperationalWorkflowNameVal,
		IfOperationalWorkflowId:     ifOperationalWorkflowIdVal,
		IfOperationalWorkflowName:   ifOperationalWorkflowNameVal,
		state:                       attr.ValueStateKnown,
	}, diags
}

func NewConfigConditionalWorkflowValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConfigConditionalWorkflowValue {
	object, diags := NewConfigConditionalWorkflowValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewConfigConditionalWorkflowValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConfigConditionalWorkflowType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConfigConditionalWorkflowValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConfigConditionalWorkflowValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigConditionalWorkflowValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConfigConditionalWorkflowValueMust(ConfigConditionalWorkflowValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ConfigConditionalWorkflowType) ValueType(ctx context.Context) attr.Value {
	return ConfigConditionalWorkflowValue{}
}

var _ basetypes.ObjectValuable = ConfigConditionalWorkflowValue{}

type ConfigConditionalWorkflowValue struct {
	ConditionalScript           customtypes.TrimmedString `tfsdk:"conditional_script"`
	ElseOperationalWorkflowId   basetypes.Int64Value      `tfsdk:"else_operational_workflow_id"`
	ElseOperationalWorkflowName basetypes.StringValue     `tfsdk:"else_operational_workflow_name"`
	IfOperationalWorkflowId     basetypes.Int64Value      `tfsdk:"if_operational_workflow_id"`
	IfOperationalWorkflowName   basetypes.StringValue     `tfsdk:"if_operational_workflow_name"`
	state                       attr.ValueState
}

func (v ConfigConditionalWorkflowValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["conditional_script"] = customtypes.TrimmedStringType{}.TerraformType(ctx)
	attrTypes["else_operational_workflow_id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["else_operational_workflow_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["if_operational_workflow_id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["if_operational_workflow_name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.ConditionalScript.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["conditional_script"] = val

		val, err = v.ElseOperationalWorkflowId.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["else_operational_workflow_id"] = val

		val, err = v.ElseOperationalWorkflowName.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["else_operational_workflow_name"] = val

		val, err = v.IfOperationalWorkflowId.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["if_operational_workflow_id"] = val

		val, err = v.IfOperationalWorkflowName.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["if_operational_workflow_name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConfigConditionalWorkflowValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConfigConditionalWorkflowValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConfigConditionalWorkflowValue) String() string {
	return "ConfigConditionalWorkflowValue"
}

func (v ConfigConditionalWorkflowValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"conditional_script":             customtypes.TrimmedStringType{},
		"else_operational_workflow_id":   basetypes.Int64Type{},
		"else_operational_workflow_name": basetypes.StringType{},
		"if_operational_workflow_id":     basetypes.Int64Type{},
		"if_operational_workflow_name":   basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"conditional_script":             v.ConditionalScript,
			"else_operational_workflow_id":   v.ElseOperationalWorkflowId,
			"else_operational_workflow_name": v.ElseOperationalWorkflowName,
			"if_operational_workflow_id":     v.IfOperationalWorkflowId,
			"if_operational_workflow_name":   v.IfOperationalWorkflowName,
		},
	)

	return objVal, diags
}

func (v ConfigConditionalWorkflowValue) Equal(o attr.Value) bool {
	other, ok := o.(ConfigConditionalWorkflowValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ConditionalScript.Equal(other.ConditionalScript) {
		return false
	}

	if !v.ElseOperationalWorkflowId.Equal(other.ElseOperationalWorkflowId) {
		return false
	}

	if !v.ElseOperationalWorkflowName.Equal(other.ElseOperationalWorkflowName) {
		return false
	}

	if !v.IfOperationalWorkflowId.Equal(other.IfOperationalWorkflowId) {
		return false
	}

	if !v.IfOperationalWorkflowName.Equal(other.IfOperationalWorkflowName) {
		return false
	}

	return true
}

func (v ConfigConditionalWorkflowValue) Type(ctx context.Context) attr.Type {
	return ConfigConditionalWorkflowType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConfigConditionalWorkflowValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"conditional_script":             customtypes.TrimmedStringType{},
		"else_operational_workflow_id":   basetypes.Int64Type{},
		"else_operational_workflow_name": basetypes.StringType{},
		"if_operational_workflow_id":     basetypes.Int64Type{},
		"if_operational_workflow_name":   basetypes.StringType{},
	}
}
