// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package networkrouterroute

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func NetworkRouterRouteResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"code": schema.StringAttribute{
				Computed: true,
			},
			"default_route": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Can be used to set as default route.",
				MarkdownDescription: "Can be used to set as default route.",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.RequiresReplace(),
				},
				Default: booldefault.StaticBool(false),
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Route description",
				MarkdownDescription: "Route description",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Can be used to enable / disable the route.",
				MarkdownDescription: "Can be used to enable / disable the route.",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.RequiresReplace(),
				},
				Default: booldefault.StaticBool(true),
			},
			"external_id": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"mtu": schema.Int64Attribute{
				Optional:            true,
				Description:         "Maximum Transmission Unit (MTU).",
				MarkdownDescription: "Maximum Transmission Unit (MTU).",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the route.",
				MarkdownDescription: "The name of the route.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"network": schema.StringAttribute{
				Required:            true,
				Description:         "Source IPV4 address or CIDR range.",
				MarkdownDescription: "Source IPV4 address or CIDR range.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"next_hop": schema.StringAttribute{
				Required:            true,
				Description:         "Destination IPV4 address or CIDR range.",
				MarkdownDescription: "Destination IPV4 address or CIDR range.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"provider_id": schema.StringAttribute{
				Computed: true,
			},
			"route_type": schema.StringAttribute{
				Computed: true,
			},
			"router_id": schema.Int64Attribute{
				Required:            true,
				Description:         "ID of the parent router.",
				MarkdownDescription: "ID of the parent router.",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"source_type": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type NetworkRouterRouteModel struct {
	Code         types.String `tfsdk:"code"`
	DefaultRoute types.Bool   `tfsdk:"default_route"`
	Description  types.String `tfsdk:"description"`
	Enabled      types.Bool   `tfsdk:"enabled"`
	ExternalId   types.String `tfsdk:"external_id"`
	Id           types.Int64  `tfsdk:"id"`
	Mtu          types.Int64  `tfsdk:"mtu"`
	Name         types.String `tfsdk:"name"`
	Network      types.String `tfsdk:"network"`
	NextHop      types.String `tfsdk:"next_hop"`
	ProviderId   types.String `tfsdk:"provider_id"`
	RouteType    types.String `tfsdk:"route_type"`
	RouterId     types.Int64  `tfsdk:"router_id"`
	SourceType   types.String `tfsdk:"source_type"`
}
