// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package loadbalancervirtualserver

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-validators/dynamicvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/objectvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/dynamicplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/HPE/terraform-provider-hpe/utils/validators"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func LoadBalancerVirtualServerResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"active": schema.BoolAttribute{
				Computed: true,
			},
			"backend_port": schema.StringAttribute{
				Computed: true,
			},
			"config": schema.DynamicAttribute{
				Optional:            true,
				Description:         "Generic virtual server configuration object. Settings vary by load balancer type.",
				MarkdownDescription: "Generic virtual server configuration object. Settings vary by load balancer type.",
				PlanModifiers: []planmodifier.Dynamic{
					dynamicplanmodifier.RequiresReplace(),
				},
				Validators: []validator.Dynamic{
					dynamicvalidator.ConflictsWith(path.Expressions{path.MatchRoot("config_nsxt")}...),
				},
			},
			"config_nsxt": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"application_profile": schema.Int64Attribute{
						Optional:            true,
						Description:         "The Load Balancer Application Profile ID (`NetworkLoadBalancerProfile`). Use `/api/options/nsxt/nsxtLBVirtualServerApplicationProfile?loadBalancerId={id}&loadBalancerInstance.vipProtocol={protocol}` to list available options.",
						MarkdownDescription: "The Load Balancer Application Profile ID (`NetworkLoadBalancerProfile`). Use `/api/options/nsxt/nsxtLBVirtualServerApplicationProfile?loadBalancerId={id}&loadBalancerInstance.vipProtocol={protocol}` to list available options.",
					},
					"persistence": schema.StringAttribute{
						Optional:            true,
						Description:         "Session persistence mode. Available values depend on protocol. For HTTP: `SOURCE_IP`, `COOKIE`, or empty string (disabled). For TCP/UDP: `SOURCE_IP` or empty string (disabled). Use `/api/options/nsxt/nsxtLBPersistence?loadBalancerId={id}&loadBalancerInstance.vipProtocol={protocol}` to list available options.",
						MarkdownDescription: "Session persistence mode. Available values depend on protocol. For HTTP: `SOURCE_IP`, `COOKIE`, or empty string (disabled). For TCP/UDP: `SOURCE_IP` or empty string (disabled). Use `/api/options/nsxt/nsxtLBPersistence?loadBalancerId={id}&loadBalancerInstance.vipProtocol={protocol}` to list available options.",
						Validators: []validator.String{
							stringvalidator.OneOf("SOURCE_IP", "COOKIE", ""),
							validators.RequiresNonEmptyStringAlsoRequiresInt64At("persistence_profile"),
						},
					},
					"persistence_profile": schema.Int64Attribute{
						Optional:            true,
						Description:         "The persistence profile ID (`NetworkLoadBalancerProfile`). Required when `persistence` is set to a non-empty value (`SOURCE_IP` or `COOKIE`). Use `/api/options/nsxt/nsxtLBPersistenceProfile?loadBalancerId={id}&config.persistence={value}` to list available options.",
						MarkdownDescription: "The persistence profile ID (`NetworkLoadBalancerProfile`). Required when `persistence` is set to a non-empty value (`SOURCE_IP` or `COOKIE`). Use `/api/options/nsxt/nsxtLBPersistenceProfile?loadBalancerId={id}&config.persistence={value}` to list available options.",
						Validators: []validator.Int64{
							int64validator.AlsoRequires(path.Expressions{
								path.MatchRelative().AtParent().AtName("persistence"),
							}...),
						},
					},
					"ssl_client_profile": schema.Int64Attribute{
						Optional:            true,
						Description:         "The SSL client profile ID (`NetworkLoadBalancerProfile`). Only applicable when `ssl_cert` is set to a non-zero value. Use `/api/options/nsxt/nsxtLBClientSSlProfiles?loadBalancerId={id}` to list available options.",
						MarkdownDescription: "The SSL client profile ID (`NetworkLoadBalancerProfile`). Only applicable when `ssl_cert` is set to a non-zero value. Use `/api/options/nsxt/nsxtLBClientSSlProfiles?loadBalancerId={id}` to list available options.",
						Validators: []validator.Int64{
							validators.RequiresNonZeroInt64At("ssl_cert"),
						},
					},
					"ssl_server_profile": schema.Int64Attribute{
						Optional:            true,
						Description:         "The SSL server profile ID (`NetworkLoadBalancerProfile`). Only applicable when `ssl_server_cert` is set to a non-zero value. Use `/api/options/nsxt/nsxtLBServerSSlProfiles?loadBalancerId={id}` to list available options.",
						MarkdownDescription: "The SSL server profile ID (`NetworkLoadBalancerProfile`). Only applicable when `ssl_server_cert` is set to a non-zero value. Use `/api/options/nsxt/nsxtLBServerSSlProfiles?loadBalancerId={id}` to list available options.",
						Validators: []validator.Int64{
							validators.RequiresNonZeroInt64At("ssl_server_cert"),
						},
					},
				},
				CustomType: ConfigNsxtType{
					ObjectType: types.ObjectType{
						AttrTypes: ConfigNsxtValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Description:         "NSX-T virtual server configuration",
				MarkdownDescription: "NSX-T virtual server configuration",
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplace(),
				},
				Validators: []validator.Object{
					objectvalidator.ConflictsWith(path.Expressions{path.MatchRoot("config")}...),
				},
			},
			"date_created": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Description:         "Description",
				MarkdownDescription: "Description",
			},
			"external_address": schema.BoolAttribute{
				Computed: true,
			},
			"external_id": schema.StringAttribute{
				Computed: true,
			},
			"external_port_id": schema.StringAttribute{
				Computed: true,
			},
			"extra_config": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"instance": schema.StringAttribute{
				Computed: true,
			},
			"internal_id": schema.StringAttribute{
				Computed: true,
			},
			"last_updated": schema.StringAttribute{
				Computed: true,
			},
			"load_balancer": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.Int64Attribute{
						Computed: true,
					},
					"ip": schema.StringAttribute{
						Computed: true,
					},
					"name": schema.StringAttribute{
						Computed: true,
					},
					"type": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"code": schema.StringAttribute{
								Computed: true,
							},
							"id": schema.Int64Attribute{
								Computed: true,
							},
							"name": schema.StringAttribute{
								Computed: true,
							},
						},
						CustomType: TypeType{
							ObjectType: types.ObjectType{
								AttrTypes: TypeValue{}.AttributeTypes(ctx),
							},
						},
						Computed: true,
					},
				},
				CustomType: LoadBalancerType{
					ObjectType: types.ObjectType{
						AttrTypes: LoadBalancerValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "The parent load balancer",
				MarkdownDescription: "The parent load balancer",
			},
			"load_balancer_id": schema.Int64Attribute{
				Required:            true,
				Description:         "The ID of the load balancer this virtual server belongs to",
				MarkdownDescription: "The ID of the load balancer this virtual server belongs to",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(), // force new,
				},
			},
			"network_id": schema.StringAttribute{
				Computed: true,
			},
			"pool_id": schema.Int64Attribute{
				Optional:            true,
				Description:         "The ID of the load balancer pool to assign to this virtual server.",
				MarkdownDescription: "The ID of the load balancer pool to assign to this virtual server.",
			},
			"pool_name": schema.StringAttribute{
				Computed: true,
			},
			"removing": schema.BoolAttribute{
				Computed: true,
			},
			"server_name": schema.StringAttribute{
				Computed: true,
			},
			"service_access": schema.StringAttribute{
				Computed: true,
			},
			"service_port": schema.StringAttribute{
				Computed: true,
			},
			"source_address": schema.StringAttribute{
				Computed: true,
			},
			"ssl_cert": schema.Int64Attribute{
				Optional:            true,
				Description:         "SSL Client Certificate ID. Use `0` for none.",
				MarkdownDescription: "SSL Client Certificate ID. Use `0` for none.",
			},
			"ssl_enabled": schema.StringAttribute{
				Computed: true,
			},
			"ssl_mode": schema.StringAttribute{
				Computed: true,
			},
			"ssl_redirect_mode": schema.StringAttribute{
				Computed: true,
			},
			"ssl_server_cert": schema.Int64Attribute{
				Optional:            true,
				Description:         "SSL Server Certificate ID. Use `0` for none.",
				MarkdownDescription: "SSL Server Certificate ID. Use `0` for none.",
			},
			"status": schema.StringAttribute{
				Computed: true,
			},
			"sticky": schema.BoolAttribute{
				Computed: true,
			},
			"subnet_id": schema.StringAttribute{
				Computed: true,
			},
			"vip_address": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "VIP Address. Required when `vip_pool` is not set.",
				MarkdownDescription: "VIP Address. Required when `vip_pool` is not set.",
			},
			"vip_balance": schema.StringAttribute{
				Computed: true,
			},
			"vip_direct_address": schema.StringAttribute{
				Computed: true,
			},
			"vip_hostname": schema.StringAttribute{
				Optional:            true,
				Description:         "VIP Hostname",
				MarkdownDescription: "VIP Hostname",
			},
			"vip_mode": schema.StringAttribute{
				Computed: true,
			},
			"vip_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "VIP Name",
				MarkdownDescription: "VIP Name",
			},
			"vip_pool": schema.Int64Attribute{
				Optional:            true,
				Description:         "Network Pool ID for automatic VIP address allocation. When set, a VIP address will be leased from this pool and `vip_address` does not need to be specified.",
				MarkdownDescription: "Network Pool ID for automatic VIP address allocation. When set, a VIP address will be leased from this pool and `vip_address` does not need to be specified.",
			},
			"vip_port": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "VIP Port",
				MarkdownDescription: "VIP Port",
			},
			"vip_protocol": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "VIP Protocol. For NSX-T load balancers, this is the virtual server type. Allowed values: `http`, `tcp`, `udp`.",
				MarkdownDescription: "VIP Protocol. For NSX-T load balancers, this is the virtual server type. Allowed values: `http`, `tcp`, `udp`.",
				Validators: []validator.String{
					stringvalidator.OneOf("http", "tcp", "udp"),
				},
			},
			"vip_scheme": schema.StringAttribute{
				Computed: true,
			},
			"vip_shared": schema.BoolAttribute{
				Computed: true,
			},
			"vip_source": schema.StringAttribute{
				Computed: true,
			},
			"vip_status": schema.StringAttribute{
				Computed: true,
			},
			"vip_sticky": schema.StringAttribute{
				Computed: true,
			},
			"vip_type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The VIP type. This is primarily used by NSX Advanced Load Balancer (AVI) to distinguish between normal, parent (shared), and child VIPs. It has no effect for NSX-T load balancers and will be null.",
				MarkdownDescription: "The VIP type. This is primarily used by NSX Advanced Load Balancer (AVI) to distinguish between normal, parent (shared), and child VIPs. It has no effect for NSX-T load balancers and will be null.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
		},
	}
}

type LoadBalancerVirtualServerModel struct {
	Active           types.Bool        `tfsdk:"active"`
	BackendPort      types.String      `tfsdk:"backend_port"`
	Config           types.Dynamic     `tfsdk:"config"`
	ConfigNsxt       ConfigNsxtValue   `tfsdk:"config_nsxt"`
	DateCreated      types.String      `tfsdk:"date_created"`
	Description      types.String      `tfsdk:"description"`
	ExternalAddress  types.Bool        `tfsdk:"external_address"`
	ExternalId       types.String      `tfsdk:"external_id"`
	ExternalPortId   types.String      `tfsdk:"external_port_id"`
	ExtraConfig      types.String      `tfsdk:"extra_config"`
	Id               types.Int64       `tfsdk:"id"`
	Instance         types.String      `tfsdk:"instance"`
	InternalId       types.String      `tfsdk:"internal_id"`
	LastUpdated      types.String      `tfsdk:"last_updated"`
	LoadBalancer     LoadBalancerValue `tfsdk:"load_balancer"`
	LoadBalancerId   types.Int64       `tfsdk:"load_balancer_id"`
	NetworkId        types.String      `tfsdk:"network_id"`
	PoolId           types.Int64       `tfsdk:"pool_id"`
	PoolName         types.String      `tfsdk:"pool_name"`
	Removing         types.Bool        `tfsdk:"removing"`
	ServerName       types.String      `tfsdk:"server_name"`
	ServiceAccess    types.String      `tfsdk:"service_access"`
	ServicePort      types.String      `tfsdk:"service_port"`
	SourceAddress    types.String      `tfsdk:"source_address"`
	SslCert          types.Int64       `tfsdk:"ssl_cert"`
	SslEnabled       types.String      `tfsdk:"ssl_enabled"`
	SslMode          types.String      `tfsdk:"ssl_mode"`
	SslRedirectMode  types.String      `tfsdk:"ssl_redirect_mode"`
	SslServerCert    types.Int64       `tfsdk:"ssl_server_cert"`
	Status           types.String      `tfsdk:"status"`
	Sticky           types.Bool        `tfsdk:"sticky"`
	SubnetId         types.String      `tfsdk:"subnet_id"`
	VipAddress       types.String      `tfsdk:"vip_address"`
	VipBalance       types.String      `tfsdk:"vip_balance"`
	VipDirectAddress types.String      `tfsdk:"vip_direct_address"`
	VipHostname      types.String      `tfsdk:"vip_hostname"`
	VipMode          types.String      `tfsdk:"vip_mode"`
	VipName          types.String      `tfsdk:"vip_name"`
	VipPool          types.Int64       `tfsdk:"vip_pool"`
	VipPort          types.Int64       `tfsdk:"vip_port"`
	VipProtocol      types.String      `tfsdk:"vip_protocol"`
	VipScheme        types.String      `tfsdk:"vip_scheme"`
	VipShared        types.Bool        `tfsdk:"vip_shared"`
	VipSource        types.String      `tfsdk:"vip_source"`
	VipStatus        types.String      `tfsdk:"vip_status"`
	VipSticky        types.String      `tfsdk:"vip_sticky"`
	VipType          types.String      `tfsdk:"vip_type"`
}

var _ basetypes.ObjectTypable = ConfigNsxtType{}

type ConfigNsxtType struct {
	basetypes.ObjectType
}

func (t ConfigNsxtType) Equal(o attr.Type) bool {
	other, ok := o.(ConfigNsxtType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConfigNsxtType) String() string {
	return "ConfigNsxtType"
}

func (t ConfigNsxtType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewConfigNsxtValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigNsxtValueNull(), nil
	}

	attributes := in.Attributes()

	applicationProfileAttribute, ok := attributes["application_profile"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`application_profile is missing from object`,
		)

		return nil, diags
	}

	applicationProfileVal, ok := applicationProfileAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`application_profile expected to be basetypes.Int64Value, was: %T`, applicationProfileAttribute),
		)
	}

	persistenceAttribute, ok := attributes["persistence"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`persistence is missing from object`,
		)

		return nil, diags
	}

	persistenceVal, ok := persistenceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`persistence expected to be basetypes.StringValue, was: %T`, persistenceAttribute),
		)
	}

	persistenceProfileAttribute, ok := attributes["persistence_profile"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`persistence_profile is missing from object`,
		)

		return nil, diags
	}

	persistenceProfileVal, ok := persistenceProfileAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`persistence_profile expected to be basetypes.Int64Value, was: %T`, persistenceProfileAttribute),
		)
	}

	sslClientProfileAttribute, ok := attributes["ssl_client_profile"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ssl_client_profile is missing from object`,
		)

		return nil, diags
	}

	sslClientProfileVal, ok := sslClientProfileAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ssl_client_profile expected to be basetypes.Int64Value, was: %T`, sslClientProfileAttribute),
		)
	}

	sslServerProfileAttribute, ok := attributes["ssl_server_profile"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ssl_server_profile is missing from object`,
		)

		return nil, diags
	}

	sslServerProfileVal, ok := sslServerProfileAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ssl_server_profile expected to be basetypes.Int64Value, was: %T`, sslServerProfileAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConfigNsxtValue{
		ApplicationProfile: applicationProfileVal,
		Persistence:        persistenceVal,
		PersistenceProfile: persistenceProfileVal,
		SslClientProfile:   sslClientProfileVal,
		SslServerProfile:   sslServerProfileVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewConfigNsxtValueNull() ConfigNsxtValue {
	return ConfigNsxtValue{
		state: attr.ValueStateNull,
	}
}

func NewConfigNsxtValueUnknown() ConfigNsxtValue {
	return ConfigNsxtValue{
		state: attr.ValueStateUnknown,
	}
}

func NewConfigNsxtValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConfigNsxtValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConfigNsxtValue Attribute Value",
				"While creating a ConfigNsxtValue value, a missing attribute value was detected. "+
					"A ConfigNsxtValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigNsxtValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConfigNsxtValue Attribute Type",
				"While creating a ConfigNsxtValue value, an invalid attribute value was detected. "+
					"A ConfigNsxtValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigNsxtValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConfigNsxtValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConfigNsxtValue Attribute Value",
				"While creating a ConfigNsxtValue value, an extra attribute value was detected. "+
					"A ConfigNsxtValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConfigNsxtValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConfigNsxtValueUnknown(), diags
	}

	applicationProfileAttribute, ok := attributes["application_profile"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`application_profile is missing from object`,
		)

		return NewConfigNsxtValueUnknown(), diags
	}

	applicationProfileVal, ok := applicationProfileAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`application_profile expected to be basetypes.Int64Value, was: %T`, applicationProfileAttribute),
		)
	}

	persistenceAttribute, ok := attributes["persistence"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`persistence is missing from object`,
		)

		return NewConfigNsxtValueUnknown(), diags
	}

	persistenceVal, ok := persistenceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`persistence expected to be basetypes.StringValue, was: %T`, persistenceAttribute),
		)
	}

	persistenceProfileAttribute, ok := attributes["persistence_profile"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`persistence_profile is missing from object`,
		)

		return NewConfigNsxtValueUnknown(), diags
	}

	persistenceProfileVal, ok := persistenceProfileAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`persistence_profile expected to be basetypes.Int64Value, was: %T`, persistenceProfileAttribute),
		)
	}

	sslClientProfileAttribute, ok := attributes["ssl_client_profile"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ssl_client_profile is missing from object`,
		)

		return NewConfigNsxtValueUnknown(), diags
	}

	sslClientProfileVal, ok := sslClientProfileAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ssl_client_profile expected to be basetypes.Int64Value, was: %T`, sslClientProfileAttribute),
		)
	}

	sslServerProfileAttribute, ok := attributes["ssl_server_profile"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ssl_server_profile is missing from object`,
		)

		return NewConfigNsxtValueUnknown(), diags
	}

	sslServerProfileVal, ok := sslServerProfileAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ssl_server_profile expected to be basetypes.Int64Value, was: %T`, sslServerProfileAttribute),
		)
	}

	if diags.HasError() {
		return NewConfigNsxtValueUnknown(), diags
	}

	return ConfigNsxtValue{
		ApplicationProfile: applicationProfileVal,
		Persistence:        persistenceVal,
		PersistenceProfile: persistenceProfileVal,
		SslClientProfile:   sslClientProfileVal,
		SslServerProfile:   sslServerProfileVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewConfigNsxtValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConfigNsxtValue {
	object, diags := NewConfigNsxtValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewConfigNsxtValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConfigNsxtType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConfigNsxtValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConfigNsxtValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigNsxtValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConfigNsxtValueMust(ConfigNsxtValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ConfigNsxtType) ValueType(ctx context.Context) attr.Value {
	return ConfigNsxtValue{}
}

var _ basetypes.ObjectValuable = ConfigNsxtValue{}

type ConfigNsxtValue struct {
	ApplicationProfile basetypes.Int64Value  `tfsdk:"application_profile"`
	Persistence        basetypes.StringValue `tfsdk:"persistence"`
	PersistenceProfile basetypes.Int64Value  `tfsdk:"persistence_profile"`
	SslClientProfile   basetypes.Int64Value  `tfsdk:"ssl_client_profile"`
	SslServerProfile   basetypes.Int64Value  `tfsdk:"ssl_server_profile"`
	state              attr.ValueState
}

func (v ConfigNsxtValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["application_profile"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["persistence"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["persistence_profile"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["ssl_client_profile"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["ssl_server_profile"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.ApplicationProfile.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["application_profile"] = val

		val, err = v.Persistence.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["persistence"] = val

		val, err = v.PersistenceProfile.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["persistence_profile"] = val

		val, err = v.SslClientProfile.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ssl_client_profile"] = val

		val, err = v.SslServerProfile.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ssl_server_profile"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConfigNsxtValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConfigNsxtValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConfigNsxtValue) String() string {
	return "ConfigNsxtValue"
}

func (v ConfigNsxtValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"application_profile": basetypes.Int64Type{},
		"persistence":         basetypes.StringType{},
		"persistence_profile": basetypes.Int64Type{},
		"ssl_client_profile":  basetypes.Int64Type{},
		"ssl_server_profile":  basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"application_profile": v.ApplicationProfile,
			"persistence":         v.Persistence,
			"persistence_profile": v.PersistenceProfile,
			"ssl_client_profile":  v.SslClientProfile,
			"ssl_server_profile":  v.SslServerProfile,
		},
	)

	return objVal, diags
}

func (v ConfigNsxtValue) Equal(o attr.Value) bool {
	other, ok := o.(ConfigNsxtValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ApplicationProfile.Equal(other.ApplicationProfile) {
		return false
	}

	if !v.Persistence.Equal(other.Persistence) {
		return false
	}

	if !v.PersistenceProfile.Equal(other.PersistenceProfile) {
		return false
	}

	if !v.SslClientProfile.Equal(other.SslClientProfile) {
		return false
	}

	if !v.SslServerProfile.Equal(other.SslServerProfile) {
		return false
	}

	return true
}

func (v ConfigNsxtValue) Type(ctx context.Context) attr.Type {
	return ConfigNsxtType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConfigNsxtValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"application_profile": basetypes.Int64Type{},
		"persistence":         basetypes.StringType{},
		"persistence_profile": basetypes.Int64Type{},
		"ssl_client_profile":  basetypes.Int64Type{},
		"ssl_server_profile":  basetypes.Int64Type{},
	}
}

var _ basetypes.ObjectTypable = LoadBalancerType{}

type LoadBalancerType struct {
	basetypes.ObjectType
}

func (t LoadBalancerType) Equal(o attr.Type) bool {
	other, ok := o.(LoadBalancerType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t LoadBalancerType) String() string {
	return "LoadBalancerType"
}

func (t LoadBalancerType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewLoadBalancerValueUnknown(), nil
	}

	if in.IsNull() {
		return NewLoadBalancerValueNull(), nil
	}

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`,
		)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute),
		)
	}

	ipAttribute, ok := attributes["ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip is missing from object`,
		)

		return nil, diags
	}

	ipVal, ok := ipAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip expected to be basetypes.StringValue, was: %T`, ipAttribute),
		)
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`,
		)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute),
		)
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`,
		)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.ObjectValue, was: %T`, typeAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return LoadBalancerValue{
		Id:               idVal,
		Ip:               ipVal,
		Name:             nameVal,
		LoadBalancerType: typeVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewLoadBalancerValueNull() LoadBalancerValue {
	return LoadBalancerValue{
		state: attr.ValueStateNull,
	}
}

func NewLoadBalancerValueUnknown() LoadBalancerValue {
	return LoadBalancerValue{
		state: attr.ValueStateUnknown,
	}
}

func NewLoadBalancerValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (LoadBalancerValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing LoadBalancerValue Attribute Value",
				"While creating a LoadBalancerValue value, a missing attribute value was detected. "+
					"A LoadBalancerValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LoadBalancerValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid LoadBalancerValue Attribute Type",
				"While creating a LoadBalancerValue value, an invalid attribute value was detected. "+
					"A LoadBalancerValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LoadBalancerValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("LoadBalancerValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra LoadBalancerValue Attribute Value",
				"While creating a LoadBalancerValue value, an extra attribute value was detected. "+
					"A LoadBalancerValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra LoadBalancerValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewLoadBalancerValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`,
		)

		return NewLoadBalancerValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute),
		)
	}

	ipAttribute, ok := attributes["ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip is missing from object`,
		)

		return NewLoadBalancerValueUnknown(), diags
	}

	ipVal, ok := ipAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip expected to be basetypes.StringValue, was: %T`, ipAttribute),
		)
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`,
		)

		return NewLoadBalancerValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute),
		)
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`,
		)

		return NewLoadBalancerValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.ObjectValue, was: %T`, typeAttribute),
		)
	}

	if diags.HasError() {
		return NewLoadBalancerValueUnknown(), diags
	}

	return LoadBalancerValue{
		Id:               idVal,
		Ip:               ipVal,
		Name:             nameVal,
		LoadBalancerType: typeVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewLoadBalancerValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) LoadBalancerValue {
	object, diags := NewLoadBalancerValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewLoadBalancerValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t LoadBalancerType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewLoadBalancerValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewLoadBalancerValueUnknown(), nil
	}

	if in.IsNull() {
		return NewLoadBalancerValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewLoadBalancerValueMust(LoadBalancerValue{}.AttributeTypes(ctx), attributes), nil
}

func (t LoadBalancerType) ValueType(ctx context.Context) attr.Value {
	return LoadBalancerValue{}
}

var _ basetypes.ObjectValuable = LoadBalancerValue{}

type LoadBalancerValue struct {
	Id               basetypes.Int64Value  `tfsdk:"id"`
	Ip               basetypes.StringValue `tfsdk:"ip"`
	Name             basetypes.StringValue `tfsdk:"name"`
	LoadBalancerType basetypes.ObjectValue `tfsdk:"type"`
	state            attr.ValueState
}

func (v LoadBalancerValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["ip"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.ObjectType{
		AttrTypes: TypeValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.Id.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Ip.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip"] = val

		val, err = v.Name.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.LoadBalancerType.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v LoadBalancerValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v LoadBalancerValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v LoadBalancerValue) String() string {
	return "LoadBalancerValue"
}

func (v LoadBalancerValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var loadBalancerTypeVal basetypes.ObjectValue

	if v.LoadBalancerType.IsNull() {
		loadBalancerTypeVal = types.ObjectNull(
			TypeValue{}.AttributeTypes(ctx),
		)
	}

	if v.LoadBalancerType.IsUnknown() {
		loadBalancerTypeVal = types.ObjectUnknown(
			TypeValue{}.AttributeTypes(ctx),
		)
	}

	if !v.LoadBalancerType.IsNull() && !v.LoadBalancerType.IsUnknown() {
		loadBalancerTypeVal = types.ObjectValueMust(
			TypeValue{}.AttributeTypes(ctx),
			v.LoadBalancerType.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.Int64Type{},
		"ip":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.ObjectType{
			AttrTypes: TypeValue{}.AttributeTypes(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"ip":   v.Ip,
			"name": v.Name,
			"type": loadBalancerTypeVal,
		},
	)

	return objVal, diags
}

func (v LoadBalancerValue) Equal(o attr.Value) bool {
	other, ok := o.(LoadBalancerValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Ip.Equal(other.Ip) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.LoadBalancerType.Equal(other.LoadBalancerType) {
		return false
	}

	return true
}

func (v LoadBalancerValue) Type(ctx context.Context) attr.Type {
	return LoadBalancerType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v LoadBalancerValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.Int64Type{},
		"ip":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.ObjectType{
			AttrTypes: TypeValue{}.AttributeTypes(ctx),
		},
	}
}

var _ basetypes.ObjectTypable = TypeType{}

type TypeType struct {
	basetypes.ObjectType
}

func (t TypeType) Equal(o attr.Type) bool {
	other, ok := o.(TypeType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TypeType) String() string {
	return "TypeType"
}

func (t TypeType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewTypeValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTypeValueNull(), nil
	}

	attributes := in.Attributes()

	codeAttribute, ok := attributes["code"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`code is missing from object`,
		)

		return nil, diags
	}

	codeVal, ok := codeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`code expected to be basetypes.StringValue, was: %T`, codeAttribute),
		)
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`,
		)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute),
		)
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`,
		)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute),
		)
	}

	if diags.HasError() {
		return nil, diags
	}

	return TypeValue{
		Code:  codeVal,
		Id:    idVal,
		Name:  nameVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTypeValueNull() TypeValue {
	return TypeValue{
		state: attr.ValueStateNull,
	}
}

func NewTypeValueUnknown() TypeValue {
	return TypeValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTypeValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TypeValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TypeValue Attribute Value",
				"While creating a TypeValue value, a missing attribute value was detected. "+
					"A TypeValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TypeValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TypeValue Attribute Type",
				"While creating a TypeValue value, an invalid attribute value was detected. "+
					"A TypeValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TypeValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TypeValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TypeValue Attribute Value",
				"While creating a TypeValue value, an extra attribute value was detected. "+
					"A TypeValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TypeValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTypeValueUnknown(), diags
	}

	codeAttribute, ok := attributes["code"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`code is missing from object`,
		)

		return NewTypeValueUnknown(), diags
	}

	codeVal, ok := codeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`code expected to be basetypes.StringValue, was: %T`, codeAttribute),
		)
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`,
		)

		return NewTypeValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute),
		)
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`,
		)

		return NewTypeValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute),
		)
	}

	if diags.HasError() {
		return NewTypeValueUnknown(), diags
	}

	return TypeValue{
		Code:  codeVal,
		Id:    idVal,
		Name:  nameVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTypeValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TypeValue {
	object, diags := NewTypeValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail(),
			))
		}

		panic("NewTypeValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TypeType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTypeValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTypeValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTypeValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)
	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)
		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTypeValueMust(TypeValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TypeType) ValueType(ctx context.Context) attr.Value {
	return TypeValue{}
}

var _ basetypes.ObjectValuable = TypeValue{}

type TypeValue struct {
	Code  basetypes.StringValue `tfsdk:"code"`
	Id    basetypes.Int64Value  `tfsdk:"id"`
	Name  basetypes.StringValue `tfsdk:"name"`
	state attr.ValueState
}

func (v TypeValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["code"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Code.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["code"] = val

		val, err = v.Id.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)
		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TypeValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TypeValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TypeValue) String() string {
	return "TypeValue"
}

func (v TypeValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"code": basetypes.StringType{},
		"id":   basetypes.Int64Type{},
		"name": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"code": v.Code,
			"id":   v.Id,
			"name": v.Name,
		},
	)

	return objVal, diags
}

func (v TypeValue) Equal(o attr.Value) bool {
	other, ok := o.(TypeValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Code.Equal(other.Code) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	return true
}

func (v TypeValue) Type(ctx context.Context) attr.Type {
	return TypeType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TypeValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"code": basetypes.StringType{},
		"id":   basetypes.Int64Type{},
		"name": basetypes.StringType{},
	}
}
