// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package networkfirewallrulegroup

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func NetworkFirewallRuleGroupResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Description:         "Manages a network firewall rule group resource in Morpheus.",
		MarkdownDescription: "Manages a network firewall rule group resource in Morpheus.",
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Network firewall rule group description",
				MarkdownDescription: "Network firewall rule group description",
			},
			"external_type": schema.StringAttribute{
				Required:            true,
				Description:         "The external type of the firewall rule group (e.g. SecurityPolicy)",
				MarkdownDescription: "The external type of the firewall rule group (e.g. SecurityPolicy)",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"group_layer": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The group layer of the firewall rule group",
				MarkdownDescription: "The group layer of the firewall rule group",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"id": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Network firewall rule group name",
				MarkdownDescription: "Network firewall rule group name",
			},
			"network_integration_id": schema.Int64Attribute{
				Required:            true,
				Description:         "The ID of the network integration",
				MarkdownDescription: "The ID of the network integration",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"priority": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Network firewall rule group priority",
				MarkdownDescription: "Network firewall rule group priority",
			},
		},
	}
}

type NetworkFirewallRuleGroupModel struct {
	Description          types.String `tfsdk:"description"`
	ExternalType         types.String `tfsdk:"external_type"`
	GroupLayer           types.String `tfsdk:"group_layer"`
	Id                   types.Int64  `tfsdk:"id"`
	Name                 types.String `tfsdk:"name"`
	NetworkIntegrationId types.Int64  `tfsdk:"network_integration_id"`
	Priority             types.Int64  `tfsdk:"priority"`
}
