// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package network_router_nat

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func NetworkRouterNatResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the NAT rule",
				MarkdownDescription: "The ID of the NAT rule",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"router_id": schema.Int64Attribute{
				Required:            true,
				Description:         "The ID of the parent network router",
				MarkdownDescription: "The ID of the parent network router",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the NAT rule",
				MarkdownDescription: "Name of the NAT rule",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Description of the NAT rule",
				MarkdownDescription: "Description of the NAT rule",
			},
			"enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether the NAT rule is enabled",
				MarkdownDescription: "Whether the NAT rule is enabled",
				Default:             booldefault.StaticBool(true),
			},
			"source_network": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Source network",
				MarkdownDescription: "Source network",
			},
			"destination_network": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Destination network",
				MarkdownDescription: "Destination network",
			},
			"translated_network": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Translated network",
				MarkdownDescription: "Translated network",
			},
			"priority": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Priority of the NAT rule",
				MarkdownDescription: "Priority of the NAT rule",
			},
			"protocol": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Protocol",
				MarkdownDescription: "Protocol",
			},
		},
	}
}

type NetworkRouterNatModel struct {
	Id                 types.Int64  `tfsdk:"id"`
	RouterId           types.Int64  `tfsdk:"router_id"`
	Name               types.String `tfsdk:"name"`
	Description        types.String `tfsdk:"description"`
	Enabled            types.Bool   `tfsdk:"enabled"`
	SourceNetwork      types.String `tfsdk:"source_network"`
	DestinationNetwork types.String `tfsdk:"destination_network"`
	TranslatedNetwork  types.String `tfsdk:"translated_network"`
	Priority           types.Int64  `tfsdk:"priority"`
	Protocol           types.String `tfsdk:"protocol"`
}
